confluentinc/vscode

src/authProvider.ts
src/graphql/local.ts
src/quickpicks/kafkaClusters.ts
src/quickpicks/schemaRegistryClusters.ts

We had some logs that were at higher levels than necessary, and the GQL local queries were still using console.log and not visible from the Output Channel.
```shell
gulp clicktest
```

chore: update logging

---

package.json

- Add a regex clause for topics to get the 'View in CCloud' menu item working again.
- Fixes https://github.com/confluentinc/vscode/issues/182

Fix for issue #182

---

src/webview/scaffold-form.spec.ts

Remove unused import

---

src/consume.ts
src/webview/canvas/brush.ts
src/webview/canvas/histogram.ts

A quick one. Number of warnings go down to zero now.

Address eslint warnings

---

README.md

Adds a sub-bullet to the README describing behavior when a user signs in to CCloud and then signs out via the browser.
```shell
gulp clicktest
```

add CCloud logout limitation [ci skip]

---

Gulpfile.js
package-lock.json
package.json
src/extension.ts

1. add vsce as dev dependency
2. drop third party errors from sentry logging

Ignore third party errors in sentry logging

---

Gulpfile.js
package-lock.json
package.json
src/extension.ts

🍒 Ignore third party errors in sentry logging

---

THIRD_PARTY_NOTICES.txt

[main] chore: update third party notices [ci skip]

[main] chore: update third party notices [ci skip]

---

src/consume.ts

This version properly counts filtered items in right most bin. I've got an automated test for the algorithm, just didn't move the algorithm to a separate function yet.

Fix histogram counting algorithm for filtered items

---

src/consume.ts

Cherry pick of https://github.com/confluentinc/vscode/pull/315 to main

🍒 Fix histogram counting algorithm for filtered items

---

CHANGELOG.md

- Add notes about extensions settings for disabling server cert verification, as well as setting custom SSL certs.

Update changelog for SSL-related settings

---

CHANGELOG.md

[v0.17.x] Add changelogs for SSL-related settings

---

src/webview/scaffold-form.html

Follow up for https://github.com/confluentinc/vscode/pull/323

Correct use of boolean attribute `required`

---

src/quickpicks/kafkaClusters.ts

https://github.com/user-attachments/assets/ff3d94e4-45b4-45fa-9c1c-9d72b9460a80

Suggest ccloud login when no clusters available for quick pick

---

NOTICE-vsix.txt
THIRD_PARTY_NOTICES.txt

[v0.17.x] chore: update third party notices [ci skip]

[v0.17.x] chore: update third party notices [ci skip]

---

README.md

Remove WSL from the list of known limitations.
-
```shell
gulp clicktest
```

docs: Remove known limitation on WSL support (#75)

---

package.json

Update welcome walkthrough:
1. Add option to login in additional to sign up
2. Move view messages ahead of inspect schemas because it seems more logical to do that first.
3. Add button to create new project in the **Generate file for new project** step
4. Update missing completion events accordingly
Before:
After:
```shell
gulp clicktest
```

Update welcome walkthrough

---

CHANGELOG.md

- Bring 0.17.X changelog changes back into main.
- Run prettier.

Bring changelog up to speed with 0.17.X releases.

---

src/scaffold.ts

- Wraps the project scaffold 'apply' steps in `try ...catch` and handles any errors generated by showing a notification to the user (with option to Try again or Report), and sending the error on to Sentry for further triage. 
Here's what it looks like now if it fails to generate a project after the form submission:
- It's rare and unexpected for the project generation to fail, but if it does we want to be sure users aren't left with no UI feedback. This was an old issue we had in Jira before the project was open sourced. 
```shell
gulp clicktest
```

Project scaffold: Add catch block and msg on error

---

CHANGELOG.md

pull `v0.18.x` to `main`

---

src/models/schema.ts

- Show the schema version number as the primary label schema label in the description in the schema treeview items. The version number is more informative than the unique-within-this-registry schema id.
```shell
gulp clicktest
```

Show the schema version number as the primary label schema label

---

src/scheduler.test.ts

Use sinon sandbox in scheduler tests

---

src/authProvider.ts

- With this change we'll check for the presence of the `AUTH_COMPLETED_KEY` in secret store during authentication and, if it exists, make sure we delete it before attempting to reset it; that way we are sure to call the onChange handler and any listeners can respond to the change.
- We found this gnarly bug today while debugging unrelated issues - I was unable to log in to the extension (it would hang even though the login process appeared successful). It turned out to be a weird state where the AUTH_COMPLETED_KEY was always true and therefore not deleted during a re-auth flow, and so the onChange handler was never called. We depend on the onChange notification to let us know auth is completed, so it seemed to hang forever.  …

Bug fix: auth secret not calling onChange handler

---

src/consume.ts

🍒 v0.18.x capture unknown sidecar responses

---

CHANGELOG.md

From https://github.com/confluentinc/vscode/pull/417

`main` changelog update from `v0.18.x`

---

CHANGELOG.md

- https://github.com/confluentinc/vscode/pull/437

add 0.18.3 changelog entry

---

.github/DISCUSSION_TEMPLATE/ideas.yml

- Adding some new fields to the discussion template to better facilitate solid request/planning approaches.
- Simple YAML additions. I used the format in https://github.com/confluentinc/vscode/discussions/406 but I can't fully validate this YAML scheme will show clean template options from the start of the flow in github without just trying it here.
```shell
gulp clicktest
```

Added better format inputs for future discussions

---

THIRD_PARTY_NOTICES.txt

[main] chore: update third party notices [ci skip]

[main] chore: update third party notices

---

src/webview/message-viewer.html

Fixes #294.
https://github.com/user-attachments/assets/edd620bc-be1d-4a47-995d-b1e04b62395a

Show paused state when stream is paused during empty table state

---

CHANGELOG.md
package.json
src/commands/extra.ts
src/context.ts
src/extension.ts

Similar to the `Copy ID`, `Copy Name`, etc. Just applies to CCloud SR and local Kafka items in the tree view:
https://github.com/user-attachments/assets/a8df3ee1-def9-464d-bd12-7af9dd9a983f
```shell
gulp clicktest
```

add "Copy URI" command+functionality

---

README.md

Update the known limitations to include the recent [increase of our token lifetime from 4 to 8 hours](https://github.com/confluentinc/ide-sidecar/commit/3224e1df8cf76a4181b1586e5e019b347d82d6e7).
-
```shell
gulp clicktest
```

chore: Update known limitations

---

CHANGELOG.md
src/emitters.ts
src/sidecar/authStatusPolling.test.ts
src/sidecar/authStatusPolling.ts
src/sidecar/middlewares.ts

- https://github.com/confluentinc/vscode/pull/465
- https://github.com/confluentinc/vscode/pull/467
- https://github.com/confluentinc/vscode/pull/468

pull `v0.20.x` into `main`

---

CHANGELOG.md

Missed addition from the 0.20.0 release, adding to go out with the 0.20.1 release.
- https://github.com/confluentinc/ide-sidecar/pull/113

[v0.20.x] MINOR: update changelog

---

src/consume.ts
src/webview/message-viewer.ts

Fixing behavior of consume mode dropdown, when switching between tabs.

Persist consume mode and timestamp

---

CHANGELOG.md
src/sidecar/checkArchitecture.ts

- https://github.com/confluentinc/vscode/pull/473
- https://github.com/confluentinc/vscode/pull/474
- (and https://github.com/confluentinc/vscode/pull/479, which was already merged in https://github.com/confluentinc/vscode/pull/478)

pull `0.20.1` changes into `main`

---

package.json

Update the description of the VS Code extension.
-
```shell
gulp clicktest
```

chore: Update description

---

src/commands/schemaUpload.ts
src/extension.ts
src/quickpicks/schemaRegistries.ts
src/quickpicks/schemas.ts
src/storage/resourceLoader.ts
src/viewProviders/resources.ts
src/viewProviders/schemas.ts
src/viewProviders/topics.ts

- Rename file `src/storage/ccloudPreloader.ts` -> `src/storage/resourceLoader.ts`
- Rename class `CCloudResourcePreloader` -> `ResourceLoader`
- Respell a couple of comments accordingly.
- Remove (currently) unused import.
Closes #431.
```shell
gulp clicktest
```

CCLoudPreloader -> ResourceLoader

---

src/extension.ts

- Getting this change into current release to avoid all the Sentry noise ASAP

🍒 Pick "set sampling to zero (#558)" to patch v0.20

---

CHANGELOG.md

- https://github.com/confluentinc/vscode/pull/560

update changelog from `0.20.2`

---

src/commands/docker.test.ts
src/commands/docker.ts
src/docker/configs.test.ts
src/docker/configs.ts
src/errors.ts

https://github.com/confluentinc/vscode/pull/569 into release branch

[v0.21.x] improve notifications when Docker is unreachable (#569)

---

src/commands/docker.test.ts
src/commands/docker.ts

Enforce starting Kafka first, and stopping it last. May need refinement later as more resource types are added.
```shell
gulp clicktest
```

[v0.21.x] enforce local resource start/stop ordering

---

Gulpfile.js
src/extension.ts

https://github.com/confluentinc/vscode/pull/605 to main

adjust Sentry filter behavior and add rollup output source map base

---

README.md

- Extension marketplace blurb for schema create/evolve functionality.
- Closes #518
---

Extension marketplace blurb for schema create/evolve functionality.

---

CHANGELOG.md
src/authn/ccloudProvider.test.ts
src/authn/ccloudProvider.ts
src/extension.ts
src/graphql/environments.ts

- https://github.com/confluentinc/vscode/pull/615
- https://github.com/confluentinc/vscode/pull/620
- https://github.com/confluentinc/vscode/pull/621

`0.21.2` to `main`

---

CHANGELOG.md
package.json
src/commands/topics.ts
src/models/topic.ts
src/sidecar/sidecarHandle.ts
src/webview/topic-config-form.html
src/webview/topic-config-form.ts

- Topic Config form that allows users to update basic configuration items on a CCloud or Local topic. 
- Provides a link to CCloud when appropriate for advanced config. 
| Access on a topic | Form with (fake) error shown | 
| -- | -- |
| <img width="500" alt="Screenshot 2024-11-21 at 8 53 57 AM" src="https://github.com/user-attachments/assets/73c54f2a-01c6-4200-a776-d01c0e7e4672"> | <img width="1028" alt="Screenshot 2024-11-21 at 8 51 07 AM" src="https://github.com/user-attachments/assets/ce34a7b4-1186-4cb3-9d2e-1eb78ff89dde"> |
| Error shown - dark theme | 
| -- |
| <img width="1031" alt="Screenshot 2024-11-21 at 9 01 29 AM" src="https://github.com/user-attachments/assets/364a52b5-550a-487e-8c3d-c6bd0bc690e5"> |
```shell …
```

Topic configuration form

---

src/quickpicks/kafkaClusters.ts
src/quickpicks/schemaRegistries.ts

Closes #547 
I didn't see a point of an empty string if we were checking for CCloudAuthSessions already, but I'm happy to make a change if I missed something. 
```shell
gulp clicktest
```

collapse notifications

---

Gulpfile.js

This means we no longer need to run `gulp apigen format` sequence.

Apply prettier to new generated code in apigen task

---

src/directConnect.ts
src/webview/direct-connect-form.html
src/webview/direct-connect-form.ts

Closes #622 
- Add the ability to connect with either username/password or API key/secret for "direct" connections form
- Clean up the form - some styling, rearrange & validate fields, copy edits, etc
- Slightly smarter validation: Schema Registry URL must begin with http or https (screenshots below), neither Kafka nor SR are required, but you must fill in at least one
- UX and copy edits pending team review next week
- This is still somewhat hidden with the experimental Setting while we iterate and test. To see the option - open VS Code settings and check the box for `Confluent › Experimental: Enable Direct Connections`
| Light | Dark |
| -- | -- |
| <img width="1107" alt="Screenshot 2024-11-26 at 2 27 39 PM" src="https://github.com/user-attachments/assets/72c40e8c-69d1-4c26-a44d-59f50d55 …

Add basic and API key auth to direct connections form

---

package.json

adding keywords for more visibility in the Marketplace
```shell
gulp clicktest
```

update:add keywords

---

src/webview/direct-connect-form.html
src/webview/direct-connect-form.ts

- Some small updates to improve this form based on team feedback & conversations 
- [remove "local" connection type](https://github.com/confluentinc/vscode/commit/30c923813fd247e12616776d49b67e9981057c1c)
- [update copy, labels, placeholder text](https://github.com/confluentinc/vscode/commit/46f0e27ba4e12e95fa1344b262ca3ea2ac986557)
- [enforce platform type ccloud only accepts api credentials](https://github.com/confluentinc/vscode/commit/7b4c0cc4b30f1a7879cb9d91305e1310abb47477)
```shell
gulp clicktest
```

New Connection form updates

---

src/commands/schemaUpload.test.ts
src/commands/schemaUpload.ts

https://github.com/confluentinc/vscode/pull/745 into `main`

🍒 fix avro schema uploads when not using the Avro editor language ID

---

CHANGELOG.md

update changelog for 0.22.0

---

CHANGELOG.md
src/docker/configs.test.ts
src/docker/configs.ts

https://github.com/confluentinc/vscode/pull/756 into main

🍒 suggest disabling `http.fetchAdditionalSupport` for local Docker actions

---

CHANGELOG.md

From https://github.com/confluentinc/vscode/pull/759

add changelog header for 0.22.1

---

package.json
src/models/topic.test.ts
src/models/topic.ts

Closes https://github.com/confluentinc/vscode/issues/659.
Removes `interestingAuthz` (so we don't need to take additional actions when checking authz for an existing operation) and case adjustments when converting authorized operation values to contextValue suffixes.
```shell
gulp clicktest
```

simplify Topic authz context value setup

---

package.json
src/graphql/direct.ts
src/storage/resourceLoader.ts

- Change the consume/browse messages icon to `play-circle`
- Sort direct "environments"/connections in the Resources view
- Sort topics in the Topics view
| <img width="417" alt="image" src="https://github.com/user-attachments/assets/4fec8526-5791-42ff-a9e4-dbe7768a491b" /> | <img width="392" alt="image" src="https://github.com/user-attachments/assets/429206ce-c875-4bcb-a7e8-f8f4850e4faf" /> | 
```shell
gulp clicktest
```

MINOR: small UI updates/fixes

---

src/models/schema.ts

Follow-up to https://github.com/confluentinc/vscode/pull/789
| <img width="368" alt="image" src="https://github.com/user-attachments/assets/e9669a93-4ca4-4b0e-b546-723ecaf9fde0" /> | <img width="458" alt="image" src="https://github.com/user-attachments/assets/68c823ba-c360-4f41-b57a-c4de012a7569" /> | 
```shell
gulp clicktest
```

MINOR: sort subject groups in Schemas view

---

src/viewProviders/resources.ts

MINOR: remove leftover debug logs from #780

---

src/sidecar/connections.ts

Adds extra debug logging information when the `<connection>.status.kafka_cluster|schema_registry|ccloud` connected state is `FAILED` so we can see exactly what may have gone wrong.
This is mainly helpful during extension activation when the extension may inform the sidecar of stored connections, since the connection creation (and [update](https://github.com/confluentinc/vscode/pull/798)) flow will show the errors in the webview form when the "test connection" button is pressed.
```shell
gulp clicktest
```

MINOR: add debug logging for `FAILED` connected states

---

src/commands/topics.ts

Closes https://github.com/confluentinc/vscode/issues/819. 
Related to https://github.com/confluentinc/ide-sidecar/issues/268, since the sidecar doesn't support passing `headers` in the produce message flow; we're showing a warning modal so we don't accidentally send "dirty" data to a user's topic unless they select "Produce without headers".
Also ensures any header `value`s are base64-encoded, which was causing the error 400 responses in #819 in the first place.
```shell
gulp clicktest
```

MINOR: show warning modal when trying to produce a message with `headers` to a topic

---

src/commands/topics.ts

Sidecar will soon support producing records with headers (https://github.com/confluentinc/ide-sidecar/pull/271). Merge this PR once its sidecar version is updated here in vscode.
-
```shell
gulp clicktest
```

Remove produce without headers popup

---

src/commands/topics.ts

Follow-up to https://github.com/confluentinc/vscode/pull/829

MINOR: rename button label to "View Message"

---

.semaphore/multi-arch-packaging.yml

https://github.com/confluentinc/vscode/pull/843 to `main`

[main] fix(CI): pass GH token during `gh auth login` for windows builds

---

src/webview/direct-connect-form.html

Cherry pick my prev fix: only required if bootstrap servers exist (#872)

---

src/commands/connections.ts

Closes https://github.com/confluentinc/vscode/issues/873

[v0.23.x] fix: always open new connection form from "Add New Connection" action

---

src/commands/connections.ts

🍒 fix: always open new connection form from "Add New Connection" action

---

CHANGELOG.md
package.json
src/context/values.ts
src/viewProviders/resources.test.ts
src/viewProviders/resources.ts

🍒 fix: update Topics/Schemas empty state when direct connections' resources change

---

src/extension.ts

https://github.com/confluentinc/vscode/pull/871 to `v0.23.x`

[v0.23.x] MINOR: add more filters to Sentry

---

CHANGELOG.md

from https://github.com/confluentinc/vscode/pull/887

update changelog from 0.23.3 release

---

src/extension.ts

MINOR: fix typo

---

.semaphore/multi-arch-packaging.yml
Makefile

#848 into main so we don't have to do https://github.com/confluentinc/vscode/pull/972 again

[main] fix "Upload VSIX files to GitHub" step

---

package-lock.json
package.json
src/webview/direct-connect-form.spec.ts
src/webview/scaffold-form.spec.ts

Note: we need to sanitize some HTML only in the code that tests our web views.
Using proper sanitize script instead of doing regex replace.

Testing: sanitize instead of replace

---

.vscodeignore
Gulpfile.js

🍒 [main] always send `sourcemaps`

---

src/authn/ccloudProvider.ts
src/commands/index.ts
src/commands/topics.ts
src/docker/configs.ts
src/errors.test.ts
src/errors.ts
src/graphql/direct.ts
src/graphql/environments.ts
src/graphql/local.ts
src/graphql/organizations.ts
src/preferences/updates.ts
src/scaffold.ts
src/sidecar/connections/index.ts
src/sidecar/connections/watcher.test.ts
src/sidecar/websocketManager.ts
src/storage/resourceLoader.ts

#984 to main, minus the temporary wrapper hack from https://github.com/confluentinc/vscode/pull/984/commits/5c7efc740df13e23025a650ef22bcfda653b6396

🍒 [main] add handling for `FetchErrors`

---

Gulpfile.js
src/loaders/ccloudResourceLoader.ts
src/loaders/localResourceLoader.ts
src/models/main.test.ts
src/storage/resourceManager.test.ts
src/telemetry/telemetry.test.ts
src/webview/canvas/brush.test.ts
tests/unit/testResources/topic.ts

Adds `src/**/*.test.ts` to our `gulp check` to ensure TS compiling doesn't throw any errors that we would otherwise just see locally.
```shell
gulp clicktest
```

include `*.test.ts` files in TS compiling / `gulp check` step, and also fix errors

---

.github/ISSUE_TEMPLATE/config.yml

Remove reference to Next.js in the docs
-
-
```shell
gulp clicktest
```

Fix issues docs

---

CHANGELOG.md
src/docker/eventListener.test.ts
src/storage/migrations/v2.test.ts
src/storage/migrations/v2.ts
src/storage/resourceManager.test.ts
src/storage/resourceManager.ts

- https://github.com/confluentinc/vscode/pull/1032
- https://github.com/confluentinc/vscode/pull/1035

🍒 [main] fix `Map` storage from VS Code 1.97 update + release 0.24.4 changelog

---

.semaphore/semaphore.yml

hotfix: set `change_in` properties

---

src/models/schema.test.ts
src/models/schema.ts

... as indicated by test coverage omission.

Additional schema model tests

---

CHANGELOG.md
src/commands/kafkaClusters.test.ts
src/commands/kafkaClusters.ts

Bring ["Strip bootstrap server protocols before copying to clipboard" ](https://github.com/confluentinc/vscode/pull/1078) forward into main.

Pull PR-1078 from v25 forward into main.

---

src/loaders/resourceLoader.test.ts
src/loaders/resourceLoader.ts

- Bring fix from https://github.com/confluentinc/vscode/pull/1083 forward into main.

Pull fix for no-schema-registries forward from release 25.

---

README.md

Update to the README to include instructions for offline VSIX installation

add offline vsix instructions

---

src/webview/scaffold-form.ts

- make options display in UI by their order.
- https://github.com/confluentinc/vscode/issues/961
```shell
gulp clicktest
```

Add new options fields to project generation form

---

src/viewProviders/schemas.ts

- Address comment from https://github.com/confluentinc/vscode/pull/1128 that didn't get handled before the merge.

Improve refresh()

---

README.md
package.json

Resolves #1123 
-
```shell
gulp clicktest
```

Remove mentions of early access

---

src/viewProviders/schemas.test.ts
src/viewProviders/topics.test.ts

- Address test description spelling comments from #1144.

Test label phrasing.

---

CHANGELOG.md
README.md

-
-
```shell
gulp clicktest
```

Mention key/schema details feature in README [ci skip]

---

package.json

| |  |
| Before |  <img width="991" alt="image" src="https://github.com/user-attachments/assets/624fd14a-94c1-4b5a-a771-95b1b65e7234" /> |
| After | <img width="1007" alt="image" src="https://github.com/user-attachments/assets/142612b9-5948-4c45-9282-9de4b2385f35" /> |

remove preview tag

---

package.json
src/authz/schemaRegistry.test.ts
src/constants.ts
src/models/environment.ts
src/models/kafkaCluster.test.ts
src/models/kafkaCluster.ts
src/models/schema.test.ts
src/models/schema.ts
src/models/schemaRegistry.ts
src/models/topic.test.ts
src/models/topic.ts

- added utm source for all the confluent cloud api calls for observability
- #1139 
```shell
gulp clicktest
```

added utm source for all the confluent cloud api calls for observability

---

.semaphore/third-party-notices.yml

-
-
```shell
gulp clicktest
```

fix third party services yaml

---

.semaphore/third-party-notices.yml

-
-
```shell
gulp clicktest
```

actually fix third party yaml

---

.semaphore/third-party-notices.yml

-
-
```shell
gulp clicktest
```

Add vault-setup before updating third party notices

---

.semaphore/third-party-notices.yml

follow-up from https://github.com/confluentinc/vscode/pull/1190

[v0.26.x] fix indentation for third party notices config

---

.semaphore/third-party-notices.yml

https://github.com/confluentinc/vscode/pull/1194

[v0.26.x] add vault-setup to third party notices prologue

---

package-lock.json

Resolves https://github.com/confluentinc/vscode/security/dependabot/17

security: `npm audit fix` for babel deps

---

README.md

Closes #1219.
Preview: https://github.com/confluentinc/vscode/blob/djs/os-limitations/README.md#known-limitations

docs: add known limitation based on OS version

---

README.md

Follow-up to https://github.com/confluentinc/vscode/pull/1208

MINOR: update survey link in README

---

src/webview/direct-connect-form.html
src/webview/direct-connect-form.ts

- Mitigates user running into weird bug https://github.com/confluentinc/vscode/issues/1241 since we don't have time for the correct solution at the moment. 
-
```shell
gulp clicktest
```

Disable auth type and add tooltip if Editing

---

src/sidecar/sidecarManager.ts

- Prefer spinnies to forever pain.
-
```shell
gulp clicktest
```

We prefer spinnies to pain.

---

src/webview/direct-connect-form.ts

- See notes on https://github.com/confluentinc/vscode/pull/1287
-
```shell
gulp clicktest
```

🍒 Hotfix from 1.0x to main - gracefully handle undefined SSL enabled field

---

src/sidecar/sidecarManager.ts

- Pull fix from #1284 / 1.0.x branch into main.
- Puts sidecar back into "only send  connection state change websocket events once" mode.
```shell
gulp clicktest
```

Pull PR-1284 forward into main.

---

src/directConnect.ts

- https://github.com/confluentinc/vscode/pull/1294 ➡️ `main`

🍒 deepMerge instead of spread for nested configs (#1294)

---

src/commands/topics.test.ts
src/commands/topics.ts

🍒  [main] fix: `ProduceMessageBadRequestError` needs to wrap the `Response`, not the `ResponseError`

---

docs/CONTRIBUTING.md

Preview: https://github.com/confluentinc/vscode/blob/djs/update-contributing/docs/CONTRIBUTING.md#solve-an-issue

docs: add link for unassigned issues to CONTRIBUTING.md

---

CHANGELOG.md
package.json
src/commands/schemas.ts
src/commands/utils/schemas.test.ts
src/commands/utils/schemas.ts
src/loaders/resourceLoader.ts
src/models/schema.ts

- Context menu command to delete an entire subject (i.e. all related schema versions) from a schema registry using a single gesture.
- Is the whole-subject version of https://github.com/confluentinc/vscode/pull/1308
- There's a [single SR route](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#delete--subjects-(string-%20subject)) for whole-subject deletion.
- Because combo of 'bulk delete' + 'hard deletion' can be toxic if used wrongly, the confirmation input for hard deletion will require user to acknowledge hard deletion, the subject name, AND the number of schemas about to be wiped out ("_hard myTopic-value 17_"), whereas soft deletion just requires the subject name ("_myTopic-value_"), since serialization of existing records will continue to work.
- Closes …

507 delete schema subject group

---

src/constants.ts
src/models/flinkStatement.ts

This PR is the beginning of a stack to provide some foundations before we get into really supporting statement listing and interactions in the Flink Statements view (and same goes for the Flink Artifacts view).
No tests for these new models since they are bound to change in the coming week(s).
Closes #1360.
- https://github.com/confluentinc/vscode/pull/1399 👈 
- https://github.com/confluentinc/vscode/pull/1400
- https://github.com/confluentinc/vscode/pull/1405
- https://github.com/confluentinc/vscode/pull/1406
- placeholder for #1361

add `FlinkStatement*` models

---

src/constants.ts
src/models/flinkArtifact.ts

Same as https://github.com/confluentinc/vscode/pull/1399 but for the Flink Artifacts view.
Closes #1374.
- https://github.com/confluentinc/vscode/pull/1399
- https://github.com/confluentinc/vscode/pull/1400
- https://github.com/confluentinc/vscode/pull/1405 👈 
- https://github.com/confluentinc/vscode/pull/1406
- https://github.com/confluentinc/vscode/pull/1408

add `FlinkArtifact*` models

---

src/context/values.ts
src/extension.ts
src/viewProviders/flinkArtifacts.ts

Same as https://github.com/confluentinc/vscode/pull/1400, but for the Flink Artifacts view.
Closes #1387.
- https://github.com/confluentinc/vscode/pull/1399
- https://github.com/confluentinc/vscode/pull/1400
- https://github.com/confluentinc/vscode/pull/1405
- https://github.com/confluentinc/vscode/pull/1406 👈 
- https://github.com/confluentinc/vscode/pull/1408
```shell
gulp clicktest
```

add `FlinkArtifactsViewProvider`

---

CHANGELOG.md
src/commands/support.test.ts
src/commands/support.ts
src/extension.ts
src/logging.ts
src/sidecar/constants.ts
src/sidecar/sidecarManager.test.ts
src/sidecar/sidecarManager.ts
src/testing.ts
src/utils/file.test.ts
src/utils/file.ts
src/utils/fsWrappers.ts
tests/unit/testUtils.ts

- Bring changes from patches to branch v1.1.x forward into main:
- https://github.com/confluentinc/vscode/pull/1430
- https://github.com/confluentinc/vscode/pull/1436
- https://github.com/confluentinc/vscode/pull/1439
-
```shell
gulp clicktest
```

V1.1.0 into main

---

CHANGELOG.md

- https://github.com/confluentinc/vscode/pull/1445

MINOR: update changelog for #1445

---

src/extension.ts
src/models/flinkStatement.ts

- Offer "View in Confluent Cloud" for Flink statements.
- Closes #1462 
```shell
gulp clicktest
```

Offer "view in confluent cloud" for Flink statements.

---

.semaphore/semaphore.yml

hotfix(CI): add `checkout` back for global config

---

src/utils/timing.test.ts

Closes #1306. Time is hard.
```shell
gulp clicktest
```

fix(test): `pauseWithJitter: should pause`

---

src/storage/resourceManager.test.ts

Doesn't solve the underlying issue(s) with #1487 and #1506, but should hopefully help CI.

add retries for flaky direct connection tests

---

package-lock.json
package.json

Closes https://github.com/confluentinc/vscode/security/dependabot/22
https://github.com/OpenAPITools/openapi-generator-cli/releases/tag/v2.19.1
`gulp apigen` runs clean, no other file changes. ✅

[security] update `openapi-generator-cli`

---

src/commands/kafkaClusters.ts
src/scaffold.ts
src/utils/bootstrapServers.test.ts
src/utils/bootstrapServers.ts

https://github.com/confluentinc/vscode/pull/1548 to main

🍒 [main] fix: remove protocol from bootstrap servers when generating project from Kafka cluster/topic

---

CHANGELOG.md

-
-
```shell
gulp clicktest
```

Move changelog header for 1.2.0

---

src/quickpicks/uris.ts

Addresses #1559 
Here's a screenshot of the behavior on the branch:
```shell
gulp clicktest
```

#1559: adjust quickpick URI function for current file

---

src/docker/workflows/confluent-local.ts
src/sidecar/connections/local.ts
src/storage/constants.ts
src/storage/resourceManager.test.ts
src/storage/resourceManager.ts

quick PR to address #638 
```shell
gulp clicktest
```

chore: delete WorkSpaceStorageKeys.LOCAL_KAFKA_TOPICS 

---

src/flinkStatementResults.ts

-
-
```shell
gulp clicktest
```

Set interval to 800ms (resolves #1591)

---

CHANGELOG.md
src/errors.ts
src/loaders/resourceLoader.test.ts
src/loaders/resourceLoader.ts

https://github.com/confluentinc/vscode/pull/1650 to `v1.2.x` for a patch release

[v1.2.x] fix: allow listing topics if request to list subjects fails

---

CHANGELOG.md
src/commands/utils/flinkStatements.ts
src/loaders/ccloudResourceLoader.test.ts
src/loaders/ccloudResourceLoader.ts
src/scaffold.ts

Pulling release branch fixes over:
- https://github.com/confluentinc/vscode/pull/1689
- https://github.com/confluentinc/vscode/pull/1696

🍒 [main] pull over fixes from `v1.2.x`

---

CHANGELOG.md

https://github.com/confluentinc/vscode/blob/v1.2.x/CHANGELOG.md#121

MINOR: add 1.2.1 release header to CHANGELOG

---

src/extension.ts

| <img width="391" alt="image" src="https://github.com/user-attachments/assets/5f58a0c9-68ec-47f6-9122-8d09e4091ad6" /> | <img width="352" alt="image" src="https://github.com/user-attachments/assets/704f41b6-f6f7-4f9c-8215-9e33af874081" /> | 
All required properties already available: https://github.com/confluentinc/vscode/blob/4d67d97282aedbdc6d1d3a28f0d4e0293f9517cd/src/models/flinkComputePool.ts#L44-L52
Closes #1497, closes #1626.
```shell
gulp clicktest
```

MINOR: enable "Copy ID", "Copy Name", "View in CCloud" actions for compute pools

---

package.json
src/chat/participant.ts
src/chat/summarizers/dockerContainers.ts
src/chat/tools/getDockerContainers.ts
src/chat/tools/registration.ts
src/docker/workflows/confluent-local.ts
src/docker/workflows/cp-schema-registry.ts
src/sidecar/connections/local.ts

This tool adds basic list-container functionality limited to only the Kafka and Schema Registry containers matching the user's [configs](https://github.com/confluentinc/vscode/blob/473a85421c03ecd3cafc64f2243c5fbc1c3f2f25/package.json#L652-L669). Basic information like container name, image repo+tag, status, and any container environment variables starting with `KAFKA_`:
There's a bit of tech debt being addressed here by cleaning up some of the list-containers logic that was copied and pasted in various spots before. Now there are simplified helper functions in `src/sidecar/connections/local.ts` to help simplify listing Kafka/SR containers.
- https://github.com/confluentinc/vscode/pull/1717
- https://github.com/confluentinc/vscode/pull/1721  👈
- …

feat(Copilot): add tool to look up local Kafka/SR Docker containers

---

src/flinkStatementResultsManager.test.ts
src/flinkStatementResultsManager.ts

- Fixes #1753 
-
```shell
gulp clicktest
```

Prevent stop statement erroring out due to in-flight get results request

---

package-lock.json
package.json
src/utils/flinkStatementResults.test.ts
src/utils/flinkStatementResults.ts

- Update changelog processing to match what we have in Confluent Cloud UI.
-
```shell
gulp clicktest
```

Update changelog processing and add tests from internal repo

---

src/commands/flinkStatements.ts

- Explicit logError() call in corner case of Flink statement submission 400 error handling corner case.
- Followup to #1791, #1578.
```shell
gulp clicktest
```

Explicit logError() call in corner case of Flink statement submission 400 corner case.

---

src/models/flinkStatement.test.ts
src/models/flinkStatement.ts

- Main branch version of #1811 
-
```shell
gulp clicktest
```

[main] Use statement name in FlinkStatement.ccloudUrl

---

src/flinkStatementResultsManager.test.ts
src/flinkStatementResultsManager.ts

…ckoff of 500ms (#1821)
* Increase retries to 60 with constant backoff of 500ms
* back to debug
-
-
```shell
gulp clicktest
```

[main] Harden results viewer: Increase num of retries to 60

---

CHANGELOG.md

- https://github.com/confluentinc/vscode/pull/1804

update changelog from 1.3.0 release

---

tsconfig.json

- Also sets `paths` (https://www.typescriptlang.org/tsconfig/#paths) so the compiler can resolve where `vscode-test0-playwright` exists.
-
```shell
gulp clicktest
```

Set `moduleResolution` to `node` for sonarqube to work

---

package-lock.json

Closes https://github.com/confluentinc/vscode/security/dependabot/24

[security] update `tar-fs` via `npm audit fix`

---

src/storage/migrations/registry.ts

- Closes https://github.com/confluentinc/vscode/issues/1970 by sorting migrations numerically, not lexicographically.
-
```shell
gulp clicktest
```

Provide custom comparator.

---

CHANGELOG.md

- Add changelog entry for https://github.com/confluentinc/vscode/pull/2027

Changelog entry for https://github.com/confluentinc/vscode/pull/2027.

---

.semaphore/semaphore.yml
Makefile

- https://github.com/confluentinc/vscode/pull/2039 and https://github.com/confluentinc/vscode/pull/2041
- https://github.com/confluentinc/vscode/pull/2039
- https://github.com/confluentinc/vscode/pull/2051
- https://github.com/confluentinc/vscode/pull/2097

[v1.4.x] pull in CI changes from main

---

package-lock.json

Closes the following:
- https://github.com/confluentinc/vscode/security/dependabot/26
- https://github.com/confluentinc/vscode/security/dependabot/27

[security] bump `brace-expansion` version

---

src/flinkSql/flinkLanguageClientManager.ts
src/flinkSql/languageClient.ts
src/telemetry/events.ts

- Send errors to Sentry and usage to Segment per project telemetry standards. 
- Closes https://github.com/confluentinc/vscode/issues/2118
-
```shell
gulp clicktest
```

Language client telemetry

---

src/authn/ccloudProvider.test.ts
src/authn/ccloudProvider.ts
src/sidecar/logging.ts

https://github.com/confluentinc/vscode/pull/2169 to `main`

🍒 [main] send CCloud auth failed events to Sentry

---

src/commands/schemaUpload.ts

🍒 [main] fix schema upload file extensions

---

src/telemetry/sentryClient.ts

-
-
```shell
gulp clicktest
```

[add from `main`] Sentry client: add rate limiting to prevent single-user spikes (#2173)

---

src/authn/ccloudProvider.ts

- Need to update the context value governing ccloud-connectedness *before* firing off the ccloudConnected event, because many event handlers there ignore the boolean passed into the event emitter and instead check `hasCCloudAuthSession()`, which is based on the context value. 
- While here, make `ConfluentCloudAuthProvider.updateContextValue()` properly async and internally await the context value change so as to guarantee completion prior to returning.
- [`hasCCloudAuthSession()`](https://github.com/confluentinc/vscode/blob/bcdd0124aafb9d26282f6d997f41989533441e20/src/sidecar/connections/ccloud.ts#L50-L58) is implemented on top of checking the context value and is called within many event listeners of `ccloudConnected` event, so ensuring that the context value is updated *before* firing …

Fix order of operations within ccloudProvider::getSessions()

---

CHANGELOG.md

https://github.com/confluentinc/vscode/blob/v1.5.x/CHANGELOG.md#150

update changelog from 1.5.0 release

---

src/viewProviders/flinkArtifacts.test.ts
tests/unit/testResources/flinkArtifact.ts
tests/unit/testResources/index.ts

Adds a test base for Flink Artifacts [a la Flink Statements(https://github.com/confluentinc/vscode/blob/main/tests/unit/testResources/flinkStatement.ts) and updates existing artifact tests.
Resolves #2234 
-
```shell
gulp clicktest
```

testing(UDFs): create flink artifact base 

---

scripts/generate-third-party-notices.sh

use fossa directly since it's installed in Semaphore agent now

use fossa installed in agent directly

---

src/flinkSql/flinkLanguageClientManager.ts

- New explicit method for clearing diagnostics on a Uri.
- Clear the diagnostics of the most recent document if/when reconnecting the language client.
- Closes #2338 against v1.5.x.
- Tests will come when bringing forward into main.
- Was able to clicktest and see it work.
```shell
gulp clicktest
```

[v1.5.x] Clear diagnostics when reconnecting to language server

---

package.json
src/flinkSql/flinkLanguageClientManager.ts

- https://github.com/confluentinc/vscode/pull/2360 closes #2357
- https://github.com/confluentinc/vscode/pull/2366 closes #2365

[main] pull in changes from `v1.5.x`

---

CHANGELOG.md
src/extension.ts
src/telemetry/sentryClient.ts

- https://github.com/confluentinc/vscode/pull/2374
- https://github.com/confluentinc/vscode/pull/2388
- https://github.com/confluentinc/vscode/pull/2389

[main] 🍒 #2388 and update changelog for 1.5.2 and 1.5.3 releases

---

src/directConnect.test.ts
src/directConnect.ts
src/webview/direct-connect-form.html
src/webview/direct-connect-form.spec.ts
src/webview/direct-connect-form.ts
tests/e2e/objects/webviews/DirectConnectionFormWebview.ts

- Moving these fixes to our release branch

🍒 Direct Connections form bug fixes (#2450)

---

src/extension.test.ts

- Address remaining dreg from #2582.
-
```shell
gulp clicktest
```

Address dreg

---

src/models/flinkUDF.ts
src/storage/resourceManager.test.ts

- Fix two lingering nits from #2627.
-
```shell
gulp clicktest
```

Fix lingering nits from #2627

---

package.json

- Group "[Select Kafka Cluster As Flink Database](https://github.com/confluentinc/vscode/blob/20968b1941a6cd36f5045708edd4b50e4326fc57/package.json#L428)" and "[Upload Flink Artifact To Confluent Cloud](https://github.com/confluentinc/vscode/blob/20968b1941a6cd36f5045708edd4b50e4326fc57/package.json#L785)" together.  
- Fixes #2663
```shell
gulp clicktest
```

Update right-click command grouping for database

---

src/quickpicks/cloudProviderRegions.ts

- See comment [here](https://github.com/confluentinc/vscode/pull/2659#discussion_r2391918062) - this label can be an empty string to avoid too many repeating words
1. It's in the Artifact Upload "guided" quickpick flow. Step 2 where you choose the Cloud region/provider 
| -- | -- |
| <img width="723" height="155" alt="label" src="https://github.com/user-attachments/assets/e638f946-3c84-4277-a694-4b5ff3ed3a7d" /> | <img width="700" height="167" alt="no-label" src="https://github.com/user-attachments/assets/9240fbda-c1ba-446e-8566-0e531abc1ca0" /> |

minor: remove this redundant label for separator item 🪓 

---

tests/e2e/specs/scaffold.spec.ts

This change introduces a new E2E test that makes sure we can generate a new project by calling the `vscode://confluentinc.vscode-confluent/projectScaffold` URI.

Add E2E test covering generating project from URI

---

src/webview/direct-connect-form.ts

- Same as https://github.com/confluentinc/vscode/pull/2768 but for 1.7
1.
-

[1.7] Direct connect form: send auth update to host after override

---

src/commands/flinkArtifacts.ts
src/commands/flinkUDFs.ts
src/commands/utils/uploadArtifactOrUDF.ts
src/telemetry/events.ts

> [!NOTE]
> I forgot to checkout 1.7 first! Will do that next time. 🍒 into [1.7] this time 
This PR logs the success and failure of artifact and UDF creation. 
cc: @bcscc 

[main] Telemetry: UDFs, Artifacts -> success/failure

---

src/commands/utils/artifactUploadForm.ts

- Picked from 1.7 release branch - adds telemetry for actions within artifact upload form

Artifacts: add telemetry to upload form steps (🍒 #2789)
