confluentinc/vscode

src/authProvider.ts, src/errors.ts, src/extension.test.ts, src/extension.ts, src/storage/index.ts, src/storage/resourceManager.ts, src/viewProviders/resources.ts, src/viewProviders/schemas.ts, src/viewProviders/topics.ts, tests/unit/testUtils.ts
Fixes https://github.com/confluentinc/vscode/issues/172
Adds a test for the new ExtensionContextNotSetError over the singletons that require it, since testing for the instance properties was giving very strange results and starting turning more into a mocking exercise.
```shell
gulp clicktest
```
=> [0.15.x] fix: prevent view providers' creation before extension activation

eslint.config.mjs
We didn't update these paths after consolidating clients into a single folder.
=> Fix ignore list in eslint config

package-lock.json, package.json, src/consume.ts, src/webview/bindings/view-model.ts, src/webview/canvas/canvas.ts, src/webview/message-viewer.ts, src/webview/scaffold-form.spec.ts, src/webview/timer/timer.ts
I've done some upgrades in [`inertial`](https://github.com/UnknownPrinciple/inertial) over the weekend, upgrading our code with the latest version.
The only breaking changes in the latest version is switch from cleanup callback to AbortSignal provided to `watch()` function. I often had to create an abort signal manually and control it via cleanup callback like this:
```js
os.watch(() => {
const ctl = new AbortController();
doAsyncStuff(ctl.signal);
doAnotherAsyncThing(ctl.signal);
return () => ctl.abort();
});
```
Which is now simplified to:
```js
os.watch((signal) => {
doAsyncStuff(signal);
doAnotherAsyncThing(signal);
})
```
Network requests support signal directly: `fetch(url, { signal })`, same goes to event listeners: `target.addEventListener("event", handler, { signal })`. If the …
=> Upgrade inertial to 0.4.1; use abortsignal if possible

CHANGELOG.md, src/commands/kafkaClusters.ts, src/extension.ts, src/storage/resourceManager.test.ts, src/storage/resourceManager.ts, src/viewProviders/topics.ts
- Rely on the resource manager / workspace storage cache for topics within a cluster. Selecting a kafka cluster will consult this cache before opting to deep-fetch from sidecar (and then it cascading through to CCloud or local kafka rest). The 'refresh' button in the topics view title bar can be used to force a deep fetch. Creating or deleting a topic will also result in a deep fetch (and write into the cache).
- Did so through integrating the local vs ccloud variant ResourceManager topics methods, making two new topics-related methods:
- `setTopicsForCluster(cluster, topics[])`: Determines the right storage manager key to use to fetch either the ccloud or local map from storage, sets (new or overwrite) entry within that map given the cluster id, then writes back to the storage manager. …
=> Use workspace cache for topic list. (#17)

Makefile
A direct link to the assets can be constructed to download publicly available files without the need to install GH cli and authorize.
=> Use curl to download sidecar to avoid dependency on gh cli

src/sidecar/sidecarManager.ts
- If an extension dev happens to be manually running the sidecar in 'dev' mode, it won't have done its full initialization and may return 401 from the health check route, but claiming to be PID 0 in the response headers. `kill(0)` is 'special' and asks the kernel to kill then entire `process group', which then unfortunately essentially logs you out.
- Guard against that by noticing if <= 0, then not raising the exception that will lead us to try to `kill()`.
The only way we could reproduce this codepath is if the sidecar port was being used by a web server that knew our routes, responded 401 to the healthcheck route but also with claiming to be pid 0. This would only happen if the user has startup up the sidecar from source code in `quarkus dev` mode, where it runs with a profile that has …
=> Never try to kill pid zero even if sidecar asks for it

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/docs_report.yml, CONTRIBUTING.md, README.md, package.json, src/sidecar/checkArchitecture.ts
This PR makes sure that we use `Confluent for VS Code` when referencing the VS Code extension.
-
```shell
gulp clicktest
```
=> chore: Use `Confluent for VS Code` when referencing the VS Code extension

CHANGELOG.md, src/authProvider.ts, src/viewProviders/resources.ts, src/viewProviders/schemas.ts, src/viewProviders/topics.ts
Fixes #225 by setting `confluent.ccloudConnectionAvailable` whenever we check for a CCloud connection during the loading of the Resource view's tree items.
```shell
gulp clicktest
```
=> [0.16.x] fix: set `confluent.ccloudConnectionAvailable` during Resources view loading to correct Topic & Schemas view states

CHANGELOG.md, src/sidecar/sidecarHandle.test.ts, src/sidecar/sidecarHandle.ts, src/sidecar/sidecarManager.test.ts, src/sidecar/sidecarManager.ts
Fix for hardening sidecar killing due to mismatched sidecar version vs `quarkus dev`, when the access token filter doesn't kick in like we expect. It is the access token filter that includes the process id of sidecar in the rejection header.
All tests (including new) pass locally.
```shell
gulp clicktest
```
=> Harden sidecar killing. (#46)

CHANGELOG.md, src/commands/diffs.ts, src/documentProviders/index.ts
Use `os.homedir()` instead of looking specifically for the `HOME` env var:
> Returns the string path of the current user's home directory.
> On POSIX, it uses the `$HOME` environment variable if defined. Otherwise it uses the [effective UID](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) to look up the user's home directory.
> On Windows, it uses the `USERPROFILE` environment variable if defined. Otherwise it uses the path to the profile directory of the current user.
✅ `gulp clicktest`ed on `darwin arm64` and `win32 x64`
Resolves https://github.com/confluentinc/vscode/issues/241
```shell
gulp clicktest
```
=> [0.16.x] fix(Windows): home dir lookup for document content provider

CHANGELOG.md, package.json, src/consume.ts, src/quickpicks/topics.ts
For a while now the message viewer was only available via tree item action, mainly because it was bound to the context of a topic entity. In the spirit of vscode-like editors, any kind of repetitive work should be possible to be done via keyboard. Enabling message viewer via command palette means the user doesn't need to get out of their current context, look for the extension in the sidebar or wherever they left topics panel at. In this PR I add a condition to the consume command that uses quick picks for cluster/topic in case if topic entity is not present (which happens if command is used via the command palette, instead of a tree item action).
If a cluster doesn't have any topics, an info message appears on the screen. I'm not quite sure yet what to do if the command is used by …
=> Make message viewer available via command palette

CHANGELOG.md, src/authProvider.ts, src/authz/constants.ts, src/extension.ts, src/models/topic.test.ts, src/quickpicks/topics.ts, src/storage/ccloudPreloader.ts, src/viewProviders/resources.ts, src/viewProviders/schemas.ts, src/viewProviders/topics.ts
- Unified the loading of common CCloud resources backing the Resources and Topics panels, improving
performance and consistency, [issue #147](https://github.com/confluentinc/vscode/issues/147)
- Did so via new CCLoudResourcePreloader singleton class
- Listens for ccloud login events. When connected, immediately starts populating the non-topic-level ccloud resources.
- Method `ensureResourcesLoaded()` allows either the Resources or Topics view controllers to block on the loading having been completed prior to consulting the `ResourceManager` cache for those elements. If the loading has been completed already, will not block.
- Fixes https://github.com/confluentinc/vscode/issues/147 , might possibly also improve https://github.com/confluentinc/vscode/issues/224 .  
All tests passing …
=> Refactor resource loading

src/commands/connections.ts, src/commands/index.ts
Forwards non-"User did not consent to login" errors through to our main command error-catching flow instead of throwing that generic "Failed to create new connection. Please try again." error.
Also adds an error notification for any thrown errors during command invocation to allow the user to show the output channel and get some more information before filing an issue. If it gets too spammy, we can remove the notification or guard against specific (frequent) error scenarios.
https://github.com/user-attachments/assets/78b04ce3-731b-4d72-9fef-f34e56275128
```shell
gulp clicktest
```
=> [0.16.x] fix: remove throwing auth error

.semaphore/semaphore.yml, Makefile
- Skip vault setup in public Semaphore
- Fetch sidecar executable using cURL in public Semaphore
- See #235 for passing public Semaphore pipeline with the same changeset as this PR. Successfully runs lint + tests.
Resolves #234
=> Refactor pipeline to run tests in public Semaphore

CONTRIBUTING.md, src/authz/schemaRegistry.test.ts, src/storage/ccloudPreloader.ts, src/storage/resourceManager.test.ts, src/storage/resourceManager.ts, src/viewProviders/topics.test.ts
- Streamline the caching of the ccloud schema registries -- make one single round trip to the storage manager instead of one per schema registry: `resourceManager.setCCloudSchemaRegistryCluster(single_cluster)` is now `resourceManager.setCCloudSchemaRegistryClusters(array_of_clusters)`.
-  https://github.com/confluentinc/vscode/issues/215
- Tests pass, check, lint, and format tasks run.
```shell
gulp clicktest
```
=> Cache CCloud schema registries more efficiently (#215)

src/scaffold.ts
Closes https://github.com/confluentinc/vscode/issues/195
Replaces the current "Open Folder" button with an "Open New Window for Project" primary button and "Switch to Project" secondary button to add a boolean argument to the `openFolder` command.
```shell
gulp clicktest
```
=> improve: change primary button on project scaffolding notification

src/authProvider.ts, src/extension.ts, src/sidecar/connections.ts
Should make it easier for other callers to get an "internal" view of whether or not we have a valid CCloud connection.
```shell
gulp clicktest
```
=> chore: add convenience functions for CCloud auth session checks

src/authProvider.ts, src/commands/connections.ts, src/commands/organizations.ts, src/extension.ts, src/quickpicks/environments.ts, src/quickpicks/kafkaClusters.ts, src/quickpicks/schemaRegistryClusters.ts, src/sidecar/authStatusPolling.ts, src/sidecar/connections.ts
- Wrap our previous implementations for signing in
- Replace our previous calls to check for true/false on whether we were connected to CCloud -- remaining `getCCloudConnection()` calls explicitly want to check with the sidecar for auth purposes and/or to reuse the `Connection` object
```shell
gulp clicktest
```
=> chore: use `getCCloudAuthSession()` for logging in & checking status

CHANGELOG.md, package.json, src/commands/organizations.ts
- Implement context menu item for the logged-in "Confluent Cloud" resource to copy the user's organization ID to the clipboard.
- https://github.com/confluentinc/vscode/issues/213
```shell
gulp clicktest
```
=> Implement 'Copy Organization ID' context menu item, issue #213.

src/commands/kafkaClusters.ts, src/commands/schemaRegistry.ts
Fixes https://github.com/confluentinc/vscode/issues/282.
The above issue happens whenever an item in a view is highlighted and the view (nav) action is triggered; instead of passing `undefined`, we get whatever the type was that was selected. In this case, we attempted to handle a non-Kafka/-SR cluster during the "Select ____" command logic.
(See `cluster = KafkaTopic` up in the Variables section of the debugger.)
```shell
gulp clicktest
```
=> fix: guard against non-cluster types being passed in "Select ___" commands

CHANGELOG.md, src/extension.ts, src/storage/ccloudPreloader.ts, src/storage/resourceManager.test.ts, src/storage/resourceManager.ts, src/viewProviders/resources.ts, src/viewProviders/schemas.ts, src/viewProviders/topics.test.ts, src/viewProviders/topics.ts
- Unify cached schema use between topics and schemas view providers.
- Make the preloader keep track of 'coarse' vs 'fine grained' resources, with 'coarse' being the environments, kafka clusters, and schema registries. Schemas are now fine-grained cached (and refresh-able)  per schema registry cluster id. Stop pre-loading all of the schemas at ccloud log in time, but instead do it on demand whenever either any topics are loaded for a cluster, or the schema registry is selected and we need to show all of the schemas.
- Fix premature clearing of the deepRefresh flags: ensure it gets cleared after the refreshing is completed, not right after the repaint event fires (but probably before the flag has been observed).
- Simplify the public schema-related methods from ResourceManager, removing …
=> Unify cached schema use between topics and schemas (issue 214)

src/consume.ts
Two things I'm aiming for fixing here.
1. The old algorithm has linear time complexity and performs way too many comparisons as number of messages grow. It significantly affects how filtering feels to the user for large volumes of messages
2. For some reason the old algorithm has weird bins calculation for first bunch of requests, at least in our testing topics
I finally got to make use of skiplist's `find()` method that behaves like binary search, or at least has similar time complexity. See the chart comparing duration to compute the histogram in old and new algorithms. The weird drop down in the New algo data coming from smaller number of bins that histogram starts using at some point as it gets wider range of time (tested on orders_avro since it has higher throughput of messages). …
=> Comparison is the thief of performance

src/commands/connections.ts, src/commands/debugtools.ts, src/commands/diffs.ts, src/commands/environments.ts, src/commands/extra.ts, src/commands/kafkaClusters.ts, src/commands/organizations.ts, src/commands/schemaRegistry.ts, src/commands/schemas.ts, src/commands/support.ts, src/commands/topics.ts, src/extension.ts
Discovered while triaging why tests were failing in https://github.com/confluentinc/vscode/pull/301: registering commands before extension activation just causes all sorts of problems in the test suite.
```shell
gulp clicktest
```
=> fix: convert command registration constants into functions and call at extension activation time

src/commands/kafkaClusters.ts, src/extension.ts, src/viewProviders/topics.ts
* When asking the topics view panel to reset due to a known change to the topics in a cluster, provide the cluster id to the reset() call so that the view panel can filter out repaint requests if not viewing said cluster's topics.
* No need for data member TopicViewProvider.ccloudEnvironment, can be simplified away since its primary use we have a local var that's just as good. One fewer moving part to track then.
Originally stemmed from https://github.com/confluentinc/vscode/issues/247, but we decided that what is prescribed in that ticket is wrong, since at this time only exactly one listener would react, and the contexts at which we want it to react we want to keep synchronous, so remain direct calls to its reset(). …
=> Minor cleanups.

src/consume.ts, src/scheduler.test.ts, src/scheduler.ts
Message Viewer talks a lot to the Consume API. It makes one request at a time, but there can be multiple message viewers opened at once. Initially, to avoid rate limiting, I made it so there's a 500ms delay between requests (if previous request was complete sooner than 500ms) plus some random 0-500ms sleep time so multiple active message viewers don't synchronize and hit rate limiting.
I made a better solution that not only keeps multiple MVs resilient to rate limiting, but also boosts request frequency for a single message viewer (which is now very visible when you consumed retained data). I've implemented a basic scheduling mechanism that ensures at most N async tasks can start within T milliseconds. With current settings, it means active message viewers can make no more than 4 requests …
=> Separation of concerns: shared task scheduler for message viewer API requests

src/scheduler.test.ts, src/scheduler.ts
The scheduler implementation I introduced in https://github.com/confluentinc/vscode/pull/309 mainly assumed the requests not going to take longer than the scheduler's interval and that we should await for the whole async task to complete before switching to the next task in the queue.
For the first thing, I think I overcomplicated the implementation: if "at least" an `interval` should pass before releasing the semaphore, we might as well just explicitly schedule release for the `interval` timeout, without any math. And because of the second thing, the requests that do run longer than the `interval` (e.g. awaiting for new messages appear in the topic) can lead to starvation: other active message viewer may not be able to proceed because of some other MVs waiting for new messages. The case …
=> Avoid unnecessary locking due to long running tasks

src/sidecar/middlewares.ts
There are two ways we invalidate the session on the extension side when it seems to be expired: 401s coming from any API (see https://github.com/confluentinc/vscode/pull/109) and by occasionally polling sidecar (see https://github.com/confluentinc/vscode/pull/110). 
Reported by #336 the first case seems to be triggered by a valid session. When the user attempts to create a topic from the extension for the cluster that already doesn't exist (but the extension hasn't updated its cache yet), the API returns 401 Unauthorized. I've been meaning to do another check in `ccloudAuthSessionInvalidated.event()` to see if the session actually expired, but @flippingbits suggested that we don't really need to invalidate the session in case of 401s at all, since we already have a poller that will it for …
=> Do not automatically invalidate the session on 401 response

Gulpfile.js
- Our error messages in case of failure to retrieve Vault keys were most likely copy-pasted and didn't give an accurate description of the failure. Now they do.
=> minor: Copy edit for Vault error msgs

src/scaffold.ts
-  For project scaffolding (`Generate Project from Template`) we need it to be more obvious how to open your project folder after generating it. Several users have mentioned it's easy to lose track of where files were saved or miss the small info message that currently helps you open the folder in VSCode. With this PR we'll make it a bigger dialog that users can't miss (or dismiss) without taking action. 
- ✅ Design approved! I paired with @alexeyraspopov and @katehollowayconfluent on this solution.
- Fixes issue #312 
- The actions themselves haven't changed, only the presentation of them
- I did confirm that neither new nor current window logs me out of Confluent Cloud in the extension. Yay 🎉 
| -- | -- |
| <img width="1664" alt="before" …
=> UX improvement for opening new project after generating from template

CHANGELOG.md, package.json, src/commands/schemas.test.ts, src/commands/schemas.ts, src/models/schema.test.ts, src/models/schema.ts
- New context menu item "Show Latest Changes" attached to schema registry schema subject groups
having more than one version of the schema. Opens up a diff view between the current and prior
versions, [issue #354](https://github.com/confluentinc/vscode/issues/354).
```shell
gulp clicktest
```
=> Quickly diff the two most recent versions of a schema (subject)

src/utils/timing.test.ts, src/utils/timing.ts
Before:
- Any callbacks run through the IntervalPoller would wait their initial polling time (whether set to regular/high frequency) before being called
After:
- If `runImmediately` is set to `true`, the callback is called once before getting into the `setInterval` flow
```shell
gulp clicktest
```
=> add `runImmediately` flag to `IntervalPoller`

CHANGELOG.md, package.json, src/commands/support.ts, src/viewProviders/support.ts
Pretty minor change overall since we're just wrapping the `workbench.action.openSettings`, but this mainly helps with getting to our extension's settings quickly and easily from anywhere in the UI (command palette or Support view).
https://github.com/user-attachments/assets/8f69af01-548e-4192-8178-28b4384637c6
```shell
gulp clicktest
```
=> feat: add "Open Settings" command and Support view item for easy access

CHANGELOG.md, package.json, src/commands/debugtools.ts, src/consume.ts
Adds a `Show Sidecar Output Channel` command (similar to our `Show Output Channel` command) for easy access, mainly to help with debugging.
First use of it is for unexpected error responses while consuming messages, tested with a local ide-sidecar build with a 20% chance of throwing a `RuntimeException` before returning the `SimpleConsumeMultiPartitionResponse`:
https://github.com/user-attachments/assets/aad691de-5cfb-47f3-b1ed-df6787aacf71
```shell
gulp clicktest
```
=> [v0.18.x] add error notification for unexpected error responses during message consume

src/graphql/local.ts, src/graphql/organizations.ts, src/viewProviders/resources.ts
Mainly aiming to get more information about what's going wrong on in https://github.com/confluentinc/vscode/issues/224.
We've tried a couple different scenarios:
- an account with no associated organization (if they deleted it after account creation) won't be able to complete the CCloud auth flow and will get an authentication failed page in their browser
- an account with no accesses to any resources should see an empty array of organizations and/or environments (but this PR also fixes the `CollapsedState` of the "Confluent Cloud" item)
Based on what we're able to find/see from this update, we can provide a follow-on fix for the above issue (that will also include new tests).
```shell
gulp clicktest
```
=> [v0.18.x] add additional logging/hardening around CCloud resource loading

src/extension.ts
https://docs.sentry.io/platforms/javascript/configuration/filtering/
=> [v0.18.x] filter `ENOENT: no such file or directory, lstat` from Sentry errors

package-lock.json
Addressing https://github.com/confluentinc/vscode/security/dependabot/7 and https://github.com/confluentinc/vscode/security/dependabot/8. None of the packages affecting the extension downloaded from the marketplace.
=> Update rollup and hono

src/authz/schemaRegistry.test.ts, src/commands/schemas.test.ts, src/context.test.ts, src/extension.test.ts, src/preferences/listener.test.ts, src/sidecar/authStatusPolling.test.ts
Attempting to fix some issues with occasional test errors in CI like:
```
TypeError: Cannot read properties of undefined (reading 'restore')
at Context.<anonymous> (out/src/authz/schemaRegistry.test.js:56:13)
at process.processImmediate (node:internal/timers:483:21)
at process.callbackTrampoline (node:internal/async_hooks:130:17)
```
=> cleanup(tests): make Sinon stubs belong to Sinon sandboxes

src/sidecar/sidecarManager.ts
Continuation of https://github.com/confluentinc/vscode/pull/378. Only applicable when the user has the `confluent.debugging.showSidecarExceptions` setting enabled and sees the error notifications:
```shell
gulp clicktest
```
=> MINOR: add "Open Logs" button for sidecar debug (error) notifications

src/authz/schemaRegistry.test.ts
Follow-up to https://github.com/confluentinc/vscode/pull/391 since we're still getting some errors:
In this case, there's no need to `.restore()` this stub since it's already being restored a couple lines up from `sandbox.restore()`
=> remove stub restore() since `sandbox.restore()` handles it

package.json, src/commands/environments.ts, src/commands/kafkaClusters.ts, src/commands/schemas.ts
Closes https://github.com/confluentinc/vscode/issues/283.
Instead of showing actions that we intend to include (but are blocked by sidecar updates or other dependencies), we're hiding them from the UI entirely. The comments around the associated code now also link to this PR so it should be easy to revert the `when` clauses in package.json once we get around to implementing the associated functionality.
The following were also blocked from showing up in the command palette and may need to be reverted once we implement them:
- `confluent.kafka-clusters.item.rename`
- `confluent.resources.item.rename`
The three `confluent.schemaViewer.*` commands already had a `when: false` section in the command palette.
```shell
gulp …
```
=> remove all commands that resulted in "COMING SOON" notifications

src/commands/diffs.ts, src/constants.ts, src/storage/constants.ts, src/storage/resourceManager.test.ts, src/storage/resourceManager.ts
They were previously in `src/constants.ts`, where nothing aside from the ResourceManager used them. It was bothering me that they didn't live in `src/storage/constants.ts`.
=> cleanup: move storage enum constants

src/viewProviders/topics.ts
Closes https://github.com/confluentinc/vscode/issues/397.
We were previously only clearing the locally stored topics and _**not**_ clearing the "focused" (local) Kafka cluster whenever there was a change in local Kafka cluster availability:
Now we properly reset everything in the view (if it was previously focused on a local Kafka cluster):
https://github.com/user-attachments/assets/115e5355-6ae1-4dc1-9398-ba5aceb16b3c
```shell
gulp clicktest
```
=> fix: reset Topics view when focused on a local cluster and `localKafkaConnected` fires

src/authProvider.ts, src/commands/index.ts, src/consume.ts, src/extension.test.ts, src/extension.ts, src/scaffold.ts, src/telemetry.ts, src/telemetry/telemetry.test.ts, src/telemetry/telemetry.ts, src/telemetry/telemetryLogger.ts
- Instead of trying to send the full email to Segment, extract the domain ending and send that. 
- Created a new function specifically for sending a Segment Identify call that handles the details of parsing user data from the Session or UserInfo object. 
- Adds a call to this ^ function during the authentication part of Extension Activation to catch existing sessions. 
- ⚠️ Files changed looks bigger bc I refactored to split off `getTelemetryLogger` from the other functions to make testing easier (since mocking module-level functions is still a challenge) 
- We found that VS Code TelemetryLogger class will [redact any email-looking string via RegEx](https://github.com/microsoft/vscode/blob/main/src/vs/platform/telemetry/common/telemetryUtils.ts#L326). We'd like to filter our final …
=> Update Segment identify calls to remove email, add domain

package.json, src/consume.ts
Closes #285 
- Using WebviewPanelCache, prevent message browsers from duplicating for the same topic (e.g. when clicked on Play button in the sidebar, or via command palette)
- Add extra editor view level control to explicitly duplicate current view. It executes the same consume command for the same topic, but makes sure to create unique ID for the webview panel cache.
https://github.com/user-attachments/assets/e39f899c-0829-40aa-bd93-470211936768
=> Switch to existing message viewer; add explicit duplicate button

src/commands/organizations.ts, src/quickpicks/environments.ts, src/quickpicks/kafkaClusters.ts, src/quickpicks/schemaRegistries.ts, src/sidecar/connections.test.ts, src/sidecar/connections.ts, src/viewProviders/resources.ts
- Reimplement `hasCCloudAuthSession()` atop the `ccloudConnectionAvailable` context value, managed faithfully by the auth provider, freeing need to interact with the auth provider directly.
- No longer need to be async.
- Fix up callers, now instantaneous instead of ~200ms best case.
- Write testlets.
```shell
gulp clicktest
```
=> Make hasCCloudAuthSession() fast and not async.

Gulpfile.js, src/consume.ts, src/scaffold.ts, src/webview-cache.ts, src/webview/message-viewer.html, src/webview/scaffold-form.html, src/webview/uikit/uikit.css
Follow up for #427. In the original implementation I tracked duplicate tabs with unique IDs, so if the original tab was closed, clicking on Play button in the sidebar would not be able to switch to other existing tabs of the same topic. Fixing it here by moving this responsibility to webview cache. The cache now tracks lists of panels per ID, and if `multiple` flag is enabled, it can create a new panel for the id that already has other panels. This resolves the mentioned issue and makes it possible to follow similar pattern in the future for other type of webviews.
Another thing I'm addressing here is the bootstrap code we need to deal with when instantiating a webview. Primarily the part about rendering the template and link static assets to the webview. This now happens inside the …
=> Make webview cache render templates and track multiple panels per id

src/viewProviders/resources.test.ts, src/viewProviders/resources.ts
We saw this behavior before with the persistent CCloud container: if we create the tree item with a `None` collapsible state, then attempt to transition it to `Expanded`, it won't automatically expand:
The fix here is to make sure the `id` changes so VS Code doesn't cache any UI state between those changes so it will actually show up as expanded.
```shell
gulp clicktest
```
=> MINOR fix: set `id` on Local container to fix collapsibleState changes

Makefile
From `man curl`:
```
-f, --fail
(HTTP) Fail with error code 22 and with no response body output at all for HTTP transfers returning HTTP response codes at 400 or greater.
In normal cases when an HTTP server fails to deliver a document, it returns a body of text stating so (which often also describes why and more) and a 4xx HTTP response code. This command line option prevents curl from outputting that data and instead returns error 22 early. By default, curl does not consider HTTP response codes to indicate failure.
```
Our CI would "successfully" fail to download the sidecar executable and store "Not Found" in the executable file. That's bad. The `--fail` will make sure curl exits with non-zero status code.
=> Ensure curling sidecar executable fails on non-200 status

src/sidecar/constants.ts, src/sidecar/sidecarHandle.ts, src/sidecar/sidecarManager.ts
Sets the `SidecarHandle` default headers to accept `application/json` by default, only overridden by the `getTemplatesApi` method so it can accept .zip files.
Fixes the issue where we were seeing non-JSON response bodies returned.
+ more comment updates +JSdoc formatting since some of these areas haven't been touched in months
```shell
gulp clicktest
```
=> fix+cleanup sidecar handle methods

src/emitters.ts, src/sidecar/authStatusPolling.ts, src/sidecar/middlewares.ts
Saw during some more clicktesting that we weren't properly returning from the auth status poller from an `INVALID_TOKEN` status, so we would still get the error notification prompting for users to reauthenticate.
I also noticed that, with careful timing, we could end up in a stuck-progress state after kicking off a request during the `INVALID_TOKEN` status because each middleware was keeping track of its own event emitter and is-notification-open boolean. This moves those up to a global level and ensures the auth poller can fire the event emitter even if no requests are going through the middleware so it can close a progress notification on its own.
```shell
gulp clicktest
```
=> [0.20.x] another `INVALID_TOKEN` handling follow-up

src/sidecar/authStatusPolling.test.ts, src/sidecar/authStatusPolling.ts
This time we're actually firing `nonInvalidTokenStatus` for the right auth status. Also adding back some of the event emitter test behavior removed in https://github.com/confluentinc/vscode/pull/455.
```shell
gulp clicktest
```
=> [v0.20.x] hotfix: move `nonInvalidTokenStatus` placement

CHANGELOG.md, src/sidecar/checkArchitecture.ts
Closes #317.
We previously saw thrown errors floated as error notifications, but something seems to have changed where we only see them in logs. This PR explicitly adds an error notification when the sidecar platform/arch doesn't match the user's platform/arch, along with a button that links directly to the Marketplace to uninstall/install.
https://github.com/user-attachments/assets/fb8b84bc-d6b9-46cc-bcc0-e90d2b23294e
```shell
gulp clicktest
```
=> [v0.20.x] error notification for wrong platform/arch

src/consume.ts, src/webview/message-viewer.ts
Cherry-pick https://github.com/confluentinc/vscode/pull/478 to `v0.20.x`.
=> 🍒 Persist consume mode and timestamp

src/scaffold.ts
- @flippingbits brought this to my attention. Subtle difference but it's easier to read if the list is sorted alphabetically. 💡 
| -- | -- |
| <img width="611" alt="before" src="https://github.com/user-attachments/assets/c591b6a9-4664-4251-825c-b043ffd72aa9"> | <img width="613" alt="after" src="https://github.com/user-attachments/assets/a1c62dff-7656-4e6d-b2c1-a30c09b5b6f4"> |
```shell
gulp clicktest
```
=> minor: sort the template list in the UI

src/commands/kafkaClusters.ts, src/commands/schemaRegistry.ts, src/quickpicks/kafkaClusters.ts, src/quickpicks/schemaRegistries.ts
Reinstate the schema registry quickpick + progress on the schemas view variant, now named `schemaRegistryQuickPickWithViewProgress()`.
Respell the peer one for kafka clusters `kafkaClusterQuickPickWithViewProgress()`.
Basically, keep the plain `...QuickPick()` named function view/progress free like other quickpics, but still have the variants that mark the progress against a specific view.
From https://github.com/confluentinc/vscode/pull/442/files#r1825107775
=> Reintroduce schema registry progress view QP, fix naming.

.vscode-test.js, Gulpfile.js
Separates our `test` task into `testBuild` and `testRun` to allow running tests with the VS Code debugger. Also adds a `.vscode-test.js` file so the [Extension Test Runner extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.extension-test-runner) can discover tests in `out/` after a `testBuild`.
https://code.visualstudio.com/api/working-with-extensions/testing-extension#quick-setup-the-test-cli
Closes #510.
> [!NOTE]  
> To use this locally, you'll need to install+enable the above extension, as well as make sure the `gulp testBuild` process runs so the `*.test.js` files show up in our `out/` directory.
=> add support for running extension tests with VS Code debugger

CHANGELOG.md, package.json, src/commands/docker.ts, src/docker/containers.test.ts, src/docker/containers.ts, src/docker/workflows/base.test.ts, src/docker/workflows/base.ts, src/docker/workflows/confluent-local.test.ts, src/docker/workflows/confluent-local.ts, src/storage/resourceManager.test.ts, src/storage/resourceManager.ts
The other side of https://github.com/confluentinc/vscode/pull/396, adding general functionality to stop containers as part of the local resource workflows.
There is no user input here; based on the Kafka image repo+tag settings, we're listing containers that are currently available, and then explicitly stopping any in a `running` state.
> [!NOTE]  
> If broker containers were started via `confluent local kafka start [--brokers #]`, they will likely not be stoppable by the extension due to different Docker image tags. (The CLI uses `7.6.0`, whereas the extension uses `latest`.)
> <img width="1177" alt="image" src="https://github.com/user-attachments/assets/b8cc7eb3-4018-4579-933a-58e16005b2f9">
- https://github.com/confluentinc/vscode/pull/396 
- …
=> feat(Docker): add "Stop Local Resources" command/action

Gulpfile.js
If the VS code extension is installed for a user that has a space in the path of the user's directory, the extension fails to load due to the URL encoding (% escaping) in the path
When you URL decode the calculated path for the idle-side car binary, the path is formatted in the original form which is understood by the OS path API. I tested this change with a manual update of the extension code (sidecar.js) and the extension worked on my machine again.
-
-
```shell
gulp clicktest
```
=> Fix encoding in idle-sidecar path

src/graphql/local.ts, src/sidecar/connections.test.ts, src/sidecar/connections.ts
Mainly moving the get/create local connection functionality to `src/sidecar/connections.ts` instead of where it previously lived (`src/graphql/local.ts`), to be more generally-usable.
Also added some new tests since `src/sidecar/connections.ts` was largely uncovered, and we have a couple new core functions for getting/creating connections for a spec. We could stand to break some of these out into not-mocked/-stubbed tests, but with the direct connect updates coming, I'd like to hold off for a bit.
```shell
gulp clicktest
```
=> cleanup: refactor connections management for local

package.json, src/authz/schemaRegistry.test.ts, src/commands/schemaRegistry.ts, src/commands/schemas.test.ts, src/context.ts, src/documentProviders/schema.ts, src/documentProviders/schemaDocProvider.test.ts, src/emitters.ts, src/extension.ts, src/graphql/local.ts, src/models/schema.test.ts, src/models/schema.ts, src/models/schemaRegistry.ts, src/quickpicks/kafkaClusters.ts, src/quickpicks/schemaRegistries.ts, src/storage/resourceManager.test.ts, src/viewProviders/resources.test.ts, src/viewProviders/resources.ts, src/viewProviders/schemas.test.ts, src/viewProviders/schemas.ts, src/viewProviders/topics.test.ts, tests/unit/testResources/schema.ts, tests/unit/testResources/schemaRegistry.ts
This is largely a compatibility update/fix to expand our SR usage beyond CCloud connections/environments as a follow-up to https://github.com/confluentinc/vscode/pull/348.
- renames previous SR/schema references with a CCloud prefix for clarity
- adds a `LocalSchemaRegistry` class (and updates the `SchemaRegistry` union type to use it)
- adds a new event emitter for when local SR is connected, used by the Docker event listener for updating the Resources view
- updates the local GraphQL query to pull in any locally-discoverable SR instance based on the [ide-sidecar SchemaRegistryConfig uri](https://github.com/confluentinc/ide-sidecar/blob/main/src/generated/resources/openapi.yaml#L865-L879)
- (this is updated in https://github.com/confluentinc/vscode/pull/401 based on dynamically-assigned …
=> add `LocalSchemaRegistry` class and update general SR handling for local instances

src/scaffold.ts
Since the hitting `ESC` is the same as clicking the "Dismiss" button (due to [`isCloseAffordance=true`](https://github.com/confluentinc/vscode/blob/431c9a977360dea9d7d5e7e088b0316cfe6c0754/src/scaffold.ts#L152)), we should never get `undefined` in the user selection after a `🎉 Project Generated` notification pops up, so we can safely check against the `Dismiss` item being selected to prevent the workspace changing to the new project directory.
Closes #512. 
```shell
gulp clicktest
```
=> MINOR fix: don't switch windows when dismissing project-created notification

CHANGELOG.md, package.json, src/commands/docker.test.ts, src/commands/docker.ts, src/docker/configs.ts, src/docker/constants.ts, src/docker/containers.ts, src/docker/eventListener.ts, src/docker/ports.ts, src/docker/workflows/base.ts, src/docker/workflows/confluent-local.test.ts, src/docker/workflows/confluent-local.ts, src/docker/workflows/cp-schema-registry.test.ts, src/docker/workflows/cp-schema-registry.ts, src/docker/workflows/index.ts, src/extension.ts, src/preferences/constants.ts, src/quickpicks/localResources.ts, src/sidecar/connections.test.ts, src/sidecar/connections.ts, src/storage/ccloudPreloader.ts, src/viewProviders/resources.ts, src/viewProviders/schemas.ts, src/viewProviders/topics.ts, tests/unit/testResources/docker.ts
The next big feature-related follow-up to https://github.com/confluentinc/vscode/pull/396 and https://github.com/confluentinc/vscode/pull/399, this time expanding resource starting and stopping to multiple resource types that can be started and stopped independently of each other, or sequentially.
https://github.com/user-attachments/assets/601fb314-582f-4e26-813c-f137162da811
Instead of "Start Local Resources" / "Stop Local Resources" only affecting Kafka containers, they will prompt the user with a multi-select quickpick:
The `Kafka` resource type also adds a secondary button that will link directly to the associated Docker image settings exposed by the extension:
- If local Kafka containers are already running and discoverable by the extension, Schema Registry can be started by itself. …
=> feat(Docker): implement multi-select quickpick and new workflow to allow starting and stopping local Schema Registry

src/extension.ts
So we don't (continue to) get `ENOENT: no such file or directory, stat` and others
=> remove `lstat` from sentry filter

src/commands/docker.ts, src/docker/configs.ts, src/docker/images.ts
- promote response errors from the `/_ping` endpoint to `error` level (Docker version incompatibility or otherwise) -- this won't be the case if docker isn't running at all; that will still show up under the `can't ping docker` debug log and avoid getting spammy
- add another "Open Logs" button for quickly seeing the above error responses
- remove the image pull response body since it can be hundreds of lines of text with all the ANSI escape codes and related progress updates
```shell
gulp clicktest
```
=> MINOR: logging updates for Docker ping / image pull

src/docker/configs.ts, src/docker/eventListener.ts, src/docker/workflows/cp-schema-registry.test.ts, src/docker/workflows/cp-schema-registry.ts, src/sidecar/connections.ts, src/viewProviders/resources.ts
Closes #525.
To avoid the sidecar caching the local Kafka cluster / SR configuration during any resource changes after the extension activates, we need to delete and recreate the connection with the new configuration.
If we don't do this, we see error responses (after local resources successfully start) when other extension actions are attempting to make requests to the (new) configuration. -- (e.g. listing topics/schemas, consuming messages, creating topics/schemas) -- but the sidecar is referencing the old configuration. This appears in a couple different ways:
- Kafka: an error 408 response with `Timed out waiting for node assignment` (only for Kafka
- Schema Registry: an error 500 response to the effect of `Connection refused: localhost/127.0.0.1:<old port>`
Now, we look discover …
=> fix: reset `LOCAL` connection on managed container "start" events

package.json, src/consume.ts, src/uriHandler.ts
Closes #171 
This PR adds a command to message viewer view that generates a `vscode://` link that can be shared with other vscode/confluent extension users to access predefined message viewer setup.
To make this work, I implemented a data class that represents a snapshot of params, used by the viewer. The structure also implements serialization/deserialization methods for `URLSearchParams` that represent the query part of a URI.
https://github.com/user-attachments/assets/ea2ee01b-94ba-4688-9321-167a922ddc3c
=> Allow sharing message viewer state via links

src/authn/ccloudPolling.test.ts, src/authn/ccloudPolling.ts, src/authn/ccloudProvider.test.ts, src/authn/ccloudProvider.ts, src/extension.test.ts, src/extension.ts
Just renaming and reorganization, no functional changes.
Creates a new `authn/` subdir to house both the CCloud auth provider and the polling we use for checking errors and expiration. Once we start using direct connect auth, we'll add the auth provider in this same subdir.
=> cleanup: add `authn/` subdir

CHANGELOG.md, src/authn/ccloudPolling.test.ts, src/authn/ccloudPolling.ts, src/authn/ccloudProvider.test.ts, src/authn/ccloudProvider.ts, src/errors.ts, src/sidecar/connections.ts, src/utils/timing.ts, tests/unit/testResources/connection.ts
Closes #565 and #500.
This PR fixes two fairly big issues with CCloud authentication/connection management:
- When we get `errors` from a non-`INVALID_TOKEN` status, we weren't invalidating the (VS Code) auth session. This meant all of the sidebar content would persist and appear to the user that they could still interact with their CCloud resources, when that really wasn't the case. ([see fix](https://github.com/confluentinc/vscode/pull/566#discussion_r1835184182))
- The error notification that appeared from an auth-errors scenario would show a "Log in to Confluent Cloud" button that made a call to our auth provider, but it wouldn't actually open the browser due to a flaw in the provider's `getSessions()` logic:
- When the button is clicked (and …
=> fix: auth expiration and error handling

src/commands/docker.test.ts, src/commands/docker.ts, src/docker/configs.test.ts, src/docker/configs.ts, src/errors.ts
Closes #546.
Mainly adjusts where we show the error notification so it can be invoked from `isDockerAvailable()` instead of as a follow-on call, so we can choose whether or not to inform the user about a specific response error (e.g. not meeting the minimum Docker engine API version) or a non-`ResponseError` type.
```shell
gulp clicktest
```
=> improve notifications when Docker is unreachable

src/storage/resourceLoader.ts, src/viewProviders/topics.ts
-  Efficient and concurrent loading of topics and correlating with schemas efficiently within ResourceLoader implementations.
- Because our KafkaTopic instances include an iota of information about if has related schemas, we have to have the schemas from the proper registry (if any) onhand to do the final bits, but can do the route hits concurrently prior to the stitching.
- `CCLoudResourceLoader`'s implementation is cache-aware.
- `LocalResourceLoader`s implementation deep-fetches every time.
-
```shell
gulp clicktest
```
=> Implement ResourceLoader.getTopicsForCluster()

src/commands/docker.ts, src/docker/eventListener.test.ts, src/docker/eventListener.ts, src/docker/workflows/base.test.ts, src/docker/workflows/base.ts
This PR smooths out the UX when attempting to start local resources and existing containers (matching the configured image repo+tag) are found. This previously showed an error notification to the effect of `Existing [Kafka|Schema Registry] container(s) found. Please (re)start or remove it/them and try again`, and only afforded the user a button the Start/Restart them or leave VS Code to handle the existing containers.
Now, we automatically start the container(s) (or restart if any are already showing a `running` state) and bypass the notification(s) and need for user interaction at all.
https://github.com/user-attachments/assets/f1f83088-b5bd-47c8-9a2e-d4e6fbb9c304
One lingering complaint I had with this start/restart flow was it was hard to know what exactly was happening since the tree …
=> [v0.21.x] remove Start/Restart notification for existing Docker containers

Gulpfile.js
- New gulp target `liveTest` for preparing the `out/` directory for within-vscode debugging with breakpoints after having made either test suite or codebase changes.
=> Gulp task for assisting with live testing.

src/extension.ts
Temporarily lifting this filter until we can figure out why all our frames are being marked as third party.
=> [v0.21.x] change Sentry error filter behavior

Gulpfile.js, src/extension.ts
Something was wrong with our build output where all our sourcemap info was being flagged as third party, which meant even when we explicitly called `Sentry.captureException()`, it would mark everything as `third_party_code: true` (https://github.com/confluentinc/vscode/pull/603). 
After doing some digging and enabling Sentry debug mode and viewing logs in the dev tools console, it seemed to be using the wrong paths:
The most minimal fix I could find was ensuring `sourcemapBaseUrl` was set in our build `extOutput`, which then properly associated our extension code in Sentry. We're then able to see the unminified code as expected.
=> [v0.21.x] adjust Sentry filter behavior and add rollup output source map base

CHANGELOG.md, src/authn/ccloudProvider.test.ts, src/authn/ccloudProvider.ts
Follow-up to #566 where our middleware may be using a stale auth status "secret" set by the poller. 
After a user reauthenticates through CCloud, there is a short period of time (before the auth poller sets the correct `VALID_TOKEN` status) where a CCloud-related request can be made and our middleware will pick up the old (usually `FAILED`) status and invalidate the auth session, leading to a misleading state that flashes the sidebar between CCloud-connected/-disconnected.
https://github.com/user-attachments/assets/56ffaa56-e89f-42ef-94b1-7c68891550e0
Now, the CCloud auth provider will explicitly update the secret after a successful (re)authentication (and similarly explicitly delete the secret during a sign-out event), which will then prevent the middleware from incorrectly invalidating …
=> [v0.21.x] fix: update CCloud auth status "secret" on reauthentication

src/graphql/environments.ts
Closes #618.
Removing the `any` type lets the types generated from `gql.tada` using https://github.com/confluentinc/vscode/blob/main/src/graphql/sidecar.graphql do the work. Would be nice to get explicit named types eventually though.
=> [v0.21.x] fix(GQL): handle `null` CCloudEnvironment

package.json, src/context/values.ts
Closes #624.
This just sets an initial experimental setting for us to use in follow-on branches as the direct connection + CP support is developed. It also adds a placeholder context value to be adjusted in a follow-on branch (as one of the responsibilities for https://github.com/confluentinc/vscode/issues/422).
Nothing is using this setting or context value yet.
```shell
gulp clicktest
```
=> add experimental direct connection setting and associated contextValue

src/commands/diffs.ts, src/storage/constants.ts, src/storage/resourceManager.test.ts, src/storage/resourceManager.ts
- Convert individual enums with one or two values which are as keys into the single workspace storage namespace into a single enum. Helps ensure they're all unique. Revisiting them all also helped identify those which should no longer exist (issues #637, #638).
- Have clicktested around and things continue to work well.
- Closes #535.
```shell
gulp clicktest
```
=> Migrate all storage manager keys to a single enum.

src/authn/ccloudPolling.ts, src/authn/ccloudProvider.ts, src/commands/support.ts, src/context/observability.test.ts, src/context/observability.ts, src/extension.ts, src/sidecar/sidecarManager.ts
Closes #449.
This PR adds a singleton class for the purpose of tracking basic extension+sidecar state information that will be used to make support faster and easier for the extension+sidecar teams. See below for the properties we're currently exposing:
https://github.com/confluentinc/vscode/blob/d470043161338dd0427f79d1dfa01fc96f594619/src/context/observability.ts#L18-L40
Test issue with the generated markdown: https://github.com/confluentinc/vscode/issues/600
Follow-on branches:
- creating a wrapper for capturing exceptions to send to Sentry (#599): https://github.com/confluentinc/vscode/pull/616
- allowing the user to download this context along with extension+sidecar logs in a .zip file (#597) 
```shell
gulp clicktest
```
=> introduce `ObservabilityContext`

CHANGELOG.md, src/commands/schemaUpload.test.ts, src/commands/schemaUpload.ts
- Fix the schema upload success message when the uploaded schema gets normalized to an old version for the subject. We handled when it was normalized to the most recent version, just not an older one.
- Closes #642
```shell
gulp clicktest
```
=> Fix schema upload success message when was normalized to a not-most-recent version.

CHANGELOG.md, package.json, src/docker/configs.ts, src/quickpicks/localResources.ts
Closes https://github.com/confluentinc/vscode/issues/664.
Exposes the `confluent.localDocker.schemaRegistryImageTag` setting in package.json and adds a quickpick button for the SR image tag config to allow users to define an image tag other than `latest`:
```shell
gulp clicktest
```
=> expose setting for `confluentinc/cp-schema-registry` image tag

src/webview/direct-connect-form.html, src/webview/topic-config-form.html
- A couple of HTML `</div>` tags got out of place in recent updates to the Topic Config and Direct Connection forms. While these don't cause any user-facing errors (HTML is so resilient!), a part of our tool chain was surfacing them as Syntax Errors. 
- It looks like a lot of line changes, but it's just a cascade of line length format changes after removing the 2 extra closing tags. 
```shell
gulp clicktest
```
=> HTML closing tags fix 

src/clients/kafkaRest/apis/RecordsV3Api.ts, src/clients/kafkaRest/models/ProduceRequestData.ts, src/clients/sidecar-openapi-specs/ce-kafka-rest.openapi.yaml
Resolves #613 
- Adds `subject`, `subject_name_strategy` and `schema_version` parameters as specified in the (non-CE) [Kafka REST spec](https://github.com/confluentinc/ide-sidecar/blob/main/kafka-rest.openapi.yaml#L2475-L2508). Notice that we've excluded `schema` and `schema_id` -- this is because ide-sidecar currently does not support these fields being set in the Records API requests.
- Also adds the `dry_run` query parameter to the Records API. Support for this was added in https://github.com/confluentinc/ide-sidecar/pull/165. This will be used to implement #576.
- Generated API clients using `npx gulp apigen`
=> Augment ce-kafka-rest spec to include schema parameters in Records API

src/directConnectManager.ts, src/emitters.ts, src/storage/resourceLoader.ts, src/viewProviders/schemas.ts, src/viewProviders/topics.ts, tests/unit/testResources/kafkaCluster.ts, tests/unit/testResources/topic.ts
- Resources view now updates across workspaces whenever a connection is added/deleted (instead of only one workspace calling `getResourceViewProvider().refresh()` during create/delete)
- The `DirectConnectionManager`'s secrets listener reinitializes any missing `DirectResourceLoader` instances upon adding/removing connections (cross-workspace)
- Removed the`directConnectionDeleted` emitter since the `DirectConnectionManager`'s secrets listener was already handling that same behavior: https://github.com/confluentinc/vscode/blob/48999081ae62d4a45875667426293e312ab49ad3/src/directConnectManager.ts#L103-L115
- Cleanup for `Direct*` test resources to use other `Direct*` resources' properties instead of randomly generated strings …
=> MINOR: direct connections follow-ups

CHANGELOG.md, src/commands/schemaUpload.ts
- Push the refresh of the schemas view to happen earlier and independent of the user's info message choice to 
"reveal the schema" if we just uploaded a new schema into the being-viewed schema registry.
- We used to do this only after the user canceled the info box, but now we always do it, concurrently with the info box being displayed so as to be efficient time-wise from the user's perspective.
- Closes #640
```shell
gulp clicktest
```
=> Repaint the schema view earlier and always if needed

src/docker/configs.ts
When we're polling the Docker engine API's `/_ping` endpoint and can't reach docker due to it not running (or similar non-ResponseError scenarios), we shouldn't bubble those up to the `error` log level, as it may mislead users into thinking something is wrong. This PR drops those passive `error` logs to `debug`:
Before:
After:
While still floating the error notification if the user attempts to launch a local resource and Docker is still unreachable:
```shell
gulp clicktest
```
=> MINOR: drop non-ResponseError docker logs to `debug`

src/authz/schemaRegistry.ts
Drops one portion of logging from `error` to `debug` when determining, from the SR API error response, whether or not a user can access the Schema Registry subjects.
Before:
After:
Will likely need one more small follow-on branch to update our middlewares to specifically look for this kind of request without masking/silencing any error responses for actions dealing with schema uploads.
```shell
gulp clicktest
```
=> MINOR: drop Schema Registry authz error log to `debug`

src/directConnectManager.ts
- Make sure we're not accidentally deleting the CCloud & Local connections when we create a new Direct Connection
- Noticed an issue where you wouldn't be able to interact with Topics and Schemas from CCloud after adding a new Direct Connection. It looks like we were accidentally de-registering those connections' ResourceLoaders when that new connection came in. 
```shell
gulp clicktest
```
=> bug fix - prevent non-direct connections deregistering when adding a new direct connect

CHANGELOG.md, src/commands/support.ts, src/constants.ts, src/viewProviders/resources.test.ts, src/viewProviders/resources.ts, tests/unit/testUtils.ts
Closes #681.
https://github.com/confluentinc/vscode/pull/554 introduced a regression while trying to avoid re-registering tree view items with the same `id` values, specifically that the top-level (static) container items in the Resources view -- ("Confluent Cloud", "Local", and the currently-experimental "Other") -- would get a new `id` at each refresh. This also meant VS Code would forget whatever the user-adjusted collapsible state was between refreshes, and always side with whatever the extension wanted that collapsible state to be.
To fix that regression while ensuring a smooth path between extension version changes, we're going back to static container item IDs that instead will only change depending on:
- the status of that connection group type (connected vs not-connected)
- the …
=> fix static container `id`s in Resources view

src/context/observability.ts, src/extension.test.ts, src/extension.ts, src/telemetry/eventProcessors.test.ts, src/telemetry/eventProcessors.ts, src/telemetry/telemetry.ts
Continuation of https://github.com/confluentinc/vscode/pull/592 that ensures our `ObservabilityContext` data is included with any events sent to Sentry. The data shows up under "Additional Data":
This also reorganized a bit of code to put all of our Sentry event processors under one place - `telemetry/eventProcessors.ts`, and similarly moved the previous Sentry telemetry config tests into `eventProcessors.test.ts` (along with a new test).
Closes #599. (Isn't a wrapper in this case, but treating it as an event processor seems like the more effective and straightforward approach.)
```shell
gulp clicktest
```
=> add Sentry processor for including observability context

src/commands/docker.ts, src/quickpicks/localResources.ts
This incorporates feedback on the local resource start/stop multi-select quickpick:
- Set the placeholder text describing whether the resources being selected are for starting or stopping
- Auto-select Kafka when starting resources and nothing is running:
- Filter out already-running resources from the quickpick (which closes #536):
- Auto-stop a resource if it's the only kind running (not treating "start" the same since a user may want to look at the image repo/tag and adjust first)
- Prevent stopping only Kafka if SR is also running
```shell
gulp clicktest
```
=> update local resource quickpick

src/sidecar/sidecarManager.ts
Closes #679. Sample from sidecar logs:
```
2024-12-05 18:10:39,071 ... INFO  [io.con.ide.res.app.SidecarInfo] (main) OS: Mac OS X 14.7.1 (MacOS); VS Code 1.95.3, extension version 0.22.0
```
```shell
gulp clicktest
```
=> include VS Code + extension versions in sidecar envs

src/webview/direct-connect-form.html, src/webview/direct-connect-form.ts
- Now we'll track the `bootstrap servers` and `uri` fields' state and use it to determine if auth type is required. This will also set us up to save inputs when the form is blurred (#712)
-
```shell
gulp clicktest
```
=> minor: improve required logic for auth fields

src/commands/connections.ts
- nitpicky update - I think it's more readable to use the `detail` attribute?
| -- | -- |
| <img width="291" alt="Screenshot 2024-12-06 at 12 48 58 PM" src="https://github.com/user-attachments/assets/7bb9ca78-7e18-4bb2-b16c-38e1c1c1feac"> | <img width="288" alt="Screenshot 2024-12-06 at 12 47 18 PM" src="https://github.com/user-attachments/assets/556b202e-5cc7-4e7d-86b9-24e4d4cc89ad"> |
=> minor: improve readability for disconnect warning

Gulpfile.js, src/extension.ts
Uses `SENTRY_ENV` instead of `NODE_ENV` to tell Sentry which environment is being used.
For real "production" releases, this will be `production`. For local builds that set `NODE_ENV=production`, this will be `development`.
```shell
gulp clicktest
```
=> use a custom dev env instead of node

Gulpfile.js
Follow-up to https://github.com/confluentinc/vscode/pull/719, where we may build the .vsix files through CI that include the microversion. We don't want those labeled with the "production" environment tag in Sentry, so those are set as "development". (I was tempted to use "pre-production" but that would likely involve more elaborate checks against the `revision` / `IS_CI` / etc, and the main thing we want is to just make it something other than "production")
```shell
gulp clicktest
```
=> MINOR: set `SENTRY_ENV` to "development" if the microversion is included

CHANGELOG.md, package.json, src/context/values.ts, src/directConnectManager.test.ts, src/directConnectManager.ts, src/extension.ts, src/preferences/constants.ts, src/preferences/listener.test.ts, src/preferences/listener.ts
Closes #721.
This PR adds a "preview" setting to allow users to opt-in to the message producing functionality before it's feature-complete. It doesn't currently affect anything, but it will be used in follow-on branches that expose message producing actions and elements, similar to how we're currently using the direct connection setting.
This included a minor renaming and re-tagging of our existing direct connection setting since it wasn't really an "experiment".
This also required a minor reorganizing of the settings listener to get out of the `DirectConnectionManager` class and into the listener that previously only watched for SSL-related settings changes. Having them all under one place made the most sense.
```shell
gulp …
```
=> feat: add "Enable Produce Messages" preview setting

src/authn/ccloudProvider.ts, src/commands/docker.ts, src/commands/index.ts, src/consume.ts, src/directConnectManager.ts, src/docker/images.ts, src/docker/workflows/base.ts, src/docker/workflows/confluent-local.ts, src/docker/workflows/cp-schema-registry.ts, src/extension.ts, src/scaffold.ts, src/telemetry/events.ts, src/telemetry/telemetry.ts
Closes #489.
Migrates our use of `getTelemetryLogger().logUsage(<string>, data)` to use an enum, which should help us more quickly determine what events are being sent, where we might want/need to clean up or standardize event names, etc. Majority of the changes are in here: https://github.com/confluentinc/vscode/blob/6905985c65970621d59271ffc40174f7f962eb2b/src/telemetry/events.ts#L5-L36
And the rest of the changes are updating imports and previous `getTelemetryLogger().logUsage(<string> ...)` calls.
Same general pattern used in [`setContextValue()`](https://github.com/confluentinc/vscode/blob/main/src/context/values.ts#L12).
```shell
gulp clicktest
```
=> create telemetry event enum and `logUsage()` wrapper

src/directConnectManager.ts, src/emitters.ts, src/viewProviders/schemas.ts, src/viewProviders/topics.ts
Closes #718.
When an environment (or direct connection, which is treated as an environment) changes -- (for now, that just includes renames) -- we need to make sure the `description` used in the tree view reflects any updates to the environment `name`, as well as refresh the underlying items (if this includes a config change).
https://github.com/user-attachments/assets/eaa4c5f1-268a-449d-b377-7da0a4709b55
```shell
gulp clicktest
```
=> add `environmentChanged` event emitter to update Topics/Schemas view descriptions

src/sidecar/connections.ts
Closes #661.
In earlier versions of the sidecar, cluster caching was causing issues relating to using old configs when the extension would make `PUT` requests to update a connection (e.g. changing the local `schema_registry_uri`), so https://github.com/confluentinc/vscode/pull/544 went the aggressive route of trying to explicitly delete and then recreate the `LOCAL` connection.
This is no longer necessary, and we are now occasionally seeing `409 Conflict` error responses when multiple local connection updates fire off in quick succession, so it's safer to go with more of an upsert approach.
```shell
gulp clicktest
```
=> fix for `409 Conflict` responses when updating `LOCAL` connections

src/commands/connections.ts, src/directConnect.ts, src/directConnectManager.test.ts, src/directConnectManager.ts, src/storage/resourceManager.ts, src/webview/direct-connect-form.ts, tests/unit/testResources/connection.ts
This PR mainly adjusts the data we're storing from the direct connection webview form to make it easier to a) log telemetry events, and b) repopulate the webview form when a user wants to edit the config of that connection.
Example logging before firing telemetry events for a direct connection create+delete where we store the `type` from the webview form:
```shell
gulp clicktest
```
=> feat: store form connection type with `CustomConnectionSpec` interface

src/commands/schemaUpload.test.ts, src/commands/schemaUpload.ts
Closes #675.
This mainly refactors our logic when determining the schema type to be used from a file URI in some different scenarios:
- If a user does not have any extension installed that enables the use of the "Avro" (`avroavsc`) editor language, the VS Code default is to use JSON for Avro schema definitions in an editor. We can't trust this, so we need to show the schema type quickpick to the user so they can specify AVRO or JSON.
- If a user has an extension that supports the "Avro" (`avroavsc`) editor language but is working in a `.json` document, we'll ignore the file extension and go with the language ID. This bypasses the need to use the quickpick.
- If the user has an Avro extension installed but is still using the JSON editor language with a .json file extension, we don't trust …
=> [v0.22.x] fix avro schema uploads when not using the Avro editor language ID

CHANGELOG.md, src/docker/configs.test.ts, src/docker/configs.ts
Related to https://github.com/confluentinc/vscode/issues/751 but does not fix the underlying issue (see [discussion](https://github.com/microsoft/vscode-discussions/discussions/2438)). Best we can do for right now is check if the setting is enabled and provide a suggestion for the user to disable the setting when they go to start/stop any local resources.
https://github.com/user-attachments/assets/b42f1fa2-8ba1-41bb-a577-bef22121228a
(The notification wording was slightly [updated](https://github.com/confluentinc/vscode/blob/djs/fetch-setting-notification-update/src/docker/configs.ts#L150) after this video was recorded.)
> [!WARNING]  
> This will not provide any notifications for our background system event listening, so if users are expecting the Resources view to change when external …
=> [v0.22.x] suggest disabling `http.fetchAdditionalSupport` for local Docker actions

CHANGELOG.md, package.json, src/commands/schemaUpload.ts, src/commands/schemas.ts, src/documentProviders/schema.ts, src/models/schema.test.ts, src/models/schema.ts, src/quickpicks/uris.ts
- Enables "Create Schema" nav action from Schemas view (doesn't require SR to be focused first since it's just opening an empty editor)
- Moves the "Upload" action to the Schemas view nav area once SR is focused, instead of showing up for any `.json`/`.avsc`/`.proto` editor
...also available in the Resources view for a specific SR:
- New command to bypass the schema subject quickpick and allow uploading **directly to a subject**
- New "URI quickpick" that loads open editors and/or offers an open file dialog for given language IDs / file filters
- Falling back to using the schema type quickpick from https://github.com/confluentinc/vscode/pull/738 if we can't determine the type from the chosen Uri
Other changes:
- Changes the "Evolve Schema" actions' icons from `plus` to `versions` to avoid …
=> refactor schema upload to start from Schemas view and prompt for editor/file Uri

CHANGELOG.md, package.json, src/constants.ts, src/graphql/direct.ts, src/models/environment.test.ts, src/models/environment.ts, src/viewProviders/resources.test.ts, src/viewProviders/resources.ts
- Removed the "Other" container item
- Moved the "Add New Connection" action from being inline on the "Other" item to a nav action on the Resources view
- Brought `DirectEnvironment`s up one level, to be siblings to the existing "Confluent Cloud"/"Local" container items
- Added `formConnectionType` to the `DirectEnvironment` model so it could change the icon depending on the connection type defined in the form
- CC/CP use the Confluent logo
- AK uses the new icon from https://github.com/confluentinc/vscode/pull/782
- everything else gets the 🔌 
- Added `formConnectionType` to the tooltips with some temporary helper text if we don't get any Kafka/SR results from the GraphQL query
- once we have [dynamic item updating](https://github.com/confluentinc/vscode/pull/780) integrated, we can pass …
=> UI/UX updates for direct connections in the Resources view

CHANGELOG.md, src/consume.ts, src/documentProviders/index.ts, src/documentProviders/message.ts, src/extension.ts
Closes #458.
Adds a text document provider to open per-message read-only JSON documents to the side of the message viewer that will also show up in `preview` mode if the user has editor previews enabled:
```shell
gulp clicktest
```
=> use read-only document provider for topic messages

CHANGELOG.md, src/commands/connections.ts, src/constants.ts, src/directConnectManager.ts, src/emitters.ts, src/graphql/direct.ts, src/graphql/environments.ts, src/graphql/local.ts, src/models/environment.test.ts, src/models/environment.ts, src/preferences/listener.ts, src/sidecar/connections.ts, src/storage/resourceManager.test.ts, src/storage/resourceManager.ts, src/viewProviders/resources.test.ts, src/viewProviders/resources.ts, tests/unit/testResources/environments.ts
Closes #774.
Until this PR, we've been doing "full tree" refreshes (for the Resources, Topics, and Schemas views) via `_onDidChangeTreeData.fire()`. This means that any time we had to update the state of one or more tree items, we would 
(re)load a lot of items that ultimately had no changes. This PR is the first time we're using `_onDidChangeTreeData.fire(item)` to update individual items within the tree data. 
For now, this is only happening for **direct connections** since they are the most affected by the async connection status checks done by the sidecar (see https://github.com/confluentinc/vscode/pull/728), and the current behavior on `main` effectively makes the entire Resources view unusable until the ["wait for connection to be …
=> dynamically update direct connection items in Resources view

src/docker/configs.test.ts, src/docker/configs.ts, src/docker/containers.ts, src/docker/eventListener.test.ts, src/docker/eventListener.ts, src/docker/images.test.ts, src/docker/images.ts, src/docker/networks.ts, src/extension.ts, src/storage/constants.ts
Closes #788.
Also migrates to the [ImageList](https://docs.docker.com/reference/api/engine/version/v1.43/#tag/Image/operation/ImageList) endpoint instead of image attempting to [inspect](https://docs.docker.com/reference/api/engine/version/v1.43/#tag/Image/operation/ImageInspect) a specific image. I was seeing some odd behavior where a locally-present image would throw 404s, even though we weren't filtering by `tag`:
-
```shell
gulp clicktest
```
=> fix: local resource Docker image pulling with registry credentials / proxy requirement

Gulpfile.js, package-lock.json, package.json, src/authn/ccloudPolling.test.ts, src/authn/ccloudProvider.test.ts, src/authz/schemaRegistry.test.ts, src/commands/connections.test.ts, src/context/extension.ts, src/context/observability.test.ts, src/directConnectManager.test.ts, src/docker/eventListener.test.ts, src/docker/workflows/confluent-local.test.ts, src/docker/workflows/cp-schema-registry.test.ts, src/extension.test.ts, src/preferences/listener.test.ts, src/sidecar/connections.test.ts, src/sidecar/middlewares.test.ts, src/storage/resourceManager.test.ts, src/viewProviders/resources.test.ts, tests/unit/testUtils.ts
The issue was uncovered during debugging of the test in https://github.com/confluentinc/vscode/pull/811. At different times we had different ideas about what has to be built for the tests to run. We have `build` task to build extension bundle (including production), and at some point the task started producing essentially a whole bundle as a single JS file. We have `testBuild` to build test scripts and their dependencies to run isolated tests. Those didn't have the same requirements as `build` task. At some point our tests started requiring the extension context, thus extension suppose to be activated before running tests. This means the bundle should be built before tests start, regardless of a test scenario dependencies. So we added `build` task to the `test` pipeline. Since `build` and …
=> Make test job build all files to run the extension

src/commands/topics.ts, src/consume.ts
Closes #821. Also re-adds the "success" info notification accidentally removed in https://github.com/confluentinc/vscode/pull/823, but with a new "View Message in Topic Messages" button that will filter to the message's timestamp and use its `key` as a text filter to open a new message viewer tab.
https://github.com/user-attachments/assets/dadb19bf-bf67-4d3d-9e7f-ab5d381752ba
```shell
gulp clicktest
```
=> add "View Message in Topic Messages" button after producing

src/directConnectManager.ts, src/sidecar/connections.ts
This fixes a race condition we hit when trying to refresh the Topics/Schemas views during a direct connection update. Previously, we wouldn't wait for the connection to be in a non-`ATTEMPTING` connected state, so we would erroneously attempt making a list topics/schemas type request before the sidecar was able to repopulate its cluster cache with the associated cluster(s).
Now we wait until the connection is not `ATTEMPTING` before firing this event, which ensures the sidecar has transitioned the connected state to either `SUCCESS` or `FAILED`, and we can then safely re-request the topic/schemas list (which will either list any available topics/schemas, or show the error if communication to the associated resource is lost). …
=> fix: don't refresh Topics/Schemas views after direct connection change until in a usable connected state

src/sidecar/connections.test.ts, src/sidecar/connections.ts
Closes #810.
If we hit a timeout waiting for a `DIRECT` connection to move past an `ATTEMPTING` connected state, we need to at least fire the `connectionUsable` event so the connection/"environment" tree item no longer looks like it's loading.
```shell
gulp clicktest
```
=> fix: fire "usable" event if we time out waiting for direct connection to be usable

CHANGELOG.md, src/storage/constants.ts, src/storage/migrationManager.test.ts, src/storage/migrationManager.ts, src/storage/migrations/base.ts, src/storage/migrations/registry.ts, src/storage/migrations/utils.ts, src/storage/migrations/v2.test.ts, src/storage/migrations/v2.ts
Closes #818.
Adds a `SecretStorage` migration to account for SSL configs being required for different kinds of `DIRECT` connections -- "Confluent Cloud" connections should have SSL enabled by default (see https://github.com/confluentinc/vscode/pull/822), and anything else should be set to `ssl.enabled = false` by default.
This PR also sets up some basic patterns for how we may want to handle future migrations across the global/workspace state(s) and secret storage, so future migration branches should be smaller / more focused.
```shell
gulp clicktest
```
=> add SecretStorage migration for direct connections' SSL config(s)

CHANGELOG.md, package.json, src/context/values.ts, src/extension.ts, src/preferences/constants.ts, src/preferences/listener.test.ts, src/preferences/listener.ts, src/viewProviders/resources.test.ts, src/viewProviders/resources.ts
Removes all references/watchers for the `confluent.preview.enableDirectConnections` preview setting, as well as the `confluent.directConnectionsEnabled` context value.
```shell
gulp clicktest
```
=> remove direct connection preview setting and enable by default

src/context/values.test.ts, src/sidecar/websocketManager.ts, src/storage/directResourceLoader.ts
- Two small things:
1. Fix websocket docstring, pointed out by @alexeyraspopov in the [websocket PR ](https://github.com/confluentinc/vscode/pull/754)but queued for followup.
2. Fix two 'gulp lint' identified issues:
```
KCX6P9D7XG:vscode jlrobins$ gulp lint
[13:38:11] Using gulpfile ~/git/vscode/gulpfile.js
[13:38:11] Starting 'lint'...
/Users/jlrobins/git/vscode/src/context/values.test.ts
8:7  warning  'executeCommandStub' is assigned a value but never used  @typescript-eslint/no-unused-vars
/Users/jlrobins/git/vscode/src/storage/directResourceLoader.ts
18:7  warning  'logger' is assigned a value but never used  @typescript-eslint/no-unused-vars
```
=> Small cleanups

src/webview/direct-connect-form.html
- Add a little check to these fields so users can submit _only_ SR for CCloud if necessary
=> bug fix: api fields should only be required if bootstrap servers exist

src/extension.ts
Closes #693, closes #796 (by filtering out `captureException` which we only ever see from `node_modules/@sentry/*` errors), closes #866.
=> MINOR: add more filters to Sentry

CHANGELOG.md, package.json, src/context/values.test.ts, src/context/values.ts, src/viewProviders/resources.test.ts, src/viewProviders/resources.ts
Closes #852.
We now have `confluent.directKafkaClusterAvailable` and `confluent.directSchemaRegistryAvailable` context values that will update when the direct "environments" update and load their respective resources:
https://github.com/user-attachments/assets/5b86d274-1fcb-4079-babb-6c688810d2c6
This ended up being more involved than initially expected since we handle per-"environment" updates and don't have as convenient of a place to check whether direct connections have Kafka clusters and/or Schema Registries like we do after loading all CCloud or local resources.
```shell
gulp clicktest
```
=> [v0.23.x] fix: update Topics/Schemas empty state when direct connections' resources change

package.json
- Adds links for connecting directly to Kafka (for the Topics view) and Schema Registry (for the Schemas view) which will just open the direct connection form.
- Updates the `when` clauses for selecting Kafka/SR to only be available when we have at least one available (whether signed into CCloud, or a local instance is running, or a direct connected resource is available)
- Changes the Schemas view to use `No connections available.` above the CCloud button to match the Topics view
| <img width="372" alt="image" src="https://github.com/user-attachments/assets/f4072e3f-153b-4657-88a7-54af0a9de72d" /> | <img width="369" alt="image" src="https://github.com/user-attachments/assets/8cf0cc5d-05a8-4dce-91f2-04c7224e61e2" /> |  …
=> MINOR: clean up Topics/Schemas empty states and add links for direct connections

src/errors.ts, src/preferences/updates.ts
Closes #619.
Also fixes the `errorType` since the error names were getting minified.
Sample error data:
=> use `logResponseError` for response errors from preferences API

src/commands/kafkaClusters.ts
Closes #771. 
No idea how we could even get here; I've only seen the above issue's behavior when clicking a view's nav/context actions when something else was highlighted.
Still, good practice to guard against unintended types coming through when we expect a command function argument.
=> guard against non-KafkaTopics being passed through "delete topic" command logic

.github/ISSUE_TEMPLATE/bug_report.yml
Closes #628.
We offer commands in the extension to download the full log file(s) for the extension and the sidecar, and we should hint at that when a user is filing an issue for this repo.
=> hint to extension Support commands for logs in GH issue template [ci skip]

.vscodeignore, Gulpfile.js
Currently we build source map for extension code in both dev and production modes which adds extra 6MB+ to the bundle size (at least uncompressed). We don't need to ship those source maps since we upload them separately to Sentry.
=> Avoid building source maps in production mode

Gulpfile.js
Mostly affects `testBuild`:
Before:
After:
=> remove "The 'this' keyword is equivalent to 'undefined' at the top level of an ES module" warnings for `node_modules`

src/graphql/direct.ts, src/models/environment.test.ts, src/models/environment.ts, tests/unit/testResources/environments.ts
Fixes some behavior we previously saw where we would show a normal icon in the Resources view for a connection that could only connect to either Kafka _**or**_ Schema Registry when both were configured. With this change, the (previously `warning`) `error` icon will show when a direct connection is configured but we didn't get the expected resource back from the GraphQL query.
When Kafka and SR are unreachable:
When only Kafka is unreachable:
When only Schema Registry is unreachable:
Ideally we'll also provide _why_ we couldn't connect to one or more of those resources within the tooltip, but that's not quite ready yet.
```shell
gulp clicktest
```
=> set `kafkaConfigured` and `schemaRegistryConfigured` to inform direct connection icon+tooltip

src/scaffold.ts
Quick follow-up to https://github.com/confluentinc/vscode/pull/914
=> MINOR: skip listing collections and just try to list all `vscode` templates

CONTRIBUTING.md
New section to our contributing guide: https://github.com/confluentinc/vscode/blob/djs/document-client-generation/CONTRIBUTING.md#updating-openapi-clients
Mainly to document how our client code generation works, how we update it, and how we add new specs and client code.
=> docs: add OpenAPI client section to CONTRIBUTING.md [ci skip]

src/directConnect.ts, src/directConnectManager.test.ts, src/directConnectManager.ts, src/webview/direct-connect-form.spec.ts, src/webview/direct-connect-form.ts
- Backfills unit tests for `mergeSecrets` 
- Updates some checks so that we don't have to `@ts-expect-error` all over the place as much
- Adds basic functional (Playwright) tests to confirm form renders, submits in happy case
- Still a few `@ts-expect-error` comments in the form `ts` - it's proving hard to check these types include or are instances of the credential objects in this file where they are are actually `inertial` Signals under the hood. 
```shell
gulp clicktest
```
=> More tests, cleanup for direct connect form

CHANGELOG.md, package.json, src/commands/schemaUpload.ts, src/commands/topics.test.ts, src/commands/topics.ts, src/quickpicks/uris.ts
Closes #763, closes #764, closes #910.
**If any editors or read-only documents are open in the current workspace**, instead of showing the open-file dialog for producing a message to a topic, we're now showing the same "URI quickpick" that we use for schema upload actions, which means any `.json` files/documents or `JSON`-language editors can be used to produce a message:
So a user can now effectively re-produce a message that was opened as a message viewer preview (https://github.com/confluentinc/vscode/pull/799), or one they were working on in a new editor (but didn't save to a file on disk).
Also closes #910 by adding some placeholder `type: "JSON"` values where we'll need to look up other schema-related information in follow-up PRs while simultaneously making sure we float any nested …
=> feat: allow producing messages to a Kafka topic from an editor or message viewer document

src/commands/connections.ts, src/commands/docker.test.ts, src/commands/docker.ts, src/commands/index.ts, src/docker/configs.test.ts, src/docker/configs.ts, src/docker/workflows/base.ts, src/docker/workflows/confluent-local.test.ts, src/docker/workflows/confluent-local.ts, src/docker/workflows/cp-schema-registry.test.ts, src/docker/workflows/cp-schema-registry.ts, src/errors.test.ts, src/errors.ts, src/graphql/direct.ts, src/graphql/environments.ts, src/graphql/local.ts, src/graphql/organizations.ts, src/sidecar/sidecarManager.ts, src/viewProviders/resources.ts
We previously had a lot of `window.showErrorMessage(msg, btn1, btn2).then(...)` logic that was repeating the same "Open Logs" handling (occasionally with "File Issue"). This PR consolidates it to a single convenience function with the ability for callers to provide a map of `buttonLabel: callbackFn()` for any custom handling.
Example of the "custom buttons + callbacks" implementation for `showErrorNotificationWithButtons()`:
https://github.com/confluentinc/vscode/blob/638843c7dc08420d942e289e5ddfa3cd2c2fb969/src/sidecar/sidecarManager.ts#L504-L512
- Closes #794 and aligns the general handling of GraphQL queries when awaiting a response from the sidecar.
- Renames the previous `Show Logs` button label (for local resource actions) to `Open Logs` for consistency
- Closes #696 since we don't …
=> cleanup: add `showErrorNotificationWithButtons()` convenience function for error notifications

src/extension.ts
The sidecar isn't able to populate the `uri` for Kafka clusters from direct connections, so we need to prevent that action altogether.
See https://github.com/confluentinc/ide-sidecar/issues/300#issuecomment-2596844086
(Direct connections to Schema Registry instances can still return a `uri` value though, so it's fine to leave in.)
=> MINOR: prevent direct Kafka cluster items from showing the "Copy URI" action

CHANGELOG.md, package.json, src/authn/ccloudPolling.ts, src/authn/ccloudProvider.ts, src/commands/connections.ts, src/quickpicks/kafkaClusters.ts, src/quickpicks/schemaRegistries.ts
- Changes the CCloud sign-in action's icon to `sign-in` since `plus` was being used elsewhere in other contexts and didn't really fit anymore.
- Adds a dedicated `sign-out` action (after a user signs in to CCloud) for easier discoverability
- Replaces "log* in/out" mentions with equivalent "sign* in/out" for consistency
https://github.com/user-attachments/assets/7becb84b-5720-4c88-9d9d-4f8905c665ba
*_Changed sign-out to use an info modal in https://github.com/confluentinc/vscode/pull/935/commits/9d422c909f01179782927a0ba0de58736de5be30_
```shell
gulp clicktest
```
=> MINOR: add "Sign out" action to CCloud item in Resources view + update icons

CHANGELOG.md, src/commands/support.ts
Closes #899.
```shell
gulp clicktest
```
=> MINOR: normalize log file URIs before `fs.read`

CHANGELOG.md, src/directConnectManager.test.ts, src/sidecar/connections/watcher.test.ts, src/sidecar/connections/watcher.ts, src/sidecar/connections/watcherUtils.test.ts, src/sidecar/connections/watcherUtils.ts, src/storage/resourceManager.test.ts, src/storage/resourceManager.ts, tests/unit/testResources/connection.ts
Closes https://github.com/confluentinc/vscode/issues/940.
Using websockets to receive connection events, we don't go through the same middleware/parsing layers as we do for the sidecar REST (HTTP) API, so in order to use the "real"/typed objects, we need to convert them (and their nested structures) to the expected types.
The main fix is in https://github.com/confluentinc/vscode/blob/fb162e544273fb9ec4bd7b828e0221b149356fb2/src/sidecar/connections/watcher.ts#L306-L311
Which ultimately calls into https://github.com/confluentinc/vscode/blob/e900d8a3f114c05d6385cb0e8b3668c59117d01d/src/clients/sidecar/models/Authentication.ts#L86-L89
The fact that we were dealing with a `requires_authentication_at` string instead of `Date` was silently throwing an error here: …
=> fix: make ConnectionStateWatcher.handleConnectionUpdateEvent use parsed `Connection` types

src/sidecar/connections/watcher.test.ts, src/sidecar/connections/watcher.ts, src/sidecar/websocketManager.test.ts, src/sidecar/websocketManager.ts, src/ws/messageTypes.ts, tests/unit/testResources/websocketMessages.ts
- Push the good fix from https://github.com/confluentinc/vscode/pull/955, apply higher-level decoding beyond mere de-JSON-ing, down a few layers to happen for all websocket message types right at websocket message reception time, so that the message object delivered to any registered callbacks will have been fully deserialized and decoded already. The issue was that `JSON.parse()` isn't sufficient for many things, such as the case of timestamps-encoded-as-strings.
- Do so through making a mapping of message type -> body decoder within `ws/messageTypes.ts`, requiring every message type to declare a (possibly null-valued) entry. At this time, we only need an entry for `MessageType.CONNECTION_EVENT` message bodies, decoding the dates-as-strings up to date instances. But if/when we have new …
=> Lowest level enforced websocket message higher-level field decoding

src/scaffold.ts, src/webview/scaffold-form.html, src/webview/scaffold-form.spec.ts, src/webview/scaffold-form.ts, src/webview/uikit/uikit.css
We switched to use the new Scaffold Service to generate projects, which will check all fields and return an error message if they are not valid. With this PR we avoid the round trip by attempting to validate client-side first, and show any error response from the API in the form for users. 
- Closes #907 
- If the input value is non-empty & it has a `pattern`, we validate against the pattern on blur and show a red border if invalid. 
- Form submit is disabled if invalid fields are present.
- Extends the Submit function to return a `PostMessage` type instead of null, similar to Direct Connect form.
- If we still get an error response on submit, the form shows a message by the Save button (per recent design mocks for our forms. See additional details below.) 
| Other errors on submit show …
=> Updates for scaffold service: client-side form validation

src/webview/scaffold-form.html, src/webview/scaffold-form.spec.ts
- **Quick Fix !** Removed the `pattern` attr in the form so that it doesn't incorrectly invalidate fields when empty. Validation against the pattern happens in `scaffold-form.ts` on input blur, so we are not relying on the HTML form validation for RegEx pattern matches anyways and can safely do away with it. 
- This is a 'side effect' of our template engine that can be addressed separately if we want to add this back. The HTML attr is incorrectly marking empty fields invalid since once it goes through the bindings [here](https://github.com/confluentinc/vscode/blob/47a98e15ce99377ed9413d9b3855de67a813d98e/src/webview/bindings/bindings.ts#L154), it was **setting the attribute as empty if it doesn't have a pattern.** This doesn't work for this specific attribute which makes some assumptions …
=> bug fix - don't use html validation

src/webview/bindings/bindings.spec.ts, src/webview/bindings/bindings.ts
Addressing the issue raised in https://github.com/confluentinc/vscode/pull/967. When `data-attr-*` binding receives `null` or `undefined`, it is going to remove attribute from a node. This should make elements like `<input />` update their behavior accordingly.
=> Bindings: remove attribute from node when null or undefined is given

.vscodeignore, Gulpfile.js
#901 adjusted sourcemap behavior to only include them when we weren't doing a production build (to reduce .vsix size), but the Sentry rollup plugin requires it to be set to `true` https://docs.sentry.io/platforms/javascript/guides/wasm/sourcemaps/uploading/rollup/
This PR sets it back to `true` but uses the `.vscodeignore` file to ensure those `*.js.map` files are excluded in the `vsce package` command (via `gulp pack`) and the .vsix still remains smaller
=> [v0.24.x] always send `sourcemaps`

src/authn/ccloudProvider.ts, src/commands/index.ts, src/commands/topics.ts, src/docker/configs.ts, src/errors.test.ts, src/errors.ts, src/graphql/direct.ts, src/graphql/environments.ts, src/graphql/local.ts, src/graphql/organizations.ts, src/preferences/updates.ts, src/scaffold.ts, src/sidecar/connections/index.ts, src/sidecar/connections/watcher.test.ts, src/sidecar/websocketManager.ts, src/storage/ccloudResourceLoader.ts, src/storage/resourceLoader.ts
Our generated client code (`src/clients/*`) will throw `FetchError`s when it encounters any kind of error that doesn't fall into the `ResponseError` category:
https://github.com/confluentinc/vscode/blob/b9f9f8213c2c529d73e4fc7ec997e3eaf5c0c59e/src/clients/schemaRegistryRest/runtime.ts#L231-L236
These [`FetchError`s include a `cause`*](https://github.com/confluentinc/vscode/blob/b9f9f8213c2c529d73e4fc7ec997e3eaf5c0c59e/src/clients/schemaRegistryRest/runtime.ts#L286-L294) which is a nested `Error` type, but we weren't generally handling these well**, and the main reason for this PR is the fact that some users are getting these `FetchError`s when attempting to list topics (but the request to get schemas is causing the issue).
*`cause` isn't strictly used with `FetchError`s though. We've seen …
=> [v0.24.x] add handling for `FetchError`s

CHANGELOG.md, src/sidecar/sidecarManager.ts
- To attempt to gain insight why we have lingering sidecar start issues in Sentry:
- Bump up startup and handshake loops from 10 to 20 attempts (theory: fork/spawning the Graalvm native executable is pain for some?) (there will be 500ms pauses between iterations).
- Log more intermediate unexpected errors into Sentry via `logErrror(..., true)` instead of just `logger.error()`, because it seems that the people suffering this are not making more formal complaints and submitting their logs.
- Improve some log message phrasing.
- Make `startSidecar()` definitely end with `reject()` if the loop over `doHandshake()` didn't succeed.
```shell
gulp clicktest
```
=> Try to harden sidecar starting

src/quickpicks/topics.ts
- Simple small branch.
- topicQuickPick() is only used by the command invocation to start up message browser from command palate.
- No need to call `loader.getSchemas()` (or new `loader.getSubjects()`) at all , because the equivalent topic -> subject matching has already been happening within `loader.getTopicsForCluster()` for some time now. Just need to realize to pivot off of the `KafkaTopic` model's `hasSchema` property. 
- Closes https://github.com/confluentinc/vscode/issues/1006
```shell
gulp clicktest
```
=> Wean topicQuickPick() off of getSchemasForEnvironmentId().

src/webview/bindings/README.md, src/webview/bindings/bindings.ts, src/webview/bindings/custom-elements.spec.ts
This PR implements a bunch of integration specs that can serve as an example of [using custom elements](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements) with our bindings library. This suppose to be the path of least resistance to get into component-based UI development wherever the complexity requires, still without switching to full fledged UI framework. Keeping things lightweight and using the platform as far as we can feasibly do.
A framework's component (React, Vue) is not the same as Web component. A framework component mainly about separating knowledge/structure based on application domain. Web component is a set of different technologies that allow building reusable **custom elements**. Custom elements by themselves is also another particular …
=> Provide examples of using web components with bindings

src/telemetry/telemetryLogger.test.ts, src/telemetry/telemetryLogger.ts
- Refactor `telemetryLogger.sendEventData()` to do the preparation of the `properties` sent up in the track() call in an new external function, `preparePropertiesForTrack().`
- Have `preparePropertiesForTrack()` include the current vscode.env.uriScheme ("vscode", "vscode-insiders", etc.) as `productName`.
- Write tests.
- Closes #1008 
```shell
gulp clicktest
```
=> Send the vscode uriScheme to segment as "productName"

CHANGELOG.md, README.md, package.json, src/commands/extra.ts, src/context/values.ts, src/emitters.ts, src/models/main.ts, src/models/schema.ts, src/viewProviders/schemas.test.ts, src/viewProviders/schemas.ts
Continuation of #996 and #1010. Closes #1003.
This is a much smaller search PR than the previous two, mainly because we can only realistically support searching by **subject** rather than any visible data associated with the schema items themselves.
https://github.com/user-attachments/assets/c5a559df-41a7-4aec-a871-8fb8ad3ab627
Unfortunately, because we're still using `ContainerTreeItem<Schema>`, that means that `Schema`s had to be "searchable" -- (since ContainerTreeItem children types must also [implement `ISearchable`](https://github.com/confluentinc/vscode/blob/main/src/models/main.ts#L14)) -- despite not functionally being searchable.
Once https://github.com/confluentinc/vscode/issues/1021 is done, this should be less confusing.
Please check if your PR fulfills the following (if …
=> feat: add search functionality to Schemas view

src/telemetry/telemetryLogger.test.ts, src/telemetry/telemetryLogger.ts
- Closes https://github.com/confluentinc/vscode/issues/991
```shell
gulp clicktest
```
=> Include vscode.version as "productVersion" in telemetry events.

Gulpfile.js
Full extension ID needs to match our publisher + extension name:
https://github.com/confluentinc/vscode/blob/a193db13417024a7a6b7f3dd3c70d11182b65fa7/package.json#L9
=> MINOR: fix `gulp clicktest` publisher ID

.semaphore/semaphore.yml, Gulpfile.js
Closes #209 
Should be a decent smoketest to get us ahead of breaking changes. Tested by pinning `1.96.4` to the normal test run, with Insiders build `1.98.0`:
Updated from the above screenshot: this is run as its own block, and will only run on PRs to `main` since we don't want to block releases or release patches if there's an issue with testing on Insiders.
| VS Code | VS Code Insiders |
| ![image](https://github.com/user-attachments/assets/e116aba3-f9c0-4bfb-a0ff-c1f115b40477) | ![image](https://github.com/user-attachments/assets/51cbd05b-1a1b-41bc-9a4e-793bb833c731) |
=> chore(CI): build & test with VS Code Insiders

CHANGELOG.md, src/consume.ts
Closes #931.
Continuation of #799, but this time for the multi-message view:
Content is now passed to the `MessageDocumentProvider` in the same format it was shown as a workspace doc, but with an updated title. All content is now read-only, and can be used for the (still in preview) produce-message flow:
Also supports VS Code document `preview` mode (when enabled in user settings) and will not show up as "dirty" / prompt for saving when closing the tab.
```shell
gulp clicktest
```
=> use read-only document provider for "Open consumed messages as JSON"

src/sidecar/connections/index.test.ts, src/sidecar/connections/index.ts, src/sidecar/connections/local.ts
Ensures we pass the correctly typed `LocalConfig` through our update-local-connection flow since our client code uses `schema_registry_uri` but the sidecar spec shows `schema-registry-uri`, so we have to use this:
https://github.com/confluentinc/vscode/blob/a35be57b123b27ae3d37686d2dd17418bd6ce182/src/clients/sidecar/models/LocalConfig.ts#L55-L66
But the proper fix is to just make sure that the `PATCH` request method uses `ConnectionSpecToJSON` all the time so we don't have to revisit this for some other connection type / field.
```shell
gulp clicktest
```
=> fix: use `ConnectionSpecToJSON` to ensure we use `schema-registry-uri` for patching connections

.semaphore/multi-arch-packaging.yml, .semaphore/semaphore.yml, .semaphore/third-party-notices.yml
pulls out 3P notices to its own block 
also updates ubuntu version
-
```shell
gulp clicktest
```
=> chore: move third party notices generation to Semaphore promotion

src/viewProviders/resources.test.ts, src/viewProviders/resources.ts
Avoids the edge case where we may have an childless `LocalEnvironment` that would incorrectly set `confluent.localKafkaClusterAvailable`.
=> MINOR: use count of local Kafka clusters to set context value

.semaphore/multi-arch-packaging.yml
Closes #1047 
Works fine with manual promotion
=> chore(CI): Migrate to Ubuntu 24.04 from soon-to-be EoL Ubuntu 20.04

src/sidecar/connections/local.ts
The sidecar has always supported using `schema_registry.uri` to set the SR URI for local connections. Use it.
-
```shell
gulp clicktest
```
=> Use `schema_registry` instead of `local_config` for SR URI

package.json, src/commands/diffs.test.ts, src/commands/diffs.ts
Same situation as https://github.com/confluentinc/vscode/pull/1032 -- VS Code `Uri`s aren't natively serializable, so we need to stringify them and parse them when performing the actual "compare with selected" action.
```shell
gulp clicktest
```
=> fix schema diffing

src/webview/scaffold-form.html
- Just a little fix @Cerchie and I noticed when testing new templates (UDF has no options for example) - the message about no options should appear under the "Options" heading, not above it !
-
```shell
gulp clicktest
```
=> minor: make sure empty message appears under options header

src/models/kafkaCluster.test.ts, src/models/kafkaCluster.ts
Tests over branches of `createKafkaClusterTooltip()` not already exercised.
=> Additional model tests as indicated by coverage report.

src/loaders/resourceLoader.test.ts, src/loaders/resourceLoader.ts
- Fix badness when an environment doesn't have a schema registry. Oops, my bad.
- Closes #1082 
- Can be clicktested through starting up Docker, then only starting up local kafka -- no schema registry at all.
```shell
gulp clicktest
```
=> Gracefully handle case when environment has no schema registry.

CHANGELOG.md, src/models/schema.test.ts, src/models/schema.ts, src/models/schemaRegistry.ts
- Updated the URL templates for viewing schemas and schema registries in CCloud (now under "stream-governance/schema-registry/data-contracts")
- The old URLs worked, but who knows for how long?
=> Update ccloud schema registry and schema URLs

CHANGELOG.md, src/models/schema.test.ts, src/models/schema.ts, src/models/schemaRegistry.ts
- Bring https://github.com/confluentinc/vscode/pull/1085 forward into main.
=> Pull respelling of schema registry ccloud urls into main (PR #1085)

src/authn/ccloudProvider.ts, src/commands/docker.ts, src/directConnectManager.ts, src/docker/images.ts, src/docker/workflows/base.ts, src/docker/workflows/confluent-local.ts, src/docker/workflows/cp-schema-registry.ts, src/extension.ts, src/scaffold.ts, src/telemetry/events.ts, src/telemetry/telemetry.test.ts, src/telemetry/telemetry.ts
**No user-facing changes here.**
This PR consolidates a lot of the old telemetry events ([`src/telemetry/events.ts`](https://github.com/confluentinc/vscode/pull/1028/files#diff-83886f8a82ab31e0a5db17ae6db93a72f46caee5684835f80cd880805d25abbe)) and starts using more `status` fields to indicate different stages for a particular event.
| `ActivatedWithSession` | `ExtensionActivation` with `status: "identify"` |
| `DockerContainerCreated` | `LocalDockerAction` with `status: "container created"` |
| `DockerContainerStarted` | `LocalDockerAction` with `status: "container started"` |
| `DockerContainerStopped` | `LocalDockerAction` with `status: "container stopped"` |
| `DockerImagePulled` | `LocalDockerAction` with `status: "image pulled"` |
| …
=> cleanup(telemetry): consolidate user events

src/commands/topics.ts, src/telemetry/events.ts
Telemetry updates around the produce-message flow. Only includes the URI scheme chosen (`file`, `untitled`, or the message-viewer URI) along with counts of original message(s) to be sent and resulting success/failure counts. No message or topic content is being sent.
Closes #896.
Associated PRs:
- https://github.com/confluentinc/vscode/pull/1028
- https://github.com/confluentinc/vscode/pull/1042 👈 
- https://github.com/confluentinc/vscode/pull/1044
=> chore(telemetry): add `MessageProduceAction` events

package-lock.json, package.json
Closes https://github.com/confluentinc/vscode/security/dependabot/10 due to an updated version of `cross-spawn`.
https://github.com/eslint/eslint/releases/tag/v9.17.0
Also bumps `typescript-eslint` due to the following errors when only bumping the `eslint` version:
```
TypeError: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
Occurred while linting .../vscode/src/authn/ccloudProvider.test.ts
at Object.create (.../vscode/node_modules/eslint/lib/rules/no-unused-expressions.js:75:13)
at create (.../vscode/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unused-expressions.js:28:32)
at Object.create (.../vscode/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:32:20)
at …
```
=> security: bump `eslint` version to update `cross-spawn`

Gulpfile.js, package-lock.json
Trying to fix creating a not-dev Sentry release by manually generating .vsix files within CI.
Adds some more logging as well so we can more easily determine what the release value will be:
=> chore(CI): try to split CI prod builds from CI non-prod builds

src/webview/direct-connect-form.html, src/webview/direct-connect-form.spec.ts, src/webview/direct-connect-form.ts, src/webview/ssl-config-inputs.ts
A few bug fixes and clean up items on the SSL Config form fields
- make sure these values are stored locally so they are in the form even after collapse/expand, tab away
- use the right binding for text and select input values - it's `data-value` not `data-attr-value` to ensure signals update
- rearrange some fields (key store first) and add "tls" to wording so it's accurate
- minor comment and clean up things (delete unused commented lines, etc)
- ⚠️ Not done: adding tooltip info/descriptions to these fields, and updating the layout of path button+input per suggestions. I will follow up when higher-priority things are done. 
Update UI: 
```shell
gulp clicktest
```
=> SSL form follow-up and bug fixes

README.md
State that the Message Viewer doesn't support consuming records that were compressed with `snappy` except for Confluent Cloud connections.
-
```shell
gulp clicktest
```
=> docs: Add missing support for snappy compression to known limitations

CHANGELOG.md, src/sidecar/connections/ccloud.test.ts, src/sidecar/connections/ccloud.ts, src/viewProviders/schemas.test.ts, src/viewProviders/schemas.ts, src/viewProviders/topics.test.ts, src/viewProviders/topics.ts
- Fix CCloud logout side effects on view controllers :
- SHOULD clear topics or schema registry view if currently viewing CCloud-based resources.
- SHOULD NOT clear topics or schema registry view if NOT currently viewing CCloud-based resources.
While in here:
- If user clicks on the same SR they were already focused on, short circuit do nothing. Do not reload the SR's subjects. That effect is reserved for the 'reload' icon.
- Closes #1137.
```shell
gulp clicktest
```
=> Fix signing out of ccloud with ccloud sr focused doesnt wipe the schemas view

src/webview/direct-connect-form.spec.ts
- Let's skip this new test, which I noticed was flaky from the beginning, so it's not creating failures on `main` 
- I will fix it in my next PR - OAuth work is rearranging these files anyways. 
- It was merged yesterday for SCRAM but there is a flake.
- I tested the related user workflows - submitting SCRAM auth type with connections - manually and with other unit tests. 
- This is unreleased, so no concern about users encountering related bugs at this time. 
=> chore: skip flaky functional spec (temporary fix)

src/models/schema.test.ts, src/models/schema.ts
Closes #1130.
There's some weird behavior on `main` that updates a Subject on expansion that converts the "other" icon to the "value" icon (for subjects using the `TopicRecordNameStrategy`/`RecordNameStrategy`) once schemas are loaded that this PR fixes:
| <img width="363" alt="image" src="https://github.com/user-attachments/assets/1cf7f075-8b9b-42b0-b979-cc51b7dd278f" /> | <img width="399" alt="image" src="https://github.com/user-attachments/assets/47e3beed-27b0-4a1f-925e-796f6a1c17d4" /> | 
Subjects following the `TopicNameStrategy` that end in `-key`/`-value` still show the correct icons.
```shell
gulp clicktest
```
=> fix: don't use the "value" subject icon for subjects that don't end in `-value`

src/commands/schemaUpload.test.ts, src/commands/schemaUpload.ts
Reduces the quickpick/input flow during schema upload and new-subject-creation to validate the new subject value and show a warning, rather than show a follow-on confirmation input.
| | |
| Before | <img width="717" alt="image" src="https://github.com/user-attachments/assets/a4c840a1-61cb-4b92-8208-5de6d1456053" /> <img width="713" alt="image" src="https://github.com/user-attachments/assets/7f176908-8e2f-4ac1-acbb-c247b0e87c81" /> |
| After | <img width="717" alt="image" src="https://github.com/user-attachments/assets/0cab2e69-7827-40b8-9bcd-31ae2b896527" /> | 
```shell
gulp clicktest
```
=> use input validation warning instead of secondary input for new schema subject creation

CHANGELOG.md, package.json, src/context/values.ts, src/extension.ts, src/preferences/constants.ts, src/preferences/listener.test.ts, src/preferences/listener.ts
Closes #1157.
```shell
gulp clicktest
```
=> remove message-produce preview setting and enable functionality by default

src/emitters.ts, src/sidecar/connections/watcher.ts, src/sidecar/connections/watcherUtils.test.ts, src/sidecar/connections/watcherUtils.ts, src/viewProviders/schemas.test.ts, src/viewProviders/schemas.ts, src/viewProviders/topics.test.ts, src/viewProviders/topics.ts, tests/unit/testUtils.ts
- Event emitter `environmentChanged` was born just carrying the env id which was changed, but information about what kind of change, specifically if the environment has just been _deleted_ was being discarded, leading to small UI issues including that if the topics or schemas views were set to a cluster within the now gone environment, the view description line would not be cleared properly.
- Fix through:
- Extending the type carried by the event to be a pair: the env id, and boolean `wasDeleted`.
- Having the event listeners pivot off of if `wasDeleted` was set, and opt to call `this.reset()` accordingly.
- Now with thorough test coverage over the two view controller event listeners.
- Closes #1159 
```shell
gulp clicktest …
```
=> Make environmentChanged events more informative

src/sidecar/connections/watcherUtils.test.ts, src/viewProviders/schemas.test.ts, src/viewProviders/topics.test.ts, tests/unit/testUtils.ts
Automerge fired too soon.
* Address a couple more things from comments on https://github.com/confluentinc/vscode/pull/1163
* Remove redundant spelling of tests. They were born in the wrong describe() block, then copy/paste into new block.
=> Dregs from comments from https://github.com/confluentinc/vscode/pull/1163

.semaphore/semaphore.yml
Same as the sidecar:
https://github.com/confluentinc/ide-sidecar/blob/0eb5a1cbe1562ffbc3e7ef90e8ce70674a54f8cd/.semaphore/semaphore.yml#L70C1-L75C144
Should hopefully make it easier to compare results between VS Code (stable) and VS Code Insiders tests if there are any failures
https://docs.semaphoreci.com/using-semaphore/tests/test-reports
=> chore(CI): use `test-results gen-pipeline-report` for unified test report in Semaphore

src/testing.ts
Follow-up to https://github.com/confluentinc/vscode/pull/1165 since the test report was merging the test results between stable and insiders under one `Mocha Tests` result.
This splits the test results into two suites based on how we set up the environment variables in the [pipeline](https://github.com/confluentinc/vscode/blob/8af2dadd0cc7b67c34e3cc34adffee1dac13ce5f/.semaphore/semaphore.yml#L40-L68):
- "VS Code (stable) Extension Tests: Mocha"
- "VS Code (insiders) Extension Tests: Mocha"
https://www.npmjs.com/package/mocha-junit-reporter#:~:text=to%20%27Root%20Suite%27)-,testsuitesTitle,-Mocha%20Tests
=> chore(CI): set `testsuitesTitle`

src/quickpicks/schemas.ts
updating helper text so devs know they can producer w/o schema
=> update help text

CHANGELOG.md, package-lock.json, package.json, src/commands/debugtools.ts, src/commands/support.test.ts, src/commands/support.ts, src/commands/utils/zipFiles.ts, src/docker/configs.ts, src/extension.ts, src/logging.test.ts, src/logging.ts, src/preferences/listener.ts, src/sidecar/constants.ts, src/sidecar/sidecarManager.test.ts, src/sidecar/sidecarManager.ts
Closes #1100.
- Renames the global const `outputChannel` to `OUTPUT_CHANNEL` for consistency with `SIDECAR_OUTPUT_CHANNEL` (#1058).
- Adds the [`rotating-file-stream`](https://www.npmjs.com/package/rotating-file-stream) dependency so we can rotate log files based on max interval and size.
> [!TIP]
> To click-test this branch, update the following from `10M` to `10K`. Signing in and out of CCloud (multiple times) will help push the logs past the 10K file limit faster to see the rotation in action. https://github.com/confluentinc/vscode/blob/a2ae3b19b30a55a5a26b01683207d11023d33f55/src/logging.ts#L153-L155
Unfortunately, now that we're handling multiple logs per workspace/window, this means the support commands needed some updating as well:
- "Support: Save Logs" will now either save an …
=> cleanup: extension logfile handling

package.json
Updates the description of the `confluent.ssl.pemPaths` setting to be CCloud specific and help users avoid using it for direct connections (or otherwise).
| <img width="536" alt="image" src="https://github.com/user-attachments/assets/28c55b74-7f24-457e-943d-324bf946b9bf" /> | <img width="541" alt="image" src="https://github.com/user-attachments/assets/66a8e979-9a55-4c01-bb35-852cfc99b3db" /> | 
We may want to update the id/name of this as well to be more CCloud-focused, but that should probably come with a migration to get users' existing settings swapped over to it and include a `deprecationMessage` on the current setting id.
```shell
gulp clicktest
```
=> update description for CCloud use

CHANGELOG.md, src/sidecar/sidecarManager.ts
If the extension fails to handshake with the sidecar 20 times in a row, something is _very wrong_ and the sidecar process likely exited immediately after starting (unrelated to platform/arch compatibility). This PR tries to capture any stderr to a file, and after a couple seconds from the process spawn, check the process to see if it's still running while logging any stderr/log output. If the process isn't running by the time that check happens, we report it to Sentry with the stderr and log output to expedite debugging so we can get a proper fix merged.
```shell
gulp clicktest
```
=> [v0.26.x] watch for issues during sidecar process start

CHANGELOG.md, src/models/environment.test.ts, src/models/environment.ts
| | |
| Before | <img width="308" alt="image" src="https://github.com/user-attachments/assets/ab60bc33-6088-4922-b578-2f139e7fcd51" /> |
| After | <img width="307" alt="image" src="https://github.com/user-attachments/assets/ec6334ca-6cd5-4f86-a7d2-3db2ad841c88" /> | 
Closes #1181.
=> MINOR: change failing direct connection icon in the Resources view

src/constants.ts, src/models/schema.ts
Looks too much like the "missing icon" icon. We can replace it with something more schema-like in the future.
Before:
After:
Closes #1182.
=> MINOR: remove `primitive-square` schema icon

package-lock.json, package.json
Resolves https://github.com/confluentinc/vscode/security/dependabot/13.
No issues seen after `gulp build` (dev or prod).
=> security: update `esbuild`

CHANGELOG.md, src/commands/topics.test.ts, src/commands/topics.ts
Closes #1184.
Mostly testing updates, actual fix is here where we now guard against objects and arrays:
https://github.com/confluentinc/vscode/blob/cb82c9d6f1d853c7faa6f3eee312b1e22e2290ec/src/commands/topics.ts#L403-L408
```shell
gulp clicktest
```
=> fix: don't set MessageViewerConfig `textFilter` when produce-message key is an object

src/consume.ts, src/telemetry/events.ts
- Refactor message-viewer telemetry logging to be able to include metadata about the connection/environment/cluster.
- Include the SHA256 -> hex encoding of the topic name.
- New augmented sub-event for exactly when message viewer is opened.
- Closes #1045
```shell
gulp clicktest
```
=> Have all telemetry events from message viewer include topic/cluster/environment metadata.

src/commands/schemaUpload.ts, src/telemetry/events.ts
- New telemetry event family for "Schema Action"s , first being for  schema uploads attempts, be they successful (accepted by the SR) or not as indicated by "status": "succeeded" or "failed".
- Includes metadata about the schema registry, the schema document language, and the SHA256s of the subject name and the schema document body.
Slightly stale screenshots:
Successful upload, `status: "success"`
Syntax error within the document failure example,`status: "failure"`.
- Closes #1207
```shell
gulp clicktest
```
=> Telemetry event when uploading schemas, includes hashes of subject name and schema body

src/directConnect.ts, src/directConnections/credentials.ts, src/directConnections/types.ts, src/models/environment.ts, src/sidecar/connections/watcher.test.ts, src/sidecar/connections/watcher.ts, src/storage/migrations/v2.test.ts, src/storage/resourceManager.ts, src/webview/auth-credentials.ts, src/webview/direct-connect-form.ts, tests/unit/testResources/authCredentials.ts
Refactors `notifyForFailedState()` into `reportUsableState()` and adds a general helper function to summarize the `ConnectedState` and `ConnectionSpec` along with additional properties we use based on the direct connection form:
https://github.com/confluentinc/vscode/blob/616139c5dfca2da868f76f5bc679f05330ea62f2/src/sidecar/connections/watcher.ts#L122-L141
Some of these telemetry updates required some helper functions and types that were previously only used in the `webviews/` area, so this is the first PR to start using a `src/directConnections/` subdirectory. Follow-on PRs will break up `directConnectManager` and probably some others.
```shell
gulp clicktest
```
=> update telemetry for success+failed direct connections

package-lock.json, package.json
Resolves https://github.com/confluentinc/vscode/security/dependabot/16
https://github.com/confluentinc/vscode/blob/b4803a0fc66c0e25d2947212115d7fe1dc0027b3/package-lock.json#L4960-L4962
Re-running `gulp apigen` didn't behave any differently and yields no changes in client code.
=> security: update `openapi-generator-cli` for `axios` CVE

src/directConnect.test.ts, src/directConnect.ts, src/webview/auth-credentials.ts, src/webview/direct-connect-form.html, src/webview/direct-connect-form.ts
- Some follow up tasks for the direct connect form.
- More to come, trying to keep PRs small
- Now validating required fields in `auth-credentials` component & preventing form submission if they're missing
- Unit tests for `deepMerge` function
- Custom patterns for validation. We may want to add this in the future for urls, etc
- Fancy JavaScript and CSS for validation messages. For now I'm using the default HTML validation. In the future we may want to add custom UI for validation messages so it matches other design choices
Choose any auth type except "None" in the form. You should not be able to submit without filling in the required fields for that type (which ones are required varies by type but all of them have > 2 required fields)
Please check if your PR fulfills the following (if …
=> Connection form - validation on required fields, add tests

src/webview/auth-credentials.ts, src/webview/direct-connect-form.spec.ts
- Fixes a bug where default values don't get added to the form if they aren't touched. 
- Closes https://github.com/confluentinc/vscode/issues/1227
- Since we are deep in web component land, we need to send all the values explicitly to the parent form using `_internals.setFormValue`. 
- Previously we were only setting these values on the 'input' event, so if they weren't touched they were not submitted with the form data. 
- This PR introduces `initializeFormValues` method to go through inputs and add them to the form data, and calls it in the connectedCallback, as well as sets a watcher to call again if the auth type or creds change
- [NO] Does anything in this PR need to be mentioned in the user-facing …
=> Connection form - fix default value submission

src/webview/direct-connect-form.ts
- Adds an event listener to the `Enter` keydown event and uses it to click the primary form submit button (Save or Update) instead of the default, which would be the first button in the DOM - here that is the left button, corresponding to the secondary action (Test). 
- We noticed that the analytics show an extremely high ratio of "Test" submissions vs "Save" submissions on the form. 
- Team members reported pressing `Enter` when making fast changes and expecting it to Save/Update but instead it would Test. 
- Since `Enter` by default _will_ Submit an HTML form, and most forms have only one submit action, it seems better to make sure that expectation is kept here by assuming a user pressing `Enter` key wants to Save not Test. 
Please check if your PR fulfills the following (if …
=> Custom enter key event handler to submit

src/webview/direct-connect-form.html, src/webview/direct-connect-form.spec.ts, src/webview/ssl-config-inputs.ts
- Add doc titles/headers to the sections
- Align file button with input
- Disable password fields if PEM type file (not supported)
- Hide advanced TLS config for Schema Registry on CCloud (not supported)
- Copy edits for titles come from internal wiki doc. 
- Not done but mentioned in the wiki doc - conditionally display certain text for Confluent Cloud. At the moment this component has no knowledge of the platform type selected in the parent form. This feature can be added in a future PR if desired. 
```shell
gulp clicktest
```
=> Connection form - TLS Config section copy/ux updates 

CHANGELOG.md, src/commands/topics.test.ts, src/commands/topics.ts, src/errors.ts, src/schemas/parsing.test.ts, src/schemas/parsing.ts, src/schemas/validateDocument.ts
When producing messages to a topic, the current behavior on `main` when any errors occur is we show a notification that repeats the error names over and over, doesn't provide any help for scenarios like validation-related issues (unless you go digging through the logs):
This PR adds an extra parsing step to any `ResponseError`s we see from the produce request to specifically catch `status: 400` messages and re-throw as a `ProduceMessageBadRequestError` with the response body. Those are then combined with the index of the failed message(s) to add diagnostics to the original document rather than show a generic `Response returned an error code`.
While adding some extra handling for these error cases, we're also now aggregating `message` values for multiple errors to summarize in the …
=> improve: handle response errors from producing messages

src/testing.ts
In different scenarios, we may try running tests and end up with a ton of mysterious failures. This PR attempts to activate the extension and start the sidecar before all other tests kick off as part of the Mocha (global) `beforeAll` hook, because otherwise we end up with dozens of unhelpful test failures.
Wall of test failures:
...when the actual culprit is nested in the middle of the test output where the passing/pending/failing summary starts listing all failures:
Same wall of test errors, but unhelpful initial failure(s):
...which then means the reason is more toward the top of the test output after a number of tests have already run (and the non-sidecar-dependent tests have passed):
---
And if all is good, we should get this log line to give us the warm-and-fuzzy feeling that the …
=> update global test setup to confirm we can activate the extension and start the sidecar before the actual test suites run

.prettierrc, eslint.config.mjs
This is a pretty terrible experience on Windows:
After these changes, no prettier errors and `npx gulp lint` works as expected:
https://prettier.io/docs/options#end-of-line
=> fix(windows dev): remove end-of-line checks from prettier/eslint configs

src/extension.ts
We can't try/catch the errors in `createSession()` and return null/undefined since the interface [expects an `AuthenticationSession`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8c9533835001e60135d5ede3d75934e7b26aa4b3/types/vscode/index.d.ts#L17680) return type.
So we're ignoring these:
https://github.com/confluentinc/vscode/blob/260cbe86410f1c9f9bb5fdef0e371f3afebfe36b/src/authn/ccloudProvider.ts#L137-L157
Also removes `captureException` because that didn't seem to actually do anything.
=> MINOR: don't send handled CCloud auth errors to Sentry

src/webview/direct-connect-form.html
- Remove the word "yet" from the tooltip
"Changing the authentication type of an existing connection is not supported ~yet~"
- Maybe we'll support it, maybe we don't need to 🤷
=> minor copy edit: not yet

src/directConnectManager.ts, src/sidecar/connections/watcher.ts
Small changes so the telemetry from https://github.com/confluentinc/vscode/issues/1228 and https://github.com/confluentinc/vscode/pull/1238 play nicely together. Only real difference between those two events being reported is the `successfully connected`/`failed to connect` include `configType` to describe which part of the connection failed. Other fields
Follow-on branch to implement an interface based on the `UserEvent` enum value.
=> MINOR(telemetry): standardize DirectConnectionAction body

src/commands/index.test.ts, src/commands/index.ts, src/models/resource.test.ts, src/models/resource.ts
Mainly for `connectionType`, but once we were there it seemed easy enough to look at some of the other fields we care about for usage: `environmentId`, `clusterId`, etc:
Closes #459
```shell
gulp clicktest
```
=> telemetry: add "arg context" to send resource IDs and connection types for commands used

src/commands/diffs.test.ts, src/commands/diffs.ts
- Fixes behavior when reading the "select for compare"d Uri from storage to ensure the first character of the path isn't lowercase and breaking our Uri comparison. The diff view would still show up, but the `title` was wrong:
|  | |
| Before | ![image](https://github.com/user-attachments/assets/89bb5f21-771a-4e5c-8875-23044d519385) | 
| After | ![image](https://github.com/user-attachments/assets/cfc98753-2479-4e2a-bc39-6ad347957d40) | 
- Updates the test to make it easier to see if any particular `executeCommand` call arg isn't what we expect
```shell
gulp clicktest
```
=> fix(windows): handle lowercase first character for stringified Uri path

src/docker/configs.test.ts
No functional changes, just a test fix for Windows. Closes https://github.com/confluentinc/vscode/issues/1250.
Related code:
https://github.com/confluentinc/vscode/blob/cfa4284a89536010569341753344cce17bbc815a/src/docker/configs.ts#L36-L37
```shell
gulp clicktest
```
=> MINOR: fix test for windows `docker/configs functions: getSocketPath() should return socket path from user settings`

src/loaders/resourceLoader.ts, src/models/schema.test.ts, src/models/schema.ts
- Inspired by the stack traces within #1262 , harden up some of the codepaths around fetching subjects / the latest schemas.
- But the code has changed a good bit between when the sentry issue happened and main, so is loosely inspired. Main bits are to harden `Subject` construction to recoil immediately if a Subject is attempted to be constructed with a bad (null, undefined, or empty string) name. And then if any unexpected errors happen within a call to `ResourceLoader.getSubjects()`, log a sentry report.
- The underlying issue in #1262 is that the old codepath for "show latest schemas for a topic" command fell over dead when encountering an undefined as one of the subject strings to consider (back when there were only `Schema` objects, no `Subject` vs `Schema` differentiation). This was …
=> Harden getting subjects / gather more information if problem happens.

src/commands/topics.ts, src/commands/utils/produceMessage.test.ts, src/commands/utils/produceMessage.ts, src/schemas/produceMessageSchema.ts
We previously had to send `type: "JSON"` for CCloud produce-message requests using the old route (before https://github.com/confluentinc/ide-sidecar/pull/335). Non-CCloud topics wouldn't pass `type` at all, and the new route doesn't support it, so we're dropping `type` from the `keyData`/`valueData` parts of the request body altogether.
Closes #1273.
```shell
gulp clicktest
```
=> fix: don't send `type` for produce message requests

src/webview/direct-connect-form.ts
- We get a TypeError on first form load since this field isn't defined until the config is passed along. I think this is affecting all other JS in the form, causing silent errors for other SSL fields in that section
- To test - verify that you can save & edit a new connection with TLS config details. Verify you can use the "Select File" button to add the file. 
```shell
gulp clicktest
```
=> Connection form: make sure we don't flip out on undefined fields

src/commands/topics.test.ts, src/commands/topics.ts
`ProduceMessageBadRequestError` was incorrectly wrapping the `ResponseError` instead of the `Response`, so when it was caught and handled by `logError()`, trying to `clone()` it didn't make any sense and would throw a `TypeError`.
However, it didn't affect the behavior of the error-handling as far as the produce-message flow goes, so there are no user-facing changes here, and this is mainly cleanup. See the noisy `telemetry` logs here:
```shell
gulp clicktest
```
=> [v1.0.x] fix: `ProduceMessageBadRequestError` needs to wrap the `Response`, not the `ResponseError`

src/directConnect.ts
- We need to `deepMerge` the existing connection with the updated values, or we can lose nested parts of the spec. 
- I also removed the unnecessary `if` block to check import/edit status. These conditions are mutually exclusive - if you have a `connection` already, you are either `import`ing or `update`ing it. 
- This is hard to run into as a user - I only found it because I was testing a different fix for that pesky `Select File` button. 
- Reproducible if you're `Edit`ing an existing connection, and the spec you're editing already has `keystore` OR `truststore` (but _not both_). Then, for your very first Edit, use the `Select File` button to choose a path for the key/trust you did **not** already have.
```shell
gulp …
```
=> hotfix: updating tls configs could remove existing configs

CHANGELOG.md, src/authn/ccloudProvider.ts, src/extension.ts, src/preferences/constants.ts, src/preferences/listener.test.ts, src/preferences/listener.ts, src/preferences/updates.test.ts, src/preferences/updates.ts
This PR adds two main changes that should help users updating the extension:
1. We have an explicit step to `getSidecar()` before any other requests may start firing. This is to ensure we don't start piling on the async event loop and then discover we have an old version of the sidecar running (during an extension update), which then may result in a race condition where the old-sidecar access token header was used on new-sidecar.
2. User settings are now the ultimate source of truth for the SSL/TLS-related "preferences":
- We were previously fetching the preferences from the sidecar, then merging any updates from the user settings, then sending an update (via `PUT` request) to the sidecar. Now we just look at the user settings and send the applicable settings to the sidecar, and that's …
=> [v1.0.x] fix: failing to fetch preferences when updating the extension

CHANGELOG.md, src/authn/ccloudProvider.ts, src/extension.ts, src/preferences/constants.ts, src/preferences/listener.test.ts, src/preferences/listener.ts, src/preferences/updates.test.ts, src/preferences/updates.ts
https://github.com/confluentinc/vscode/pull/1296 to `main`, with some slight adjustments on double-quotes wrapping the `version` in extension activation logging
=> 🍒 [main] fix: failing to fetch preferences when updating the extension

src/sidecar/sidecarManager.ts
- Remove setting sidecar env disabling the websocket hack, since removed in https://github.com/confluentinc/ide-sidecar/pull/362 , sidecar 0.181, which we're already up to speed on as of https://github.com/confluentinc/vscode/pull/1304
=> Stop setting now-removed sidecar flag

Gulpfile.js, src/featureFlags/evaluation.test.ts
VS Code Insiders runner kept failing this one test in CI:
I originally thought it was flaky and couldn't produce locally, but that was because we had an issue with the way we were setting the `version` in the Mocha runner: because we likely weren't specifying the `VSCODE_VERSION` environment variable locally, any `gulp testRun` would spin up a VS Code (stable) runner.
Now we have another check based on whether the `gulp` task was kicked off within a VS Code stable/insiders terminal (using the VS Code built-in `TERM_PROGRAM_VERSION` env var), to then use that if `VSCODE_VERSION` wasn't provided. This means running `gulp test` inside a VS Code Insiders terminal will use `insiders` by default:
...and `gulp test` from inside a VS Code (stable) terminal will use `stable` by default:
And …
=> fix: test for VS Code Insiders and add version check for local test runner

src/models/schema.test.ts
We had a lingering "skipped" test that didn't have a `.skip()`, but looks like this was leftover from https://github.com/confluentinc/vscode/pull/1071
```shell
gulp clicktest
```
=> MINOR: remove skipped test fragment

CHANGELOG.md, package.json, src/context/values.ts, src/extension.ts, src/preferences/constants.ts, src/preferences/listener.test.ts, src/preferences/listener.ts
Adds a new preview setting (`confluent.preview.enableFlink`) to allow toggling in-development Flink work on/off, and also an associated context value (`confluent.flinkEnabled`) to inform the VS Code UI when upcoming commands/actions should be visible.
For now, this context value only controls whether or not the placeholder `confluent-flink` view is available at all. There is no view provider for it, as it will be covered in a separate branch as part of https://github.com/confluentinc/vscode/issues/1320.
```shell
gulp clicktest
```
=> add preview setting for upcoming Flink work

src/commands/schemaUpload.ts, src/commands/schemas.ts, src/emitters.ts, src/models/schema.test.ts, src/models/schema.ts, src/viewProviders/schemas.test.ts, src/viewProviders/schemas.ts, src/viewProviders/topics.ts, tests/unit/testResources/schema.ts
- Have create schema command emit the same events as delete schema command does to decouple the action from the view controllers (as well as to improve behavior in the topics view, which was wholly ignorant of when a new subject was created or a new schema version added to an existing subject).
- New subtype for a Subject which _must_ have a non-null schema array, used for the events when we definitely know the new schema versions which should be shown in views.
- When a schema version is added or removed, and the subject is known to the subject view already, then do a smart merge join between the new known schema versions fresh from a route call and any existing versions known to the subject view:
- If present in both, keep in the cached subject's schemas to keep the corresponding …
=> Have schema upload command use same events as delete schema command

src/commands/kafkaClusters.test.ts
- Have the test over `copyBootstrapServers()` stash away any existing clipboard contents, restore it afterwards.
=> Reduce test suite leakage affecting clipboard contents.

Gulpfile.js, src/commands/docker.ts, src/commands/topics.ts, src/consume.ts, src/errors.ts, src/extension.ts, src/telemetry/eventProcessors.ts, src/telemetry/sentryClient.ts, src/viewProviders/resources.ts
- Change the way we setup Sentry to manually create the NodeClient and Scope (instead of using the node package's managed `init` function), giving us full control over the exceptions captured and removing the possibility that 3rd party errors will make it in our Sentry account. 
- Move any calls to `Sentry.captureException()` to either call the new method, or use the new-ish `logError()` function, which was updated with the new capture method as well. 
- Closes #982  <-- see issue for more info
- Made it similar to the `telemetryLogger.ts` pattern where Sentry Scope and Client will be initialized only once. 
- ⚠️ We will need to be extra diligent about catching & sending any exceptions to Sentry in the code, since this setup removes the global handlers (e.g. "OnUnhandledRejection", …
=> chore: move Sentry init logic, manually setup client

CHANGELOG.md, package.json, src/chat/constants.ts, src/chat/errors.ts, src/chat/participant.ts, src/chat/references.ts, src/context/values.ts, src/extension.ts, src/preferences/constants.ts, src/preferences/listener.test.ts, src/preferences/listener.ts
Another new setting + context value combo, but this time for the Copilot chat participant:
Setting is marked as experimental since this is currently just a Q&A bot (which goes [against the guidelines](https://code.visualstudio.com/api/extension-guides/chat#guidelines:~:text=Chat%20participants%20should%20not%20be%20purely%20question%2Danswering%20bots.)) and doesn't have any helpful actions, tools, context, etc. Those should be handled in follow-up branches as part of the [Copilot chat participant integration milestone](https://github.com/confluentinc/vscode/milestone/16).
Closes #1327, closes #1328.
No wholly new tests since all of this is bound to change in the short term.
In click-testing, it looks like the approach to use whatever language model is selected in the normal model …
=> add basic Copilot chat participant behind experimental setting

CHANGELOG.md, package.json, src/commands/diffs.ts, src/context/values.ts, src/extension.ts
This PR addresses some necessary follow-up from #799 where we lost the built-in ability to diff (Kafka topic) message documents with the move from JSON editors to `confluent.topic.message`-schemed URIs.
Using that URI scheme (along with `confluent.schema`-schemed URIs), we can provide the existing "Select for Compare" and "Compare with Selected" commands in both the editor title area as well as the editor context itself:
https://github.com/user-attachments/assets/d5d5cbb5-3f26-422d-863c-75ec035f75ea
Closes #1343.
I also tried exposing these commands in the "Open Editors" view, but nothing in https://code.visualstudio.com/api/references/contribution-points#contributes.menus or https://code.visualstudio.com/api/references/when-clause-contexts#available-context-keys seems to indicate exactly …
=> re-enable message diffing and allow diff commands from more areas

src/commands/topics.ts
- Add a check in `editTopicConfig` to return early if the topic is not defined or not a KafkaTopic. 
- Closes #1349 
-We've noticed that at runtime VS Code could pass an undefined or different type than expected if, for example, another item is highlighted/selected while invoking the command, or the tree view is refreshing.
```shell
gulp clicktest
```
=> when editing topics - return early if topic isn't the type we expected

CHANGELOG.md, package.json, src/constants.ts, src/graphql/environments.ts, src/models/environment.test.ts, src/models/environment.ts, src/models/flinkComputePool.test.ts, src/models/flinkComputePool.ts, src/preferences/listener.ts, src/viewProviders/resources.ts, tests/unit/testResources/environments.ts, tests/unit/testResources/flinkComputePool.ts
This PR adds the first few Flink compute pool related models, and updates our CCloud environment (GraphQL) query to add them as children to `CCloudEnvironment`s. When the `confluent.preview.enableFlink` setting is toggled and the user is signed in to CCloud, it will trigger a refresh of the Resources view:
https://github.com/user-attachments/assets/1759ea63-c956-4913-8fd1-aff819ad4c15
This also includes some initial empty-states for the Flink view (also toggled from the same preview setting) that will be updated further in follow-on branches for https://github.com/confluentinc/vscode/milestone/17.
```shell
gulp clicktest
```
=> feat: show Flink compute pools in Resources view

src/errors.ts
- Link  `FlinkComputePoolResponseError` into `isResponseError()`.
- Closes #1372 
```shell
gulp clicktest
```
=> Link FlinkComputePoolResponseError into isResponseError().

package.json
We're preemptively trying to avoid any mixed-resource-type views and currently intending on only displaying Flink (SQL) statements in one view, and Flink artifacts in another view. This should reduce the need to complicate a view provider, and make it easier for users to hide one or the other view if desired.
The `contextualTitle`s added to each view to help when [a view is moved](https://code.visualstudio.com/api/references/contribution-points#contributes.views) out of the main "Confluent" view container:
> Human-readable context for when the view is moved out of its original location. By default, the view's container name will be used.
Before this PR, each moved view would just say "Confluent", which wasn't particularly helpful.
Please check if your PR fulfills the following (if …
=> split Flink view into Statements and Artifacts views

src/featureFlags/handlers.ts
https://support.launchdarkly.com/hc/en-us/articles/12998125691419-Error-LaunchDarklyFlagFetchError-network-error
> It is relatively common to see general network errors logged. Our SDKs are designed to be resilient and maintain a network connection to LaunchDarkly. If the SDK ever loses connectivity, it will continue to attempt to reconnect until it can. Until then, the SDK will evaluate flags using the most recently cached values.
Closes #1404.
=> stop sending common `network error` events to sentry

CHANGELOG.md, package.json, src/extension.ts, src/scaffold.ts
- Adds a new command & context menu action to scaffold a new project from a Topic or Cluster in the sidebar, filling in the known bootstrap server address and topic name if we can find it. 
- Closes #1333 
- This depends on project template options being named with specific strings: `topic` or `cc_topic` for example. To make this the most useful, we will need to decide how to encourage or reinforce that pattern for template authors. 
```shell
gulp clicktest
```
=> Add right-click scaffold actions for cluster, topic

src/sidecar/sidecarManager.ts
- Provide more detailed information to Sentry if a sidecar executable isn't stat-able, most interestingly the underlying exception raised by `fs.stat`.
- We received a sentry event over the `reject(new NoSidecarExecutableError(`Component ${executablePath} does not exist`))` line, but more information is needed.
- That said, it feels like a one-off error, perhaps the user actually deleted their sidecar executable.
- Related to #1379, gathers more information if it happens again, but doesn't c l o s e anything.
```shell
gulp clicktest
```
=> Send more info to Sentry if cannot stat the sidecar executable.

src/sidecar/sidecarManager.test.ts, src/sidecar/sidecarManager.ts, src/sidecar/utils.ts
Change philosophy of `killSidecar()`, making it:
1. Deliver kill signal, initially `SIGTERM`, allowing either old version or wrong access token) sidecar to gracefully shut down.
2. Loop up to 4s over pausing 500ms, then checking to see if sidecar pid is still alive.
-  If dead, awesome, done.
3. If alive after 4s and delivered `SIGTERM` initially, go back to 1, but with `SIGKILL` (limited recursion).
4. If alive 4s after delivering `SIGKILL`, then give up.
Prior philosophy was to send `SIGTERM`, then blindly pause 500ms, then blunder on and hope for the best, leading to sometimes starting new sidecar while prior one still held the server socket open, leading to hilarity.
100% test coverage on the changed code, slightly complicated because `process.kill` is used to both deliver signals as …
=> Harden killSidecar() in face of sometimes unknown-reason slow-to-die sidecar processes.

CHANGELOG.md, src/commands/schemas.ts, src/commands/utils/schemas.ts
- Notice that when deleting a subject would be only deleting a single schema and is equivalent to deleting a single subject within, to then use the simpler prompt requiring the user to type fewer things (just the version number).
- Trying to make simpler things simpler. Unlike the sentence above.
- Closes #1420
```shell
gulp clicktest
```
=> When deleting a subject with a single schema, use the simpler single-schema-version deletion confirmation prompt.

package.json, src/commands/flinkComputePools.ts, src/context/values.ts, src/emitters.ts, src/errors.ts, src/extension.ts, src/models/flinkComputePool.ts, src/quickpicks/flinkComputePools.ts, src/viewProviders/base.ts, src/viewProviders/flinkArtifacts.ts, src/viewProviders/flinkStatements.ts
This PR adds a Flink compute pool quickpick and three new commands:
- `confluent.resources.flink-compute-pool.select`: the primary action on any Flink compute pools displayed in the Resources view. This will focus that pool in both the Flink Statements and Flink Artifacts views.
- `confluent.statements.flink-compute-pool.select`: the nav action at the top of the **Flink Statements view** to focus a compute pool for only that view
- `confluent.artifacts.flink-compute-pool.select`: the nav action at the top of the **Flink Artifacts view** to focus a compute pool for only that view (but follow-on work shouldn't handle any pool-specific filtering, just env+region+provider)
https://github.com/user-attachments/assets/1a771c7a-1aef-4f44-89f5-77adf86cfb06
(Slight adjustments to the fake data …
=> implement Flink compute pool selection commands and quickpick

CHANGELOG.md, package.json, src/models/schema.test.ts, src/models/schema.ts
- "View in Confluent Cloud" item added to ccloud-based subjects (previously only available on individual schemas).
- Closes #1424 
```shell
gulp clicktest
```
=> "View in Confluent Cloud" item added to ccloud-based subjects 

src/extension.ts, src/models/flinkStatement.test.ts, src/models/flinkStatement.ts, src/viewProviders/base.test.ts, src/viewProviders/flinkStatements.ts
- Enable "Copy Name" for flink statements and artifacts; enable "Copy ID" for just Flink artifacts.
- Revise Flink statements model to take in `name` at constructor time, since that's what will be coming from  [real API responses](https://docs.confluent.io/cloud/current/api.html#tag/Statements-(sqlv1)/The-Statements-Model). Have its `id` be a gettable property for our codebase-internal needs (namely for `FlinkStatementTreeItem` readability, and probable upcoming `BaseViewController` changes.
- Closes #1419
-
```shell
gulp clicktest
```
=> Enable "Copy Name" for flink statements and artifacts; enable "Copy ID" for just Flink artifacts.

CHANGELOG.md, src/utils/file.test.ts, src/utils/file.ts
- Consult the list of *workspace* open files when submitting schema documents, not the list of
*window* open editors, #1429. The user may have chosen an untitled document from a window distinct
from the one they have the extension open in.
- Closes #1429.
```shell
gulp clicktest
```
=> Fix #1429 in v.1.1.x

README.md
We'll have to [update the Semaphore agent used for building the ide-sidecar's native executable to a newer Ubuntu version](https://github.com/confluentinc/ide-sidecar/pull/396). As a consequence, the native executables can't be executed on Ubuntu versions older than 22.04.
-
```shell
gulp clicktest
```
=> chore: Require Ubuntu 22.04 or newer

CHANGELOG.md, src/preferences/updates.test.ts, src/preferences/updates.ts
Floats an error notification whenever we try to push workspace configs to the sidecar for CCloud TLS/SSL settings. In most cases, this issue comes up because of an invalid cert path, so there's an "Update Settings" button added if the error `source` includes `"tls_pem_paths"`:
https://github.com/user-attachments/assets/b40aa756-bf77-4f12-90df-86d5efb51986
Closes #1011.
I realized partway through this branch that our specs (sidecar, ce-kafka-reset, scaffolding-service) are using an [`Error` schema](https://github.com/confluentinc/vscode/blob/af88393600e09f319619230587d870189a79f5fb/src/clients/sidecar-openapi-specs/sidecar.openapi.yaml#L795-L810) (as part of the [`Failure` schema](https://github.com/confluentinc/vscode/blob/af88393600e09f319619230587d870189a79f5fb/src/clients/sidecar-openap …
=> show error notification on failure to sync settings to the sidecar preferences API

src/telemetry/sentryClient.ts
Closes #1454, hopefully we won't need to add any of those other error message strings back in to the client-side filtering
=> don't send `Canceled` errors to sentry

src/loaders/ccloudResourceLoader.ts, src/viewProviders/flinkStatements.ts
- Have CCloud loader also fetch (and cache) the user's organization id concurrently with the fetch for the Confluent Cloud environments.
- Makes fetching the first Flink resources (statements, artifacts) go one step faster because organization id will already be known. We can't use the Flink API clients until we know the organization ID -- is part of the API paths.
- The original ticket thought that this could be done by watching websocket connection events, and that the organization id will be pushed to us. Alas:
- Even though the organization id field is in the spec, it was optional and doesn't seem to be populated when we get a ccloud connection change event pushed to us.
- Even if it were present, we won't always get this event (say, second workspace coming online _after_ sidecar …
=> Eagerly fetch + cache users's ccloud organization ID as a "coarse resource"

src/commands/environments.ts, src/quickpicks/environments.test.ts, src/quickpicks/environments.ts
- Generalize `ccloudEnvironmentQuickPick()` to take an optional filter function to use to filter the possible environments.
- Make convenience variant, `flinkCcloudEnvironmentQuickPick()`, only offering the flinkable environments as determined at this time by the presence of at least one flink cluster, wired up into the command for picking the environment to show flink statements for.
- While here,  make`ccloudEnvironmentQuickPick()` consult the CCLoudResourceLoader cached environments, not deep-graphql-fetch every time.
- Closes #1476
- Closes #1466
```shell
gulp clicktest
```
=> 1476 filterable environment quickpick

src/ccloudStatus/api.test.ts, src/ccloudStatus/api.ts, src/chat/participant.ts, src/commands/index.ts, src/commands/schemas.ts, src/commands/topics.ts, src/consume.ts, src/errors.test.ts, src/errors.ts, src/extension.ts, src/featureFlags/client.ts, src/featureFlags/handlers.ts, src/graphql/direct.ts, src/graphql/environments.ts, src/graphql/local.ts, src/graphql/organizations.ts, src/loaders/resourceLoader.test.ts, src/loaders/resourceLoader.ts, src/preferences/updates.test.ts, src/preferences/updates.ts, src/scaffold.ts, src/sidecar/connections/index.ts, src/sidecar/sidecarManager.ts, src/sidecar/websocketManager.ts, src/utils/workerPool.ts, src/viewProviders/resources.ts, src/viewProviders/schemas.ts
Thank you for the clear and detailed issue, @shouples ! 
Drafting since I had a question. 
I [didn't remove the TODO](https://github.com/confluentinc/vscode/compare/main...scope-ctx-for-logerr#diff-55db69e02ff5714d444d8081ec6ecac5d9833fb29fda64d1e829e5766434fdc0L134), because the [beforeSend](https://docs.sentry.io/platforms/native/guides/crashpad/configuration/filtering/#event-hints) callback wasn't present in the codebase, and [this was the only documentation I ](https://docs.sentry.io/platforms/native/guides/crashpad/configuration/filtering/#event-hints)could find on the `EventHint` type. Can you say more about what you were thinking?  
```
logger.error(errorMessage, { ...errorContext, ...sentryContext });
// TODO: follow up to reuse EventHint type for capturing tags and other more …
```
=> #1456: Support ScopeContext interface for logError()

package.json
We're focusing on statements for right now, and won't be getting around to Flink artifacts management until the statements UI/UX is in at least an MVP state. Disabling the view and its associated `confluent.artifacts.flink-compute-pool.select` command while keeping the underlying code available for when we revisit. (Or if we decide to go another direction and combine resources under a singular Flink Resources view, we can delete the artifacts-specific view+commands separately.)
Confirmed selecting pools from the Resources view still works fine and doesn't holler about `confluent.artifacts.flink-compute-pool.select` not being enabled:
https://github.com/user-attachments/assets/7891dba3-0855-4297-883e-44b8e6db0c29
```shell
gulp …
```
=> temporarily disable artifacts view

src/directConnectManager.test.ts, src/storage/resourceManager.test.ts, src/storage/resourceManager.ts
More focused than https://github.com/confluentinc/vscode/pull/1488. @jlrobins and I aren't sure that this will actually fix the test flakiness since the changes shouldn't ultimately change the handling of adding connections and asserting that they exist.
Using https://github.com/confluentinc/vscode/issues/1495 for `addDirectConnection` cleanup, but that also shouldn't affect this test.
```shell
gulp clicktest
```
=> simpler fix(test): `deleteDirectConnections() should delete all direct connections`

package.json, src/chat/constants.ts, src/chat/messageTypes.test.ts, src/chat/messageTypes.ts, src/chat/participant.ts, src/chat/tools/README.md, src/chat/tools/base.ts, src/chat/tools/listTemplates.test.ts, src/chat/tools/listTemplates.ts, src/chat/tools/registration.ts, src/chat/tools/toolMap.ts, src/chat/tools/types.ts, src/extension.ts, src/scaffold.ts, src/storage/resourceManager.test.ts
This PR sets up some of the basic structures needed for our `@Confluent` Copilot chat participant to start using ["tools"](https://code.visualstudio.com/api/extension-guides/tools) based on lessons learned while collaborating with @Cerchie over https://github.com/confluentinc/vscode/pull/1458.
As part of this setup, the first tool exposes functionality **solely to the chat model** to allow it to list project templates from the scaffolding service by reusing [`getTemplatesList()`](https://github.com/confluentinc/vscode/blob/d1be37e68cd0d036dec3dc067ae5b486de71d864/src/scaffold.ts#L296C23-L296C39).
https://github.com/user-attachments/assets/6f424860-4fba-4f59-a6c4-71d310bc3156
Closes #1329, closes #1469.
Some other helpers are added here:
- …
=> feat: set up initial chat participant tool integration with "list project templates" tool

CHANGELOG.md, package-lock.json, package.json, src/authn/ccloudProvider.ts, src/commands/index.ts, src/extension.ts, src/featureFlags/client.test.ts, src/featureFlags/client.ts, src/featureFlags/evaluation.test.ts, src/featureFlags/evaluation.ts, src/featureFlags/handlers.ts, src/featureFlags/init.ts
https://github.com/confluentinc/vscode/pull/1166 unfortunately broke the extension for WSL users due to the added LaunchDarkly Electron Client SDK requiring the `electron` package. Remote instances attempting to run this extension quietly threw an error (visible in the `Extension Host (Remote)` output channel) and failed to even start activation due to https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-native-node.js-modules
> However, VS Code Server runs a standard (non-Electron) version of Node.js, which can cause binaries to fail when used remotely.
Thankfully, LaunchDarkly makes it easy to use both the [Node client SDK](https://launchdarkly.com/docs/sdk/client-side/node-js) and the [Electron client SDK](https://launchdarkly.com/docs/sdk/client-side/electron#why-u …
=> [v1.1.x] fix: use the LaunchDarkly Node SDK for remote environments

CHANGELOG.md, package-lock.json, package.json, src/authn/ccloudProvider.ts, src/commands/index.ts, src/extension.ts, src/featureFlags/client.test.ts, src/featureFlags/client.ts, src/featureFlags/evaluation.test.ts, src/featureFlags/evaluation.ts, src/featureFlags/handlers.ts, src/featureFlags/init.ts
https://github.com/confluentinc/vscode/pull/1512 to `main`, with a slight adjustment for the `logError` call since it accepts slightly different args (#1457)
https://github.com/confluentinc/vscode/blob/d58fe0d8781f2fb148e0fc360953bd4322dda2e3/src/featureFlags/init.ts#L27-L29
=> 🍒 [main] fix: use the LaunchDarkly Node SDK for remote environments

src/context/observability.ts, src/telemetry/telemetryLogger.ts
We get some of this automatically when sending errors to Sentry, but we won't get them for support requests. 
(We also previously [set platform/arch](https://github.com/confluentinc/vscode/pull/1225) in the telemetry logger, but didn't have `remoteName`.)
```shell
gulp clicktest
```
=> MINOR: add `platform`/`arch` and VS Code `env.remoteName` to observability context

src/quickpicks/schemaRegistries.ts, src/viewProviders/schemas.ts
- Have SchemasViewProvider know its view id; use it when making new `vscode.window.withProgress()`  calls over remote fetches. Mostly whitespace changes within `refresh()` and `updateSubjectSchemas()` as the work is now done within an inner async passed to `vscode.window.withProgress()`.
- Shows progress meter again while loading subjects or schemas.
- Closes #1463 
```shell
gulp clicktest
```
=> Show progress meter when loading schemas or subjects

src/commands/environments.ts
Fix for the scenario where a `FlinkStatement` is focused/selected in the view and the command is invoked through the view nav action:
Similar handling to our other nav actions, like the compute pool selection: https://github.com/confluentinc/vscode/blob/e27716e4c45fe2d755252d8b55102a908ee7b025/src/commands/flinkComputePools.ts#L18-L26
```shell
gulp clicktest
```
=> fix: prevent non-`CCloudEnvironment` arguments from being used in command

src/emitters.ts
We were having some trouble remembering what happened with CCloud auth and opening additional workspaces in different stages, so this is just to help us remember these transitions/scenarios.
=> MINOR: update docstring for `ccloudConnected` [ci skip]

src/scaffold.ts
No user-facing changes here, just adding more telemetry logging for handling URIs:
Worth noting this also adds `templateId` (as the template spec `name`) to the data sent back since we don't have the template spec `display_name` of the template at the time of handling the URIs.
Closes #1503.
```shell
gulp clicktest
```
=> update project scaffolding telemetry for URI handling

src/scaffold.ts
Updated telemetry with user notification in the event the template collection + name don't jive.
Closes #1536, closes #1537.
Also includes a minor typo fix for the "user canceled" result message.
```shell
gulp clicktest
```
=> allow optional `collection` arg when listing templates and set `templateCollection` for telemetry events

src/quickpicks/flinkComputePools.ts
Fixes a minor UX issue where selecting a Flink compute pool from the Resources view will populate the (hidden) Flink Artifacts view with a "focused" pool, which will show multiple "focused" pools if the pool for the Flink (statements) view is changed after the selection from the Resources view.
```shell
gulp clicktest
```
=> ignore hidden artifacts view pool

src/commands/kafkaClusters.ts, src/scaffold.ts, src/utils/bootstrapServers.test.ts, src/utils/bootstrapServers.ts
Moves the logic from https://github.com/confluentinc/vscode/blob/275e11db8783af3d3aa365bfd4a55b3d021791fb/src/commands/kafkaClusters.ts#L281-L285 (https://github.com/confluentinc/vscode/pull/1078) to a more accessible location and ensures we use it whenever generating a project from a Kafka cluster/topic from the sidebar.
https://github.com/user-attachments/assets/7729464b-a2ae-4741-9d2b-40288ca5d8d6
```shell
gulp clicktest
```
=> [v1.2.x] fix: remove protocol from bootstrap servers when generating project from Kafka cluster/topic

service.yml
Should help us only require certain blocks to pass for release branches, and have generally better visibility around which block(s) may be failing builds/tests/etc.
=> chore(CI): set up block-level PR status checks

src/loaders/ccloudResourceLoader.test.ts, src/loaders/ccloudResourceLoader.ts, src/models/flinkStatement.test.ts, src/models/flinkStatement.ts, src/models/organization.ts, src/models/resource.ts, src/viewProviders/base.test.ts, tests/unit/testResources/flinkStatement.ts, tests/unit/testResources/organization.ts
- Introduces a typed `OrganizationId` into the `FlinkStatement` model, this is used by the following PR #1565.
- Also introduces exported constants for the Flink statement phase.
- Use API generated types instead of custom types for most fields of `FlinkStatement`. 
This PR extracts refactorings made as part of #1565.
```shell
gulp clicktest
```
=> Refactor custom `FlinkStatement` model to use API generated models

src/flinkStatementResults.ts, src/webview/flink-statement-results.html, src/webview/flink-statement-results.ts
- Introduces a new state called `Completed` in the results viewer, this will be shown for system statements that execute and stop.
- Also fixes #1602 -- notifying UI on pause/resume button click
-
```shell
gulp clicktest
```
=> Introduce completed state in results viewer

src/commands/flinkStatements.ts, src/commands/utils/flinkStatements.ts, src/quickpicks/kafkaClusters.test.ts, src/quickpicks/kafkaClusters.ts, tests/unit/testResources/environments.ts, tests/unit/testResources/kafkaCluster.ts
- Extract the kafka-cluster-as-Flink-default-database quickpick  inlined in submit statement code. Will filter for those matching the provider and region as indicated by the provided compute cluster (could in future devolve to anything providing `provider` and `region`, and/or undefined if we want open-ended picking). Current known use case wants only the kafka clusters appropriate for a given compute cluster, so API matches that need for now.
- Address the lower-hanging nits left-over from https://github.com/confluentinc/vscode/pull/1562 . #1599 will mop up the rest soon.
- Closes #1596
```shell
gulp clicktest
```
=> 1596 flink database quickpick

.github/copilot-instructions.md
This PR sets up some basic instructions to help Copilot suggest better test practices, which will in turn help other contributors that are newer to the repo.
In future PRs, we can add some additional sections describing the overall architecture of the extension repo, sidecar interaction context, `src/clients` generation, `gulp` and `rollup` nuances, etc.
Context: https://docs.github.com/en/copilot/customizing-copilot/adding-repository-custom-instructions-for-github-copilot?tool=vscode
- uses chai/jest/expect instead of sinon and assert
- loads `copilot-instructions.md` context by default
- suggests using `sinon` and `assert`, with sandboxes and stubs if appropriate
=> add basic `copilot-instructions.md` to help with testing

src/scaffold.test.ts, src/scaffold.ts
This one is similar to #1592 but doesn't test `resourceScaffoldProjectRequest` directly (would need input on the contexts to import for that) but it does test the results of calling `scaffoldProjectRequest`  by resource type, which `resourceScaffoldProjectRequest` pretty much is a wrapper on. 
-
-
```shell
gulp clicktest
```
=> chore: Testing scaffold resource

src/commands/flinkStatements.ts, src/commands/utils/flinkStatements.test.ts, src/commands/utils/flinkStatements.ts
- Obtain the user's timezone's current offset from GMT, augment Flink statement context.
- Matches CCloud Workspaces behavior when submitting statements.
-Closes #1579
```shell
gulp clicktest
```
=> Describe user local timezone's GMT offset to Flink when submitting new statements.

.vscode/settings.json
We've had some issues with `gulp lint` catching formatting-related issues that can usually be addressed with `gulp format`, but handling that before each commit can be tedious. This PR adds some basic repo-level settings to use https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode and auto-format when a file is saved.
> [!NOTE]  
> These are definitely up for discussion/feedback, since they're mainly the settings I use and have shared with other folks that ran into the above linting issues.
=> set default `typescript` configs under `.vscode/settings.json`

docs/CONTRIBUTING.md
Follow-up from https://github.com/confluentinc/vscode/pull/1622 since not having https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode installed doesn't provide any feedback on document save
=> MINOR docs: add code formatting section to CONTRIBUTING.md

src/authn/ccloudStateHandling.test.ts, src/directConnect.test.ts
Noticed we had some references creating stubs/`SinonStubInstance`s off of `sinon` instead of the `sandbox`es, which is problematic since we don't use `sinon.restore()` anywhere in the test suites.
This _may_ be affecting some of the test flakiness (on windows agents in CI) we've seen with ResourceManager methods, but neither of the affect suites mess with direct connection storage/deletion, so my confidence isn't super high that the flaky behavior will cease. Regardless, this is necessary cleanup for consistency.
```shell
gulp clicktest
```
=> MINOR fix(testing): create stub instances from the sandboxes

src/commands/flinkStatements.ts, src/commands/utils/flinkStatements.test.ts, src/quickpicks/uris.ts
- #1615 caused by the nuance needed when using the `window.createQuickPick()` API and our subsequent need to sometimes open up `window.showOpenDialog()`.
- In buggy code spelling, the immediate explicit call to `quickpick.hide()` would cause the `onDidHide()` handler to fire _before_ the `window.showOpenDialog().then()` handler had a chance to be called, leaving us with `resolve(undefined)` from the  `onDidHide()` handler --- "prematurely." Any subsequent `resolve()` with the file picker's URI was moot. _That ship done sailed_.
- Moreover, even with the explicit `quickpick.hide()` removed, the `onDidHide()` is _implicitly_ fired when we make the `window.showOpenDialog()` call, so need to work around that by recording if we're going down that codepath.
- Closes #1615 
- Leaving #1627 as …
=> Prevent uriQuickpick() from resolving too soon when external file is chosen

package.json, src/commands/flinkComputePools.test.ts, src/commands/flinkComputePools.ts, src/flinkSql/flinkConfigManager.ts, src/quickpicks/flinkComputePools.ts
- Reuse code from @jlrobins recent PR - smart kafka cluster picker instead of a text field for the Flink default database
- Update copy in a couple places to make the "default" aspect of these settings clear
-
```shell
gulp clicktest
```
=> Flink settings followup: better db picker

src/commands/utils/flinkStatements.test.ts, src/commands/utils/flinkStatements.ts
- Use ccloud username as prefix for flink statements, not local username.
- Tests.
- Closes #1604
```shell
gulp clicktest
```
=> Make determineFlinkStatementName() use the ccloud username

src/commands/flinkComputePools.test.ts, src/commands/utils/flinkStatements.test.ts, src/commands/utils/flinkStatements.ts
=> MINOR: use CCloud authentication session's `label` (email) instead of `id`

src/webview/flink-statement-results.html
- Reformatted results viewer HTML.
-
```shell
gulp clicktest
```
=> Reformat results viewer with prettier

src/viewProviders/resources.test.ts
Closes #1655:
The main problem was:
- the test would fail, claiming the tree item had the wrong collapsible state (`0=none`,`2=expanded`)
- the test didn't fail on the `id` assertion, even though `id` is set after the collapsible state: https://github.com/confluentinc/vscode/blob/7d9d11a654838f3e3eccc60f985992405729c534/src/viewProviders/resources.ts#L587-L596
- this means something about the stubbing was not behaving correctly in the Windows environment, suggesting the `ResourceManager.getCCloudEnvironments()` method wasn't being called
- [`CCloudResourceLoader.getEnvironments()` is called](https://github.com/confluentinc/vscode/blob/7d9d11a654838f3e3eccc60f985992405729c534/src/viewProviders/resources.ts#L574) more closely to all the logic with these tree views, even though the loader's …
=> fix(test): swap stub for flaky test on Windows agent

CHANGELOG.md, package.json, src/codelens/flinkSqlProvider.test.ts, src/codelens/flinkSqlProvider.ts, src/commands/documents.test.ts, src/commands/documents.ts, src/commands/flinkStatements.ts, src/quickpicks/flinkComputePools.ts, src/storage/constants.ts
Follow-up to https://github.com/confluentinc/vscode/pull/1595 to allow setting the database (Kafka cluster with the same cloud provider+region as the chosen Flink compute pool) from a codelens in a `flinksql` document:
Closes #1644.
> [!NOTE]  
> Similar to #1595, this is mainly for generic functionality and smaller copy/UI branches will be done as follow-up work to this, which may include consolidating some of the codelenses and improving the overall flow.
Since we handle some "make sure the compute pool and catalog+db match CCloud provider+region" logic here, we ended up in a situation where:
- if you set the compute pool first (via unfiltered quickpick), which then filters the catalog+db quickpick based on the pool's cloud provider/region
- if you set the catalog+db first (via …
=> feat: add codelens for setting Flink statement catalog + database

src/webview/flink-statement-results.html, src/webview/flink-statement-results.ts
- Update column width code to allow for dynamic number of columns
- Move the settings gear to the left of table & adjust stuff so it fits there
- You should be able to resize and show/hide columns 
- It's a little jumpy while the results are streaming in & updating the `DOM`; works better when Paused
https://github.com/user-attachments/assets/3df8f773-0909-411a-86e7-92899dab88aa
https://github.com/user-attachments/assets/61bbf6a7-cf7f-4142-a94e-830a619a3c02
```shell
gulp clicktest
```
=> Statement results viewer - dynamic column sizes

CHANGELOG.md, src/loaders/ccloudResourceLoader.test.ts, src/loaders/ccloudResourceLoader.ts
We recently started seeing `No current organization found` errors that mainly came from trying to load CCloud resources from quickpicks (like the Kafka cluster quickpick) when the user wasn't signed in to CCloud:
This PR removes the error-throwing and instead skips returning any (mainly Flink) resources if we get the CCloud org.
New tests with previous behavior:
```shell
gulp clicktest
```
=> [v1.2.x] fix: `No current organization found`

package.json
Doesn't do anything when invoked since we fall through the `if`/`else` conditions and never end up calling `scaffoldProjectRequest()`: https://github.com/confluentinc/vscode/blob/13fe55f3eec273e01262432b43175c0a6804e6c1/src/scaffold.ts#L56-L92
Still appears on resources as expected:
=> MINOR cleanup: remove "Generate Project from Resource" from command palette

src/codelens/flinkSqlProvider.ts, src/commands/flinkStatement.test.ts, src/commands/flinkStatements.ts, src/models/flinkStatement.ts, src/storage/resourceManager.ts
This PR adds a step before opening any `flinksql` document from the Flink Statements view to ensure its associated compute pool ID and database property as stored in extension state. This allows the codelens provider to pre-populate the last values used and helps the user skip the quickpicks and easily resubmit (or change something and then resubmit without having to start from scratch):
https://github.com/user-attachments/assets/c6d13667-c75a-4828-88a4-df59c167e36b
Closes #1661.
This also loosens up our catalog/database matching since CCloud may store the names of resources instead of the ids:
https://github.com/confluentinc/vscode/blob/bf354e9ba6f8bfb1cf702316a601898147eada9a/src/codelens/flinkSqlProvider.ts#L216-L218
https://github.com/confluentinc/vscode/blob/bf354e9ba6f8bfb1cf702316a6 …
=> store Flink statement compute pool ID and database on document load

src/models/flinkStatement.test.ts, src/models/flinkStatement.ts, src/viewProviders/flinkStatements.test.ts, tests/unit/testResources/flinkStatement.ts
- Method to update the mutable fields of a `FlinkStatement` given a reference to an updated representation of the same statement.
- Will be used for doing piecemeal updates of non-terminal-state statements within the statement view in #1589.
- Simplify test names for `FlinkStatementsViewProvider`, dregs from #1666 PR comments.
- Closes #1709.
```shell
gulp clicktest
```
=> FlinkStatement.update(other)

package.json, src/commands/flinkStatements.ts, src/flinkSql/constants.ts, tests/e2e/specs/flinkStatement.spec.ts
From `.flinksql` to `.flink.sql` (leaving the `flinksql` language ID alone).
Closes #1663.
```shell
gulp clicktest
```
=> swap file extension used for Flink SQL documents

Gulpfile.js, src/graphql/sidecarGraphQL.d.ts
This file is automatically generated/updated by gql.tada based on: https://github.com/confluentinc/vscode/blob/8dafd000411968a8fb25dd097bfd74955579cf04/tsconfig.json#L13-L17
Formatting it will only cause gql.tada to undo the formatting and show (revert) changes whenever it decides to update that file, which causes unnecessary changes to show up in work branches.
=> MINOR: don't let `gulp format` affect `graphql/sidecarGraphQL.d.ts`

src/flinkStatementResultsManager.ts, src/webview/flink-statement-results.html, src/webview/flink-statement-results.ts
- Keeping pause/resume in the results viewer would do nothing but confuse the user into thinking they're able to pause the statement execution. This PR removes it.
-
```shell
gulp clicktest
```
=> Remove Pause/Resume and timer functionality from results viewer

src/chat/tools/listTemplates.ts, src/scaffold.test.ts, src/scaffold.ts
Adds sanitizeOptions to getTemplatesList so that we can return options without secret or key. 
Needed to help the `list_projectTemplates` tool so Copilot is completely unaware of any kind of `*secret*` or `*key*` input options. For now this is just handled by iterating through the options and string matching, but can be cleaned up when the templates provide an explicit property/flag like `is_sensitive` for easier filtering.
```shell
gulp clicktest
```
=> sanitize options: add param to getTemplatesList and test 

src/chat/messageTypes.ts, src/chat/participant.ts, src/chat/summarizers/chatHistory.ts, src/chat/summarizers/projectTemplate.ts, src/chat/tools/README.md, src/chat/tools/base.ts, src/chat/tools/listTemplates.ts, src/chat/tools/registration.ts, src/chat/tools/types.ts
While working on https://github.com/confluentinc/vscode/pull/1717 and its child branches, I noticed some concerning behavior with the tool calling flow where Copilot would be missing tool call results/references and having to repeat a lot of the same tool calls at each request. This was not ideal since it can drive up the token usage for some very simple tool chaining flows.
While debugging this behavior and poring over https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vscode/index.d.ts, I realized we were mixing a lot of the core types/interfaces while trying to convert tools' `LanguageModelTextPart`s into `User` messages.
This PR aims to address all of the above by:
- explicitly adding [tool call metadata](https://github.com/confluentinc/vscode/blob/b5c761d241359af8be9 …
=> refactor Copilot tool calling flow to enforce `LanguageModelToolResultPart` usage

package.json, src/chat/tools/createProject.ts, src/chat/tools/getTemplate.ts, src/chat/tools/listTemplates.ts, src/chat/tools/registration.ts, src/scaffold.ts
Follow-up to https://github.com/confluentinc/vscode/pull/1735 to take user-provided inputs (based on project template `options`) and pass them to `scaffoldProjectRequest()` to show the project generation form.
- Some additional changes were needed in `scaffold.ts` to clean up the telemetry source attribution as well as return the same kind of `{ success: boolean, message: string }` structure to help the tool result handling
- Similar to https://github.com/confluentinc/vscode/pull/1735, this also required adding a hint to the "parent" tool (`get_templateOptions`) to continue on and pass values into this `create_project` tool
Closes #1470 
```shell
gulp clicktest
```
=> feat(Copilot): add tool for applying project template and showing form

package.json, src/chat/participant.ts, src/chat/telemetry.test.ts, src/chat/telemetry.ts, src/chat/types.ts, src/extension.ts, src/preferences/constants.ts, src/telemetry/events.ts
This PR addresses two main telemetry asks under a new `Copilot Interaction` event:
- Handling user feedback via the 👍 / 👎 ([docs](https://code.visualstudio.com/api/extension-guides/chat#measuring-success)), which includes two new settings (in a dedicated section) to control how much data is being sent (error details, and tool calls/results)
- General usage events for requests, tool chaining iterations, and responses
Closes #1475
- Since the `ChatResult.metadata` [accepts arbitrary key/value pairs](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d2e940c81701bda35414024afa8751fa8deb1477/types/vscode/index.d.ts#L19496-L19509), I wanted to enforce expected fields by setting up a `CustomChatResult` interface so we didn't accidentally start passing arbitrary key/value pairs through: …
=> add Copilot chat participant telemetry and feedback integration

package.json, src/authn/constants.ts, src/chat/summarizers/README.md, src/chat/summarizers/connections.test.ts, src/chat/summarizers/connections.ts, src/chat/tools/getConnections.ts, src/chat/tools/listTemplates.ts, src/chat/tools/registration.ts, tests/unit/testResources/connection.ts
This is the first PR of a stack that will contribute basic context to Copilot, whether that's through the `@Confluent` chat participant or as tools for Agent mode.
We're also starting to get into some interactive elements for any inquiries about a specific connection type that may not be available:
Closes #1471 
- We need to figure out how to restructure some of the tool-invocation flow if/when we want to better integrate [chat output types](https://code.visualstudio.com/api/extension-guides/chat#supported-chat-response-output-types)
- Our current flow begins by sending the initial prompt and conversation context / message history in the main request, which will then either return a text or tool-call response. https://github.com/confluentinc/vscode/blob/a59c03275d34cce5411234f897c5c93ec9bb …
=> feat(Copilot): add tool for summarizing CCloud/local/direct connections

src/extension.ts, src/flinkSql/flinkConfigManager.test.ts, src/flinkSql/flinkLanguageClientManager.test.ts, src/flinkSql/flinkLanguageClientManager.ts, src/flinkSql/languageClient.ts
- Closes https://github.com/confluentinc/vscode/issues/1729 
- Refactors what was the "FlinkConfigManager" so that it is only responsible for the language client and handles the entire client lifecycle, so we can avoid hard-to-debug disconnect logic spread across the codebase 😁 
- Language Client file is simpler - it just initiates the client and handles logic specific to LSP messages, and server websocket  interactions.
- This is based on the prev branch `ncothren/flink-language-client`, PR open [here.](https://github.com/confluentinc/vscode/pull/1630)
```shell
gulp clicktest
```
=> Saner client instance management (Follow-up #1 for FlinkSQL language client)

src/models/flinkComputePool.test.ts, src/models/flinkComputePool.ts, src/models/kafkaCluster.test.ts, src/models/kafkaCluster.ts
- Include the cloud provider/region in CCloud  Kafka clusters and Flink compute pools `searchableText` so can be searched.
- Closes #1773
```shell
gulp clicktest
```
=> Include cloud provider/region in ccloud kafka clusterrs and flink compute pools searchable text

package.json, src/chat/constants.ts, src/chat/summarizers/connections.ts, src/chat/summarizers/environments.ts, src/chat/tools/getEnvironments.ts, src/chat/tools/registration.ts
Now that #1717 allows Copilot to look up CCloud/local/direct connections, the next layer down in our resource hierarchy is **environments**. Also, since we load Kafka/SR/Flink compute pool details at the time we construct environments ([CCloud](https://github.com/confluentinc/vscode/blob/473a85421c03ecd3cafc64f2243c5fbc1c3f2f25/src/graphql/environments.ts#L73-L126), [local](https://github.com/confluentinc/vscode/blob/473a85421c03ecd3cafc64f2243c5fbc1c3f2f25/src/graphql/local.ts#L71-L99), [direct](https://github.com/confluentinc/vscode/blob/473a85421c03ecd3cafc64f2243c5fbc1c3f2f25/src/graphql/direct.ts#L67-L104)), we shouldn't need explicit tooling to get names/IDs of those resources. (We may still want tools later that can look up _other_ properties for those "cluster"-likes, though.)
- …
=> feat(Copilot): add tool for listing environments and Kafka, Schema Registry, and Flink compute pool names & IDs

CHANGELOG.md, package-lock.json, package.json, src/extension.ts, src/flinkSql/flinkConfigManager.test.ts, src/flinkSql/flinkConfigManager.ts, src/flinkSql/flinkLanguageClientManager.test.ts, src/flinkSql/flinkLanguageClientManager.ts, src/flinkSql/languageClient.ts, src/flinkSql/websocketTransport.test.ts, src/flinkSql/websocketTransport.ts
- Adds intellisense features with a new ✨ Language Client ✨ that connects to Confluent Cloud's Flink Language Server via `ide-sidecar`'s websocket proxy
- Closes https://github.com/confluentinc/vscode/issues/1493
Just the initial setup and happy path here. 🌞 Full implementation to be done in separate PRs w/ remaining tasks listed in [this issue](https://github.com/confluentinc/vscode/issues/1401).
It currently maintains a single connection for all files, so depends on a single compute pool/region for now. Future work will allow it to make multiple connections for different regions.
- User Settings required: Flink features enabled, (valid) global compute pool id set
- Sign in to CCloud and open a file that is `flinksql` language. You should see completions from the CCloud service. 
Please …
=> Client for FlinkSQL language server

src/flinkStatementResultsManager.test.ts, src/flinkStatementResultsManager.ts, tests/createResultsManager.ts
- setInterval fires regardless of previous calls. This poses a problem with our `await`ed get results call because we could have out of order result changelog being processed. We fix it by adding a simple mutual exclusion on the fetchResults function.
- Closes #1787 
-
```shell
gulp clicktest
```
=> Fix changelog out-of-order parsing due to lack of mutual exclusion

src/flinkStatementResultsManager.test.ts, src/flinkStatementResultsManager.ts, tests/createResultsManager.ts
- setInterval fires regardless of previous calls. This poses a problem with our awaited get results call because we could have out of order result changelog being processed. We fix it by adding a simple mutual exclusion on the fetchResults function.
- Pulls patch  #1808  to v1.3.x forward into main.
-
```shell
gulp clicktest
```
=> [main] Fix changelog out-of-order parsing due to lack of mutual exclusion

src/models/flinkStatement.test.ts, src/models/flinkStatement.ts
- We recently changed `FlinkStatement.id` to return `name@env` instead of `name`. The "View in Confluent Cloud" URL constructed for statements then led to 404. 
- Fix was to swap with `name`.
-
```shell
gulp clicktest
```
=> Fix: Use statement name in FlinkStatement.ccloudUrl

src/extension.ts
- Comments out the line that initializes language client code. We are finding too many flaky errors and don't want to release with this UX. It will be reenabled shortly when we find the cause! 
-
```shell
gulp clicktest
```
=> Disable language client on activate (for now)

src/flinkStatementResultsManager.test.ts, src/flinkStatementResultsManager.ts
- As title
- Closes #1820
```shell
gulp clicktest
```
=> Harden results viewer: Increase num of retries to 60 with constant backoff of 500ms

src/quickpicks/utils/quickPickUtils.test.ts, src/quickpicks/utils/quickPickUtils.ts
Follow-up from https://github.com/confluentinc/vscode/pull/1272 to address https://github.com/confluentinc/vscode/pull/1272#discussion_r2047376234 and fix a syntax error. Also includes a new test and some additional test adjustments.
```shell
gulp clicktest
```
=> fix: quickpick followup

.semaphore/semaphore.yml, service.yml
- Set `main_branch: main` in the ServiceBot config for Sonarqube.
- Actually run the Sonarqube scan using the DevProd team provided script `emit-sonarqube-scan` -- only on Linux x64 (because that's where the epiloque YAML reference is set up and we only want to run the scan once).
- Hopefully resolves #933 
-
```shell
gulp clicktest
```
=> Run Sonarqube scan on Linux x64 and set `main_branch: main`

service.yml, sonar-project.properties
Fixes this error:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ProjectReactor' defined in org.sonar.scanner.scan.MutableProjectReactorProvider: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.sonar.api.batch.bootstrap.ProjectReactor]: Factory method 'provide' threw exception; nested exception is Wildcards ** and * are not supported in "sonar.sources" and "sonar.tests" properties. "sonar.sources" and "sonar.tests" properties support only comma separated list of directories. Use "sonar.exclusions/sonar.inclusions" and "sonar.test.exclusions/sonar.test.inclusions" to further filter files in "sonar.sources" and "sonar.tests" respectively. …
```
=> Remove wildcard from coverage sources

src/quickpicks/organizations.test.ts, src/quickpicks/organizations.ts
Mainly to use `QuickPickItemWithValue<CCloudOrganization>` objects instead of the base `QuickPickItem`.
```shell
gulp clicktest
```
=> chore: update `quickpicks/organizations.ts` and add tests

CHANGELOG.md, src/extension.ts
We got some Sentry reports that users were trying to use the "File Issue" button from notifications when the extension would fail to activate, which would then break since we hadn't yet registered those support commands (including downloading logs and the support .zip), so this PR ensures we register those commands much earlier in the process.
https://github.com/user-attachments/assets/2894c69e-b4ac-452d-ad95-a593bba5cc2e
Closes #1823.
```shell
gulp clicktest
```
=> fix: register support commands earlier in extension activation

src/chat/summarizers/dockerContainers.ts
Includes port information in summarizing logic. Ideally, this is what happens: 
But there are cases (when you ask it to generate a template without asking it to tell you about local docker first) that you may end up with it filling the template with the default local port first, then "realizing" its mistake, but there's no way to re-render a form so: 
addresses: #1842 
```shell
gulp clicktest
```
=> 1842: Update container tool summarizer to include port info

src/commands/schemas.test.ts, src/quickpicks/topics.test.ts, src/quickpicks/topics.ts, src/quickpicks/utils/schemaSubjects.test.ts, src/quickpicks/utils/schemas.test.ts, src/viewProviders/base.test.ts, src/viewProviders/flinkStatements.test.ts, tests/stubs/resourceLoaders.ts
Similar addition to `tests/stubs/` as https://github.com/confluentinc/vscode/pull/1858, but this time just for the various `ResourceLoader` instances. Tests should just have to call `getStubbed*ResourceLoader()` instead of having to set up the stubbed instances and also stub the `ResourceLoader.getInstance` call:
- Most test suites using ResourceLoader stubs were straightforward to update, but the `quickpicks/topics.test.ts` was somewhat hairy since it included a test that asserted the right loader was used based on the connection ID. That test was removed in favor of a standalone suite that used dedicated stubbed loader instances for each Kafka cluster type (CCloud, local, direct).
- While I was in there, I realized we didn't actually need to show any progress indicator on the Topics …
=> chore: add `ResourceLoader` stubbed instance helper functions

src/commands/flinkStatements.ts
If the content of a notification is too long, VS Code won't show it but will have a small badge/indicator in the notification section of the status bar. This PR limits the error details to 500 characters so longer errors aren't hidden.
=> MINOR fix: truncate the error content sent to the notification on statement submission

src/sidecar/connections/watcher.test.ts, src/sidecar/connections/watcher.ts
We want to get a better feel for how often users are encountering `FAILED` connection states with direct connections - in order to do that, this PR is pulling out any `sign_in` errors (see sidecar [Kafka](https://github.com/confluentinc/ide-sidecar/blob/2d770d3574b632f0c5367cb75df8d3b6fec31e20/src/main/java/io/confluent/idesidecar/restapi/connections/DirectConnectionState.java#L203-L208) and [SR](https://github.com/confluentinc/ide-sidecar/blob/2d770d3574b632f0c5367cb75df8d3b6fec31e20/src/main/java/io/confluent/idesidecar/restapi/connections/DirectConnectionState.java#L244-L249) handling) and including them in the `ConnectionSummary` interface to then forward on to Segment.
Samples:
```shell
gulp clicktest
```
=> telemetry: add `failedReason` to start aggregating common direct-connection failures

src/sidecar/logging.test.ts, src/sidecar/logging.ts, src/sidecar/sidecarManager.test.ts, src/sidecar/sidecarManager.ts, src/sidecar/types.ts, src/sidecar/utils.test.ts, src/sidecar/utils.ts, tests/fixtures/sidecarLogs/sidecar-glibc-death/vscode-confluent-sidecar.log.stderr
- Detect quick sidecar death due to missing GLIBC. Show a specific diagnostic to the user at startup.
- Closes #1698 
- Do some followup nits from the prior PR, namely:
-  Stop telling user to 'check logs for more details' when we're showing them an 'open logs' button already.
- Rename `divineSidecarStartupFailureReason()` (as in reading the tea leaves) to `determineSidecarStartupFailureReason()`.
- No need for second condition in `confirmSidecarProcessIsRunning()` if first one short-circuit returned.   
```shell
gulp clicktest
```
=> Check for glibc not found errors

src/flinkStatementResults.ts, src/flinkStatementResultsManager.test.ts, src/flinkStatementResultsManager.ts, src/webview/flink-statement-results.html, src/webview/flink-statement-results.ts
- Add a 'View Statement Source' button to the Flink results view. Drives the preëxising command to open the statement in a read-only buffer. If the statement sources was already being shown in a read-only buffer, will bring focus to it. The user is free to tear either the statement results or the statement source tab into a new window to view both side-side.
- Totally copied the HTML of the 'Stop' (statement execution) button. Am indifferent as to if this UI element should become a link, or its position in the 'page', or its styling. This here is FE-by-backend, and would be delighted to pass the last mile over to opinion and skill.
- Closes #1610 , more or less.
```shell
gulp clicktest
```
=> View sql statement from Flink statement results viewer

src/directConnectManager.ts, src/loaders/directResourceLoader.test.ts, src/loaders/directResourceLoader.ts, src/loaders/resourceLoader.ts
- Get each `DirectConnectionLoader` to cache its subset of the graphql results, so as to reduce the number of times we make the deep graphql fetch.
- When direct connections are updated (or, sigh, added or deleted), we pessimistically clear any cached data for existing direct connection loaders.
- Will improve performance / reduce deep graphql calls, both before and after migrating `DirectConnectionLoader` over to using single-connection-graphql query from https://github.com/confluentinc/ide-sidecar/issues/434.
- While here, new method to get at all of the `DirectConnectionLoader` instances registered in the `ResourceLoader` registry, `static ResourceLoader.directLoaders()`. There are probably a few places that want to call it, but now starting within `DirectConnectionManager`'s …
=> Direct resource loader cache

src/flinkSql/languageClient.ts, src/flinkSql/logging.ts
Dynamically created (possibly multiple, based on disconnects) regular `OutputChannel`s
Single output channel reused even between disconnects, uses the `LogOutputChannel` format for some syntax highlighting and support for compound-log creation.
=> MINOR: create single log output channel for Flink SQL language server

Gulpfile.js, tests/e2e/playwright.config.ts
Since most E2E tests require logging in to CCloud and handling the auth callback URI, having the same version of VS Code open (when running `gulp e2e`) can cause the URI handling to focus on the main window instead of the test window. (This causes a "do you want to install the Confluent extension" type prompt in the main window, while also causing the test window to never successfully log in and fail the tests, etc.)
This catches that behavior early on and shows an error message:
- `gulp e2e` from stable, testing stable ❌ 
- `gulp e2e` from insiders, testing insiders ❌
- `VSCODE_VERSION=stable gulp e2e` from insiders, testing stable ✅
- `VSCODE_VERSION=insiders gulp e2e` from stable, testing insiders ✅
=> cleanup(testing): prevent running E2E tests from VS Code terminal for same VS Code version being tested

package.json, src/extension.ts, src/extensionSettings/constants.ts, src/extensionSettings/listener.test.ts, src/extensionSettings/listener.ts, src/extensionSettings/sidecarSync.test.ts, src/flinkSql/flinkLanguageClientManager.ts, src/flinkSql/logging.ts, src/telemetry/events.ts
Add a new setting to control whether or not the Flink SQL language client/server integration is enabled:
https://github.com/user-attachments/assets/2b40e968-8adf-4537-8529-9246ef3ffc56
- This PR also lets the `FlinkLanguageClientManager` be in control of the "Confluent Flink SQL Language Server" output channel's lifecycle, so whenever it's disposed -- (which should only be on extension deactivation after this setting is removed) -- the output channel is disposed (and cleared in `src/flinkSql/logging.ts`)
- Special attention to the new user event enum value + comment for telemetry purposes: https://github.com/confluentinc/vscode/blob/e5fe565110e1fb52a74243d9f445bcced81f5ac9/src/telemetry/events.ts#L25-L31
```shell
gulp …
```
=> feat: add preview setting for enabling Flink SQL CCloud language server integration

package.json, src/commands/extra.ts, src/commands/search.test.ts, src/commands/search.ts, src/emitters.ts, src/extension.ts, src/viewProviders/base.test.ts, src/viewProviders/base.ts, src/viewProviders/flinkStatements.test.ts, src/viewProviders/flinkStatements.ts
Adds search functionality to the Flink Statements view similar to how it's handled in the Resources, Topics, and Schemas views.
https://github.com/user-attachments/assets/c26b76bd-d4cb-4643-8b00-c1e736c146e8
Closes #1407 
- This is the first use of the BaseViewProvider's search pattern, which required some slight adjustments to ensure we don't hit any race conditions (may have been related to https://github.com/confluentinc/vscode/issues/1977 ?), but overall it should reduce the amount of boilerplate needed to enable search for the Resources/Topics/Schemas view providers
- I moved all of the search-related commands to a dedicated `src/commands/search.ts` since `extra.ts` was getting too big. Easier for testing now, too. …
=> feat: enable search in the Flink Satements view

README.md
This change mentions that we do not yet support using private networking with Flink resources.
-
```shell
gulp clicktest
```
=> docs: Add private networking with Flink as known limitation [ci skip]

CHANGELOG.md, src/graphql/direct.test.ts, src/graphql/direct.ts, src/viewProviders/resources.ts
The main problem behind #1988 was a race condition between:
- the time we would see websocket events transitioning a connection from `ATTEMPTED` to a stable state (`SUCCESS`/`FAILED`)
- the time we started and got results back from GraphQL to populate the Resources view
Since the logs showed correct behavior from the websocket perspective, that hinted at problems either in the `ResourceViewProvider` and/or the handling of the [direct connection GraphQL query](https://github.com/confluentinc/vscode/blob/03c72ccca060525f45abad1b1afef52643ad96dd/src/graphql/direct.ts#L12). Since `ResourceViewProvider` is more of a middleman, the most focused fix appeared to be on the GraphQL side where we could look at the latest websocket events for a given connection and decide whether to proceed with the …
=> fix: block GraphQL queries for direct connections in `ATTEMPTING` states to prevent race condition

Gulpfile.js
We've occasionally hit local hiccups where we would kick off tests after a sidecar version bump without explicitly running `gulp build` (directly or from the extension dev [task](https://github.com/confluentinc/vscode/blob/50f1996a2e68714fd0cf5129d22b868c2cc28fe0/.vscode/tasks.json#L9) launching), which would then throw up a big angry error
No download/check, global beforeEach failure:
...
Downloads if necessary:
=> MINOR fix(local): download sidecar if necessary before tests start

.semaphore/semaphore.yml, Makefile
Instead of each job running `gulp test` and then `gulp functional`, this PR lets them run as separate jobs inside a single "tests" block (per agent). This reduces the total running time for a given block to 4-5min instead of 6-7 minutes. (Aside from Windows, which usually takes longer due to waiting for an available agent/runner.)
This also:
- updates some names for clarity (making it slightly easier to add E2E playwright tests)
- adds a `linux arm64` step to run against VS Code Insiders (helpful to compare against any failing tests in the `linux x64` VS Code stable block)
- adds `gulp check` and `gulp lint` its own block that has to pass before the tests kick off. (We don't want to waste resources if at least one more commit will be required for formatting, error correction, type fixes, …
=> chore(CI): split `test` and `functional` into separate jobs per block

Makefile
Follow-up to https://github.com/confluentinc/vscode/pull/2039 to shave off a small amount of work from the test blocks by just running `gulp build` instead of `gulp ci`:
https://github.com/confluentinc/vscode/blob/d94ca96d05356099f216aabfe26035637bdad2cd/Gulpfile.js#L35
(Likely won't save any time since `check` and `lint` are faster than `build`)
We don't need to run `gulp ci` here since the `gulp check`/`gulp lint` pieces are already covered in their own block:
https://github.com/confluentinc/vscode/blob/d94ca96d05356099f216aabfe26035637bdad2cd/.semaphore/semaphore.yml#L40-L46
=> MINOR: only `gulp build` in make `test*` targets

src/loaders/ccloudResourceLoader.test.ts, src/loaders/ccloudResourceLoader.ts, src/models/environment.ts, src/storage/resourceManager.test.ts, src/storage/resourceManager.ts
- Do for environment caching what was done for kafka clusters, schema registries --- remove the CCloud hard dependency.
- Closes #2063.
- Also round out a few additional tests so that `resourceManager.ts` test coverage is now:
- Reduce duplication between getting / setting environments, kafka clusters, schema registries. All of these share the same general structure, but vary by storage key determination function / result; the concrete resource type class lookup, and how to construct the concrete resource type (constructing an Environment is a little different than constructing the other two.) Model those differences then make interior private shared implementations. (#2063)
- Relax key restrictions to allow direct and local resources to be cached (#2065).
- Migrate coarse resource …
=> Generalize environment caching. Flesh out a few more test cases.

package-lock.json, package.json, tests/e2e/baseTest.ts, tests/e2e/playwright.config.ts, tests/e2e/specs/confluent.spec.ts, tests/e2e/specs/flinkStatement.spec.ts, tests/e2e/specs/schemas.spec.ts, tests/e2e/specs/utils/confluent.ts
This PR mainly sets up the `baseTest` module to handle all the lower-level E2E + Electron setup that was handled by https://github.com/ruifigueira/vscode-test-playwright.
`gulp e2e` from a terminal still works as intended to launch a VS Code (stable) window and run the tests like before. Bonus: each test isn't downloading a fresh copy of VS Code anymore. 🎉 
However, `VSCODE_VERSION=insiders gulp e2e` doesn't work quite right -- even though it launches a VS Code Insiders window for testing, the CCloud auth callback URI is still using the `vscode` scheme instead of `vscode-insiders`. I'm not too concerned about that for this PR since we aren't normally running these tests against Insiders anyway.
Also worth noting (for anyone that runs `gulp e2e` for this PR), some of the tests are …
=> cleanup(E2E): remove `vscode-test-playwright` dependency

src/flinkSql/flinkLanguageClientManager.ts, src/flinkSql/languageClient.ts, src/flinkSql/logging.ts, src/flinkSql/websocketTransport.ts
- Sets existing logs for the language client and related processes to `trace` level where appropriate, so they won't cause as much noise for end users
- Update `logger` names for easier filtering
- Additional and more verbose logging to better observe the client lifecycle
- Clarify and update doc blocks
- Potential improvement / bug fix? The cleanup handler call was duplicated during the reconnect flow and is [removed here](https://github.com/confluentinc/vscode/commit/58bf7a0dc56cbad9be1143ccae7e07668b0c4b7a). 
-
```shell
gulp clicktest
```
=> chore: more language client logs

tests/e2e/baseTest.ts
Follow-up from https://github.com/confluentinc/vscode/pull/2077 where we were incorrectly pointing at the `vscode/` directory for the extension dev path instead of `vscode/out/`, which caused a bunch of errors loading webview files (and then caused more test failures since the locators couldn't find the specified elements).
(I have no idea why the theme color changed between the two.)
=> MINOR fix(E2E): adjust extension dev path for webviews

src/authn/ccloudProvider.ts, src/extension.ts
Same as https://github.com/confluentinc/vscode/pull/2093, but against `v1.4.x` to go out in the next patch release.
=> [v1.4.x] remove CCloud email from LaunchDarkly client identify calls

src/flinkSql/languageClient.ts
- While digging through language server logs I noticed some warnings like this: `jsonrpc2: code -32601 message: method not supported: workspace/didChangeWatchedFiles`
- These methods are sent if the client library's synchronize option is set, but aren't necessary for the language server features we are using. I'm **removing it to reduce the log noise.** 
- Similar log warnings are showing for `textDocument/didClose`. It would be a bit more lift to remove this call (it always gets sent from language client lib), so I'm leaving it. 
```shell
gulp clicktest
```
=> minor: remove synchronize option

src/flinkSql/languageClient.test.ts, src/flinkSql/languageClient.ts
- Closes https://github.com/confluentinc/vscode/issues/1814
- Logic for handling backticks added by the server moves to `sendRequest` to get ahead of other manipulations in the `languageclient/node` library -- see description on https://github.com/confluentinc/vscode/pull/2107 for similar moves that ***should be merged before this one***
- Now we check the document's completion range & avoid removing filters if the editor document does actually have them. 
- See [linked issue](https://github.com/confluentinc/vscode/issues/1814) for more details. In `languageClient.ts`, in the middleware for `provideCompletionItem` we were already doing some special handling for backticks added by the server to avoid vscode filtering out completions, but it wasn't working quite right. 
- Note: we don't …
=> fix: avoid backticks filtering out completion items from vscode UI

src/flinkSql/flinkLanguageClientManager.test.ts, src/flinkSql/flinkLanguageClientManager.ts
- Closes https://github.com/confluentinc/vscode/issues/2002
- These values are returned as-is in diagnostics messages, so it's a better UX with the names. 
-
```shell
gulp clicktest
```
=> Lookup & use names instead of ids for language server workspace settings

CHANGELOG.md, package.json, src/commands/topics.test.ts, src/commands/topics.ts, src/graphql/ccloud.test.ts, src/graphql/ccloud.ts, src/loaders/loaderUtils.ts, src/models/kafkaCluster.ts, src/models/topic.test.ts, src/models/topic.ts
- Add "Query with Flink" option to the context menu when right-clicked on a Confluent Cloud topic.
- A new editor tab will open, with language mode set to Flink SQL, and prepopulated with a default `SELECT *` query
```shell
gulp clicktest
```
=> Support query topic with Flink via context menu

src/flinkSql/flinkLanguageClientManager.ts, src/flinkSql/languageClient.ts
- Closes #1776 
- The language server backend will intermittently fail to send the expected `publishDiagnostics` message, so in this PR we add code to manually clear out diagnostics when the doc changes, avoiding showing any outdated error messages in the UI. 
- A similar workaround is in place for CCloud UI
- **To Test** 
- Make sure the language client flag is enabled, you're logged into CCloud, and you have an open `flink.sql` document.
- Write an invalid statement & pause until you observe the diagnostics error. 
- Add/change the doc. Expectation: the error disappears. (Before this change, the error would not get cleared even if you corrected it in the doc)
```shell
gulp clicktest
```
=> fix: preemptively clear outdated language client diagnostics

src/flinkSql/flinkLanguageClientManager.test.ts, src/flinkSql/flinkLanguageClientManager.ts
Adds a few more scenarios that we need to pay attention to so the language server can try to start anytime we have a flink doc open: 
1. If a flink document is already opened and you are already authenticated with CCloud, the language server should try to start. Closes https://github.com/confluentinc/vscode/issues/1725 
1. If the active document language changes to flinksql, the language server should try to start. Closes https://github.com/confluentinc/vscode/issues/2003
-
```shell
gulp clicktest
```
=> Language server - handle more "maybe start" scenarios

src/authn/ccloudStateHandling.ts, src/utils/privateNetworking.test.ts, src/utils/privateNetworking.ts
Follow-up from https://github.com/confluentinc/vscode/pull/2127#discussion_r2178708460:
> This hasn't actually been used since before this repo went public. Back in the early prototype days, this was used for a test that was deleted back in PR 463 (in the old repo). Nothing uses it now.
```shell
gulp clicktest
```
=> MINOR: remove old `openExternal` function

src/flinkStatementResultsManager.test.ts, src/loaders/ccloudResourceLoader.test.ts, src/quickpicks/uris.ts, tests/createResultsManager.ts, tests/e2e/objects/editor/TextDocument.ts, tests/e2e/objects/quickInputs/InputBox.ts, tests/e2e/objects/quickInputs/Quickpick.ts, tests/e2e/objects/views/ResourcesView.ts, tests/e2e/objects/views/SchemasView.ts, tests/e2e/objects/views/viewItems/SubjectItem.ts, tests/e2e/specs/flinkStatement.spec.ts, tests/e2e/specs/schemas.spec.ts, tests/e2e/specs/topicMessageViewer.spec.ts, tests/e2e/utils/commands.ts, tests/e2e/utils/settings.ts, tests/fixtures/schemas/customer.json, tests/fixtures/schemas/customer.proto, tests/fixtures/schemas/customer_bad_evolution.avsc, tests/fixtures/schemas/customer_bad_evolution.json, tests/fixtures/schemas/customer_bad_evolution.proto, tests/fixtures/schemas/customer_good_evolution.json, tests/fixtures/schemas/customer_good_evolution.proto, tests/fixtures/utils.ts
Partially a fix to update the schema/subject deletion behavior that changed in https://github.com/confluentinc/vscode/pull/2027, but turned into some more general cleanup and refactoring of existing tests to be less flaky, use (some existing, some new) page object models, and expand coverage to include JSON and protobuf schemas.
Now we have:
- AVRO vs JSON vs PROTOBUF schema types
- CCLOUD vs DIRECT connection types
- test scenarios:
- basic schema upload and subject creation
- happy path: schema evolution with existing subject, adding new schema version
- unhappy path: invalid schema evolution with error notification, no new schema version
Closes #2080
- The `loadFixture` utility function was renamed and repurposed to return the string contents of a file so we could use it with `.proto` …
=> fix schema evolution E2E tests

src/flinkSql/flinkLanguageClientManager.test.ts, src/flinkSql/flinkLanguageClientManager.ts
Fixes an issue where the outdated diagnostics would not always be cleared for document changes.
- Adds document tracking so that we can match URIs to changes in the listener
- Adds a mutex for initializing the language client so that multiple listeners can't call init at the same time -- we never want more than one client instance.
- This issue had two underlying causes:
- First, we were previously comparing the `onchange` document event URI to the uri that's saved when we start the client, to decide whether to clear. Of course this doesn't work for subsequent docs using the same client connection. 🤦 
- Second, sometimes the listeners calling `maybeStart...` could get in a race condition, attempting to initialize the client within milliseconds of each other and thereby bypassing the …
=> fix: flink sql diagnostics should clear on changes

src/flinkSql/flinkLanguageClientManager.test.ts, src/flinkSql/flinkLanguageClientManager.ts
- Fixes an issue found during bug bash - if a flinksql doc is already opened when you sign in to CCloud, the language server does not start automatically. 
- Builds on previous branch which added document tracking
```shell
gulp clicktest
```
=> fix: check for open flink docs in ccloud connected event

src/flinkSql/flinkLanguageClientManager.test.ts, src/flinkSql/flinkLanguageClientManager.ts
- Adds a timeout with callback when the last tracked document closes; it will automatically close the FlinkSQL Language Client websocket and cleanup the language client. 
- We know that the server and the load balancers auto-close inactive sockets, so with this we're preemptively closing it to avoid any issues and to not waste resources with idle connections. 
- ⚠️ Based on https://github.com/confluentinc/vscode/pull/2150, which was based on  https://github.com/confluentinc/vscode/pull/2145
```shell
gulp clicktest
```
=> task: set a timer and cleanup when all docs closed

src/commands/connections.test.ts, src/commands/connections.ts
This was really a one-line change, where our `ccloudSignOut` command (from the Resources view > "Confluent Cloud" item):
https://github.com/confluentinc/vscode/blob/7a140245adfca83865f7e128f9258577d9f33fa5/src/commands/connections.ts#L72-L73
...needed to behave the same as the auth provider (signing out from the Accounts menu):
https://github.com/confluentinc/vscode/blob/7a140245adfca83865f7e128f9258577d9f33fa5/src/authn/ccloudProvider.ts#L345-L350
This wasn't a problem before https://github.com/confluentinc/vscode/pull/2127 since we didn't depend as much on connected state transitions from `SUCCESS` to `NONE`, which was the cause of the (incorrect) expiration notification.
Closes #2165.
To click-test, compare notifications that appear when signing in and out multiple times between `main` …
=> [v1.5.x] clear CCloud connected state from sign-out command to prevent incorrect CCloud expiration notification

src/commands/connections.test.ts, src/commands/connections.ts
https://github.com/confluentinc/vscode/pull/2166 to main
=> [main] clear CCloud connected state from sign-out command to prevent incorrect CCloud expiration notification

src/authn/ccloudProvider.test.ts, src/authn/ccloudProvider.ts, src/sidecar/logging.ts
We want to get more real-time alerting when multiple users experience failures when authenticating to CCloud via the browser-based auth flow in the extension, so this PR sets up an additional event to send to Sentry when we get the `success=false` URI callback (when users see "Confluent Cloud authentication failed. See browser for details."). This will allow our team to quickly focus on triaging to see if there was a regression or external change that we need to address. 
Sample Sentry event data:
```shell
gulp clicktest
```
=> [v1.5.x] send CCloud auth failed events to Sentry

src/webview/scaffold-form.ts
- Fixes #2168 
- We found that users could submit invalid (pattern mismatched) values from the project generation form if using the `Enter` key to submit the form. This adds an extra validation check for each input just before submission to prevent that.
- In investigation I asked myself why `form.checkValidity()` wasn't working in this case, and realized it's because the RegEx patterns are _not_ added as input `attr` in the HTML form, instead checked explicitly on blur. 
- Then I had to go back to my notes from January to remember _why_ I did that: Seems that the JS RegEx interprets the unicode sets in [HTML with the `/v` flag](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input#pattern), which is different than the the backend Scaffold Service's template …
=> scaffold: catch pattern mismatches when submitted with keyboard

.gitignore, .semaphore/semaphore.yml, Makefile, mk-files/semaphore.mk, playwright.config.ts, src/extension.ts, tests/e2e/baseTest.ts, tests/e2e/playwright.config.ts, tests/e2e/specs/confluent.spec.ts, tests/e2e/tags.ts
- Basic setup for [test tags](https://playwright.dev/docs/test-annotations#tag-tests)
- Standalone CI step to run on linux amd64/arm64 agents for the `@smoke`-tagged "activate the extension" E2E test
Sample failure on activation where the "Confluent Cloud" item (in the Resources view) never appeared:
This also sets up the make target and some basic structure to help with running more E2E tests in CI (see https://github.com/confluentinc/vscode/pull/2163).
- I realized our test-publishing in Semaphore only applied to the Mocha tests, so this branch adds pushing test results from the `functional` and `e2e` tests as well
```shell
gulp clicktest
```
=> run E2E smoke test(s) in CI

src/telemetry/sentryClient.ts
- To prevent overwhelming our Sentry account with repetitive errors, add rate limiting for events sent by a single instance. 
- Caps the number of error events with the same message to one per minute by saving the message in `throttledEvents`, with a handler in `beforeSend`
- Still logs that rate limiting has occurred & surfaces errors to output logger
- Closes #1174 
- TIL that [Sentry uses a dynamic algorithm to detect spikes](https://docs.sentry.io/pricing/quotas/spike-protection/#how-sentry-detects-spikes), so the number of errors that will cause a spike aren't set in stone. 
- When a spike happens we get an On Call Slack channel alert, but sometimes there's no action that can be taken (it could be on the user's machine and unrelated to us). We've seen this happen a few times over the …
=> Sentry client: add rate limiting to prevent single-user spikes

.vscode-test.js, Gulpfile.js, src/testing.ts
- updates our `.vscode-test.js` to use Mocha configs similar to [testing.ts](https://github.com/confluentinc/vscode/blob/3e75e714b820d110b957835c919a37897f91254b/src/testing.ts#L15-L19) (but no CI timeout since we can only run it locally) and [Gulpfile.ts](https://github.com/confluentinc/vscode/blob/3e75e714b820d110b957835c919a37897f91254b/Gulpfile.js#L679-L688)
- adjusts our test reporting so we always create a coverage report (and show it) even if tests fail
=> chore: updates for test coverage and using Extension Test Runner

src/directConnect.ts
- Closes #2189 which exposed two issues:
1. With the dispose call happening _after_ the `await window.showInfoNotificationWithButtons...`, the form wouldn't close after saving unless/until the user responded to the window notification. **Solution**: Move dispose call ahead of the line. 
2. The handler/listener for closing the form when a connection is deleted should not be invoked for New connections, including the Imported ones. **Solution**: Check for "update" action before creating `connectionChangesListener`
-
```shell
gulp clicktest
```
=> fix: connections form not closing after save + falsely reporting "disconnected"

src/webview/direct-connect-form.html, src/webview/direct-connect-form.spec.ts, src/webview/direct-connect-form.ts
- Update to use dynamic `options` for Kafka cluster auth type so that we can control which are available based on platform type selected. (note: schema registry already has limited auth options, those are staying the same)
- Add logic to check which auth types are valid for a given platform (CCloud, Warpstream have limitations) and only allow those options for the user. 
| If CCloud, limited auth types | If WarpStream, limited auth types |
| -- | -- |
| <img width="288" height="335" alt="Screenshot 2025-07-22 at 8 23 23 AM" src="https://github.com/user-attachments/assets/66ecf166-f837-4f8c-8a44-4ab8ee9ca599" /> | <img width="329" height="304" alt="Screenshot 2025-07-22 at 8 23 07 AM" src="https://github.com/user-attachments/assets/4e431f47-ec8e-47af-82fd-67936a4bdbc1" /> |
- This is the …
=> direct connections form: validate auth types

src/webview/auth-credentials.ts, src/webview/direct-connect-form.html, src/webview/direct-connect-form.spec.ts, src/webview/direct-connect-form.ts
- Closes https://github.com/confluentinc/vscode/issues/1255. 
- Built on https://github.com/confluentinc/vscode/pull/1413 
| WarpStream SCRAM only allows SHA 512 |
| -- |
| <img width="317" height="347" alt="Screenshot 2025-07-22 at 8 24 05 AM" src="https://github.com/user-attachments/assets/d2f11fdf-826a-4c4b-aa8d-c0e2c8637008" /> |
- ⚠️ Caveat: with this change, users with existing warpstream connections that have set sha 256 will be forced to update the sha type if they edit. This is a good thing. And hopefully this is extremely rare as that combo was never supported and won't work anyways. 
```shell
gulp clicktest
```
=> Enforce sha 512 for warpstream scram connections

src/webview/direct-connect-form.spec.ts, src/webview/direct-connect-form.ts
- Set SSL enabled to `false` if user types in localhost for bootstrap server or SR uri. The user can still change it back to enabled if they really want to....
- Closes #2018 
-
```shell
gulp clicktest
```
=> direct connections form: if localhost, uncheck ssl by default

src/webview/direct-connect-form.spec.ts, src/webview/direct-connect-form.ts
- Closes #1415 
- If the user types in `http:` we know the are not using ssl, and if they type `https:` we know they are, so we can be smart about checking the box to enable or not. 
- Doesn't prevent users from clicking the box again to revert our helpful change. But they shouldn't do that. Bad user. 
- Built on https://github.com/confluentinc/vscode/pull/2217 must merge that first
```shell
gulp clicktest
```
=> direct connections form: check connection urls for ssl enabled

.semaphore/prerelease-multi-arch-packaging.yml, Gulpfile.js, Makefile, service.yml
We're adding a (manual, for now) Semaphore task to allow building prerelease .vsix files for our supported `vsce` targets:
This requires the [GitHub (pre-release) Release](https://github.com/confluentinc/vscode/releases/tag/v1.6.0-pre) to already be available (done from a separate task) beforehand.
For now, each of these steps is manual until we're comfortable enough with the flow to start scheduling them (delete existing prerelease, create new prerelease, build vsix files for prerelease).
Closes #1697
=> chore: add Semaphore task for uploading pre-release .vsix files to GitHub

sonar-project.properties
Mainly to match the same behavior we see via `gulp test --coverage`: 
https://github.com/confluentinc/vscode/blob/8468f8419d03699bb3b1e9bd7a630d2e29588800/Gulpfile.js#L632-L636
With some extras since sonarqube is looking at all of `src/` instead of just the files that are part of our Gulp (test)build processes:
- we didn't need to exclude anything that wasn't under `src/` since we set `sonar.sources=src`, which removes the need to exclude things like `node_modules/` and `tests/`
- `sonar.typescript.coverage.reportPaths` wasn't valid and didn't actually do anything, and [`sonar.javascript.lcov.reportPaths`](https://docs.sonarsource.com/sonarqube-server/latest/analyzing-source-code/test-coverage/test-coverage-parameters/#javaScript-typeScript) handles what we need
=> chore: fix `sonar-project.properties` exclusions

CHANGELOG.md, package.json, src/commands/environments.test.ts, src/commands/environments.ts, src/extensionSettings/constants.ts, src/extensionSettings/listener.test.ts, src/extensionSettings/listener.ts, src/extensionSettings/sidecarSync.test.ts, src/extensionSettings/sidecarSync.ts, src/sidecar/constants.ts, src/sidecar/sidecarHandle.ts
Added:
- New command to set private network endpoint(s) for a CCloud environment
- ...which updates a (new) setting `confluent.cloud.privateNetworkEndpoints`
This configuration is sent to the sidecar to update the preferences API changes introduced in https://github.com/confluentinc/ide-sidecar/pull/472.
- Added tests over `setFlinkStatementsEnvironmentCommand()` as well to get >90% coverage on `commands/environments.ts`
```shell
gulp clicktest
```
=> add CCloud private network settings

.semaphore/prerelease-multi-arch-packaging.yml, service.yml
Follow-up to https://github.com/confluentinc/vscode/pull/2226 where we set up a daily task to package and upload .vsix files based off the latest commit to `main` to a GitHub prerelease matching [`.versions/next.txt`](https://github.com/confluentinc/vscode/blob/main/.versions/next.txt). (GitHub prereleases will be created through a separate process outside of this repository.)
Sample run: https://semaphore.ci.confluent.io/workflows/b883aea6-b920-487c-90c2-5f265b0fb9d3
> [!NOTE]
> We'll still have to use the manual `prerelease-multi-arch-packaging` task for generating prereleases for a release branch.
=> chore(CI): set up scheduled prerelease vsixes

src/viewProviders/flinkStatements.test.ts, src/viewProviders/newResources.test.ts, src/viewProviders/newResources.ts, src/viewProviders/schemas.test.ts, src/viewProviders/topics.test.ts
- Bring NewResourceViewProvider event handler registration tests up to speed with technology created in #2254.
- While here, also prove that the event registration method returns the tested-number of event handlers, otherwise when we go and add more event handlers into these, their wiring may go untested. This change will now force a test fail in that case.
```shell
gulp clicktest
```
=> Bring new view controller event handler tests up to speed; write one more event handler-related test across the view controller family.

package.json
change the package.json to use `enablement` instead of `when`
-
```shell
gulp clicktest
```
=> MINOR: remove upload udf availability on main

src/directConnectManager.ts, src/directConnections/utils.test.ts, src/directConnections/utils.ts, src/graphql/direct.ts, src/sidecar/connections/watcher.test.ts, src/sidecar/connections/watcher.ts, tests/unit/testResources/connection.ts
New helper function [`hasCCloudDomain()`](https://github.com/confluentinc/vscode/blob/b9d2f6de7033ff08497d9f962f4faf9ea9859742/src/directConnections/utils.ts#L10-L14) to check a Kafka cluster config's `bootstrap_servers` or a Schema Registry config's `uri` to see if they contain the `.confluent.cloud` substring. If so, we'll add a new boolean value to associated direct connection telemetry events:
Closes #2280. (I opted for a more generic `hasCCloudDomain` to capture "Kafka OR Schema Registry" instead of a definitive `isCCloud` which may only apply to half of the connection configs if a user is pointing at CCloud Kafka and some other SR, or vice versa.)
```shell
gulp clicktest
```
=> telemetry: add `hasCCloudDomain` to 'Direct Connection Action' events

.semaphore/prerelease-multi-arch-packaging.yml, service.yml
Necessary for building prerelease .vsix files for a non-`main` branch.
Sample workflow: https://semaphore.ci.confluent.io/workflows/b1df16dd-23a6-4e9e-a1b8-89e52371d5d1?pipeline_id=39ce1b40-120d-4651-8ed9-a0074d02d9ff
Sample prerelease: https://github.com/confluentinc/vscode/releases/tag/v1.5.1-pre
=> fix(CI): add `TARGET_BRANCH` param to prerelease task

src/flinkSql/flinkStatementManager.test.ts, src/flinkSql/flinkStatementManager.ts
- Refactor `FlinkStatementManager` event handlers to be consistent with current standard design (registering top-level bound methods, using `setEventListeners` to perform the registration), increase test coverage.
- Now 100% lines covered.
```shell
gulp clicktest
```
=> Refactor FlinkStatementManager event handlers

src/flinkSql/flinkLanguageClientManager.ts
This change makes sure we always reinitialize the language client after a reconnect to the remote language server. It should fix cases where an idle disconnect does not lead to timely reconnects.
Fixes #2273 
```shell
gulp clicktest
```
=> fix: Force reinitialization of language client after WebSocket reconnect

src/flinkSql/flinkLanguageClientManager.test.ts, src/flinkSql/flinkLanguageClientManager.ts
- Bring https://github.com/confluentinc/vscode/pull/2344 forward from v1.5.x branch into main.
- Revise the existing test coverage over `onDidChangeTextDocumentHandler` making the call into clearDiagnostics() via `clearDiagnostics`'s side effects., generalizing the FakeDiagnosticsCollection concept in the process for future reuse in future tests.
- There's no test coverage (yet) over `maybeStartLanguageClient()` (and therefore also its new call into `clearDiagnostics()`). That's a big enough effort to warrant its own issue, and not this merge forward into main.
- Closes #2338 in main.
```shell
gulp clicktest
```
=> Bring PR-2344 forward from v1.5.x branch into main.

src/flinkSql/flinkLanguageClientManager.ts
🍒 https://github.com/confluentinc/vscode/pull/2341 from `1.5.x` branch
This change makes sure we always reinitialize the language client after a reconnect to the remote language server. It should fix cases where an idle disconnect does not lead to timely reconnects.
Fixes #2273
We'll implement unit tests in a follow-up PR; captured in https://github.com/confluentinc/vscode/issues/2346.
```shell
gulp clicktest
```
=> 🍒 1.5.x -> main: Force reinitialization of language client after WebSocket reconnect

src/flinkSql/flinkLanguageClientManager.test.ts, src/flinkSql/flinkLanguageClientManager.ts
- https://github.com/confluentinc/vscode/pull/2354 closes #2350
- https://github.com/confluentinc/vscode/pull/2348 closes #2343
- https://github.com/confluentinc/vscode/pull/2353 closes #2349
=> [main] pull in fixes from `v1.5.x`

package.json
This reverts commit 3ce9cf8f282342418762ca27bc6565cabd409daf to remove the preview label/flag from the Flink features in the upcoming 1.5.2 patch release.
-
```shell
gulp clicktest
```
=> Revert "Jlr/reinstate preview declaration (#2302)"

package.json, src/viewProviders/newResources.test.ts
- Fix for the command invocation wiring for currently-disconnected direct connection rows in the Resources view when populated by the new resources provider.
- Command wiring fix was that the regular expression was expecting a trailing '-' in the row's context value when not connected, but there won't be one. So, simplify the regular expression and remove the trailing dash.
- Write some additional tests over `DirectConnection` row vs `getTreeItem()` for clarity for the future.
- Closes #2289
- Without this fix, the commands would be invokable from currently-connected status DirectConnection rows, just not the currently-disconnected ones.
- Now both show the expected edit/export/delete command icons (The "a-main-test-kafka-cluster shadow" connection is in disconnected state right now, …
=> Fix for edit/delete/export direct connection command wiring for new resources provider when connection is 'not connected'

src/logging.test.ts
- Adds test coverage over changes associated with #2334 and #2362.
- Next steps are to refactor existing Logger class and logging methods to use new classes
- Update test coverage of Logger from associated changes
```shell
gulp clicktest
```
=> Add test coverage for new classes that save output logs

src/flinkSql/flinkLanguageClientManager.test.ts, src/flinkSql/flinkLanguageClientManager.ts
- Simplify `validateFlinkSettings()`, then fix its test suite to cover the right cases and use the right stub.
- Closes #2373
```shell
gulp clicktest
```
=> Simplify validateFlinkSettings(), then fix its test suite 

package.json, src/commands/flinkArtifacts.ts, src/commands/flinkUDFs.ts, src/context/values.ts, src/emitters.ts, src/extension.ts, src/models/flinkUDF.ts, src/viewProviders/baseModels/multiViewBase.test.ts, src/viewProviders/baseModels/multiViewBase.ts, src/viewProviders/flinkArtifacts.test.ts, src/viewProviders/flinkArtifacts.ts, src/viewProviders/multiViewDelegates/constants.ts, src/viewProviders/multiViewDelegates/flinkArtifactsDelegate.test.ts, src/viewProviders/multiViewDelegates/flinkArtifactsDelegate.ts, src/viewProviders/multiViewDelegates/flinkUDFsDelegate.test.ts, src/viewProviders/multiViewDelegates/flinkUDFsDelegate.ts
Continuation of https://github.com/confluentinc/vscode/pull/2243, but with reusable `MultiModeViewProvider` and `ViewProviderDelegate` classes to switch between "Flink Artifacts" and "Flink UDFs" modes in the single `confluent-flink-artifacts` view.
https://github.com/user-attachments/assets/47113860-301a-44d7-a728-c55ace7fe1d5
- The current action-toggling behavior works fine for two view modes, but we'll need to explore better UI/UX if a view needs three modes. Cycling through them would be clunky, but a quickpick may feel like overkill.
- I don't like the `FlinkArtifactsUDFs*` naming pattern, but can't come up with anything better at the moment without it being too vague
```shell
gulp clicktest
```
=> feat: add multi-mode view for Flink Artifacts/UDFs

src/directConnect.test.ts, src/directConnect.ts, src/webview/direct-connect-form.html, src/webview/direct-connect-form.spec.ts, src/webview/direct-connect-form.ts, tests/e2e/objects/webviews/DirectConnectionFormWebview.ts
- Closes #2444. Details in issue report
It's two underlying issues; fixes are in separate commits to help with review. (When filed we weren't sure if the issues were related but I found they were not.)
1. Connection type (aka platformType) was not saved in the form when the user left the window in background and came back. It was because the html field had been respelled with all lowercase while the js stayed camel case, so the field's string name was not passing strict equality to re-populate. Simple re-write to all camel case to avoid this, but required changing a lot of files.  
2. The auth type was not updated to a valid type when user changed the platform to CCloud, so the auth component would not show the fields at first. Now we'll check for a valid auth type when the user updates …
=> Direct Connections form bug fixes

src/webview/direct-connect-form.ts
This change makes sure we pass the new/updated platform type when checking the valid Kafka auth types, so that the credential-related form fields show up correctly after switching the connection type to, for instance, "Confluent Cloud".
Fixes #2463
-
```shell
gulp clicktest
```
=> [v1.6.x] fix: Credential fields don't show up after switching connection type

src/docker/containers.test.ts, src/docker/containers.ts, src/docker/eventListener.test.ts, src/docker/eventListener.ts, src/docker/workflows/base.test.ts, src/docker/workflows/base.ts, src/docker/workflows/confluent-local.ts, src/docker/workflows/cp-schema-registry.test.ts, src/docker/workflows/cp-schema-registry.ts, src/docker/workflows/medusa.test.ts, src/docker/workflows/medusa.ts
This PR cleans up how we check if Schema Registry and Medusa containers are ready by switching from watching logs to using proper health checks in a unified workflow. Kafka still uses the old log-watching method - we'll move that to its own 'waitForReadiness' implementation later to keep this PR from getting too big.
Closes #2442 
=> 2442 refactor local kafka and schema registry containers to follow new readiness pattern

package.json, src/extensionSettings/constants.ts
Mainly to follow expectations of "experimental" vs "preview" settings per VS Code [docs](https://code.visualstudio.com/docs/configure/settings#_feature-lifecycle)
=> [v1.6.x] MINOR: update "Use New Resources View Provider" setting's id, description, tag

src/commands/topics.test.ts, src/commands/topics.ts, src/viewProviders/baseModels/parentedBase.test.ts, src/viewProviders/baseModels/parentedBase.ts, src/viewProviders/flinkStatements.test.ts, src/viewProviders/flinkStatements.ts, src/viewProviders/schemas.ts, src/viewProviders/topics.ts
- Remove `environment` property from `SchemasViewProvider`, `TopicViewProviderData`, and `ParentedBaseViewProvider` 
- Update `queryTopicWithFlink()` in topics command to directly get environment and clusters using `CCloudResourceLoader` instead of from`TopicViewProviderData`. 
- Update tests for `queryTopicWithFlink()` using `getStubbedCCloudResourceLoader`
- Fix: #2504 
```shell
gulp clicktest
```
=> Remove `environment` property from `SchemasViewProvider`, `TopicViewProviderData`, and `ParentedBaseViewProvider`

.semaphore/multi-arch-packaging.yml
Just like https://github.com/confluentinc/vscode/blob/main/.semaphore/prerelease-multi-arch-packaging.yml, consolidate to a single agent with parallelized jobs based on our supported targets, which speeds up overall packaging time since we don't need to wait for different agents to spin up:
https://semaphore.ci.confluent.io/workflows/4a9fb6ee-eb83-47be-b1d4-e54f75295fe4/artifacts?path=packaged-vsix-files
Closes #1282
=> refactor multi-arch-packaging promotion to run on single agent 

src/commands/flinkArtifacts.test.ts, src/loaders/ccloudResourceLoader.ts, src/models/flinkArtifact.test.ts, src/models/flinkArtifact.ts, src/models/main.ts, tests/unit/testResources/flinkArtifact.ts
- Added more detailed information to Flink artifact tooltips
- Updated tooltip structure: to use `CustomMarkdownString.resourceTooltip` 
- Added optional argument for `CustomMarkdownString.resourceTooltip` to customize second external link for artifact documentation
- Fixes #2457 
After:
https://github.com/user-attachments/assets/a65ff621-3572-4c3d-af4a-0710f7c01250
```shell
gulp clicktest
```
=> Expand tooltip for flink artifacts

package.json
- Closes #2477
- Adds an icon to the Upload Artifact command, and makes it visible in the header of the Artifacts view if the user is connected to CCloud and `enableFlinkArtifacts` is true in the config.  
- I also renamed the title since the "Confluent: " prefix is redundant in the places where this appears. 
- In future work we could link this upload command to the currently selected compute pool when one is selected in the view, or we could at least put it higher in the list (see also #2458).  For now it asks the user to choose a compute pool each time. 
- No new tests required - this is not new functionality, just an icon and link in view header to existing command. 
```shell
gulp clicktest
```
=> #2477 add upload icon to invoke command from artifacts view header

src/models/environment.ts, src/models/flinkArtifact.ts, src/models/flinkComputePool.test.ts, src/models/flinkComputePool.ts, src/models/flinkStatement.ts, src/models/kafkaCluster.ts, src/models/main.test.ts, src/models/main.ts, src/models/schema.ts, src/models/schemaRegistry.ts, src/models/topic.ts, src/viewProviders/newResources.test.ts
- Removed `CustomMarkdownString.resourceTooltip()` and simplified into sub methods for more flexible field customization of tooltips while still maintaining a  general defined structure of:
1. **Header** - Resource type with icon
2. **Fields** - Key-value pairs for resource properties
3. **Warnings** - Error/warning messages (if any)
4. **Links** - External links and Confluent Cloud links (if any)
- Updated outdated tooltip markdown generation in `flinkComputePool`, `environment`, `kafkaCluster`, `schema`, `schemaRegistry`, `topic` to new methods
```
---
Field Name: `value`
Another Field: `value`
---
$(warning/error) Warning message
---
$(warning/error) Another warning
---
[Custom Link](url)
---
[(confluent-logo) Open in Confluent Cloud](ccloud-url)
```
- Fixes #2524
Please check if your …
=> Update tooltip markdown generation

package.json, src/commands/uris.test.ts, src/commands/uris.ts, src/context/values.ts, src/extension.ts, src/uriHandler.ts
Part 1 of 2 for https://github.com/confluentinc/vscode/issues/2528:
- add the `confluent.handleUri` command 👈 
- update E2E tests to use this command for CCloud auth (https://github.com/confluentinc/vscode/pull/2585)
```shell
gulp clicktest
```
=> feat: add dedicated URI handler command

package.json
This PR mainly swaps out the mention of the `confluent.flinkArtifactsPoolSelected` context value (which was removed in https://github.com/confluentinc/vscode/pull/2510) for `confluent.flinkDatabaseSelected` to enable `confluent.flinkdatabase.setUDFsViewMode` in the view again.
I also updated the ordering of the nav actions for that view to more closely match the Schemas view.
No tests, but more justification for https://github.com/confluentinc/vscode/issues/2549 to be done!
=> MINOR: fix Flink artifact/UDF view nav actions

src/clients/flinkArtifacts/models/ArtifactV1FlinkArtifactList.ts, src/clients/sidecar-openapi-specs/flink-artifacts.openapi.yaml, src/clients/sidecar-openapi-specs/patches/flinkartifactlist.patch, src/loaders/ccloudResourceLoader.test.ts, src/loaders/ccloudResourceLoader.ts
Patches the sidecar openapi spec to allow a nullable field for response.data and so swallow the TypeError that is otherwise thrown. Fixes #2278 
-
To test, run the extension dev host.
1. select the Artifacts view. 
2. select a cluster like `ccn_e2e_testmultizone`
3. Verify that no TypeError is thrown 
```shell
gulp clicktest
```
=> UDFs (Artifacts): Fix TypeError when uploading to unavailable AWS region 

package.json, src/commands/flinkArtifacts.ts, src/commands/utils/uploadArtifact.test.ts, src/commands/utils/uploadArtifact.ts
- Rearrange some things so we can upload artifacts from _all the places_. Modifies existing upload command to accept a CCloud Cluster, CCloud Compute Pool, or File URI as `item`
- Refactor `promptForArtifactUploadParams` to use provided `item` info instead of asking the user to select when possible
- Adds a new "explorer/context" menu item - this will create the right-click context menu item for `.jar` files
- Adds a new "view/item/context" menu item to connect uploadArtifacts to these resources
- Another change to the wording of the `uploadArtifact` command `title` so that it looks good in the context menus. 
- Closes #2193
- Closes #2460
| `.jar` file context menu | `cluster` context menu |
| --  | -- |
|<img width="684" height="651" alt="Screenshot 2025-09-10 at 8 03 26 AM" …
=> (UDFs) Artifacts: allow upload from right-click on cluster, compute, or .jar file

src/loaders/ccloudResourceLoader.test.ts, src/loaders/ccloudResourceLoader.ts
- Refactor `determineFlinkQueryables()` into a side part: `toFlinkQueryable()` which can convert either a `CloudFlinkComputePool` or `CCloudKafkaCluster` to a single `IFlinkQueryable`. 
- Simplify the argument of `getFlinkArtifacts()` to match its peer `getUDFs()`: a single `CCloudFlinkDbKafkaCluster`:
- Can then use `toFlinkQueryable`
- No longer any need to drive API calls in parallel, now that will only be making a single API call.
- The only caller to this, from the Flink Database view provider's sub-mode, is doing so with a `CCloudFlinkDbKafkaCluster` instance.
- `toFlinkQueryable()` gets 100% test coverage through existing tests over `determineFlinkQueryables()`.
- This is preliminary work towards enabling caching for `getFlinkArtifacts()`, #2606.
Please check if your PR fulfills …
=> Simplify getFlinkArtifacts(): is only being called with CCloudFlinkDbKafkaCluster

tests/e2e/utils/settings.ts
The main problem was this highlighted part from this screenshot in https://github.com/confluentinc/vscode/issues/2609#issuecomment-3300206479:
Where, upon changing the `window.menuStyle` setting on Windows, a system dialog would show up saying the window needed to be reloaded. That combined with this:
https://github.com/confluentinc/vscode/blob/33195f2a1189891b00c68b649ac954c6ff6f2017/tests/e2e/baseTest.ts#L85-L88
...meant we were automatically restarting the (test) VS Code window and losing our `page` context before tests even started.
Closes #2609, confirmed working on Windows locally.
=> MINOR: fix `window.menuStyle` setting for Windows to unblock running E2E tests

src/commands/index.test.ts, src/commands/index.ts
- Refactor `wrappedCommand` to `createWrappedCommand`
- Added tests for when wrapped commands are async and raise Errors
- Fixes #2445 
```shell
gulp clicktest
```
=> Refactor `wrappedCommand` to be testable

src/commands/medusaCodeLens.test.ts, src/commands/medusaCodeLens.ts, src/errors.ts, src/medusa/api.ts, src/sidecar/connections/local.ts
Transforms the placeholder "Generate Dataset" CodeLens command so that it:
1. Reads the contents of the Avro schema file.
2. Sends the schema as the POST body to the local Medusa endpoint /_/v1/schemas/avro/convert.
3. Receives the converted Medusa Dataset from the endpoint.
4. Prompts the user to save the result as a *.dataset.json file containing the generated dataset.
Attached schema file can be used for click testing: [schema.json](https://github.com/user-attachments/files/22389256/schema.json)
=> 'Generate Dataset' CodeLens creates Dataset file

package.json, src/codelens/avroProvider.test.ts, src/codelens/avroProvider.ts, src/commands/medusaCodeLens.test.ts, src/commands/medusaCodeLens.ts
This PR implements conditional display of Avro schema CodeLens based on Medusa container availability and adds functionality to start the Medusa container directly from the schema file via code lens.
Key Features:
- Conditional CodeLens Display: Avro schema files now only show the 'Generate Dataset' CodeLens action when the Medusa container is running
- Start Medusa Container: Added a new "Start Medusa" CodeLens action that allows users to launch the local Medusa container directly from Avro schema files when the container is not running.
1. Open below schema file in running extension without Medusa container running.
2. Only the 'Start Medusa' option should be visible. 
3. When clicked, Medusa container should start, be visible in local resources UI, and 'Start Medusa' code lens should …
=> 2615 conditionally display the avro schema codelens based on medusa container availability

src/models/environment.ts, src/models/kafkaCluster.ts, src/models/schemaRegistry.ts, src/viewProviders/newResources.ts, tests/e2e/objects/views/ResourcesView.ts, tests/e2e/objects/views/View.ts, tests/e2e/objects/views/viewItems/DirectConnectionItem.ts, tests/e2e/objects/views/viewItems/ViewItem.ts, tests/e2e/objects/webviews/DirectConnectionFormWebview.ts, tests/e2e/specs/directConnectionLifecycle.spec.ts, tests/e2e/utils/connections.ts
New tests that only cover basic CCloud API key/secret connection management.
- valid connection creation, edit, export, disconnect, import
- invalid connection creation and some basic assertions over the error info we show from the notification area and Resources view item
Once https://github.com/confluentinc/vscode/issues/2140 is done, this can be updated so the Kafka/SR config functions use right-click actions on existing local resources to copy Kafka bootstrap server + Schema Registry URL values.
Closes #2025
- This set of tests was more or less the tipping point for some of our connection-setup patterns, and I don't like how much boilerplate has to be copied. The [next branch](https://github.com/confluentinc/vscode/pull/2616) will start refactoring connection-specific setup and …
=> add E2E tests for direct connection CRUD

playwright.config.ts, src/webview/baseTest.ts, src/webview/bindings/bindings.spec.ts, src/webview/bindings/custom-elements.spec.ts, src/webview/direct-connect-form.spec.ts, src/webview/scaffold-form.spec.ts
We were accidentally including `src/clients/` in the webview coverage reporting, and the most straightforward way to include/exclude specific file patterns is to set the [`coverage` fixture](https://github.com/UnknownPrinciple/rollwright/blob/ab6b27a071d9789979f647e2d8faf8a0bebddf9c/packages/rollwright/fixture.d.ts#L14-L16) config to exclude that directory (and some other sensible defaults).
Also updated `playwright.config.ts` to only point at `src/webviews/` since we don't run (let alone have) any `*.spec.ts` files elsewhere that would be run from `gulp functional`.
...
=> fix `gulp functional` coverage reporting

src/viewProviders/newResources.test.ts, src/viewProviders/newResources.ts
- Fix a gap in the new resources view provider that the old provider handled: resetting context values `ContextValues.directSchemaRegistryAvailable` and `ContextValues.directKafkaClusterAvailable` based on if any of the direct connections have a kafka cluster or schema registry. These context values help inform the empty states of the Topics and Schemas views.
- Do so by hooking into whenever `NewResourceViewProvider` signals to VS Code to repaint any portion of the view, which is the tailmost operation of whenever one of the connection rows have been updated.
- Having the view responsible for this action doesn't seem the best possible place for this responsibility, but it 1) does have all of the necessary information (access to all of the direct connections with updated state) and also …
=> Fix newResourceViewProvider gap in resetting direct connection context values

Gulpfile.js
=> fix: ignore `src/webviews/baseTest.ts` when building webview stuff

src/commands/flinkStatements.ts, src/loaders/ccloudResourceLoader.test.ts, src/loaders/ccloudResourceLoader.ts, src/quickpicks/kafkaClusters.test.ts
- Fix #2631 through logically reverting recent change where `CCloudResourceLoader.getOrganization()` as made to never return `undefined`, but instead to raise an Error. That good deed was misguided in not realizing that `getOrganization()` was the closest thing to checking for "are we logged into ccloud", directly or indirectly, by codepaths that gather up all accessible environments through a loop over all `ResourceLoader.loaders()`. CCloudResourceLoader is always returned, for better or worse at this point, and its `getEnvironments() is ultimately coded to eventually short circuit if `getOrganization` ultimately returns undefined. So, reinstate that behavior, then respell the recent bits of Flink-ness which were coded assuming it would always return a number (or an Error).
- Now the …
=> Fix kafkaclusterpick vs not ccloud logged in.

CHANGELOG.md, src/utils/dateUtils.test.ts, src/utils/dateUtils.ts, src/webview/message-viewer.html, src/webview/message-viewer.ts
This PR swaps the text input for adding a timestamp (milliseconds since epoch) for a combo text input + date/time picker when setting the consume mode to `From date/time` (previously `From timestamp`):
https://github.com/user-attachments/assets/fd8ad402-ba39-432c-93fe-5df592ee1c86
To do this, we're taking the existing text field -- (converted from `vscode-text-field` to a regular text `input` since `vscode-webview-ui-toolkit` is [no longer supported](https://github.com/confluentinc/vscode/issues/842)) -- and adding a datetime-local `input` right next to it, but styling it like a button.
> [!NOTE]
> This is because [the default behavior of that kind of input](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/datetime-local) prevents pasting (timestamp- or …
=> add date/time picker to topic mesage viewer

package.json, src/extension.test.ts, src/extension.ts, src/viewProviders/baseModels/base.ts, src/viewProviders/baseModels/parentedBase.test.ts, src/viewProviders/baseModels/parentedBase.ts, src/viewProviders/flinkDatabase.ts
- New command / title bar action for force refreshing the Flink Database view.
- Refreshes only the current modal delegate (at this time).
While here and was clicktesting, happend to wander into clicktest path of 'log in, set the Flink database in the view, then log out from CCloud, and then finally logging back in', then being unhappy with the view states when logged out as well as when logged back in:
- When logged out after having set the view state, the view title wasn't cleared.
- When logged back in, the default view state still thought that a database had been selected even though the logout had cleared it.
So, this branch also fixes both of those issues (both were due to insufficient / wrong code in `ParentedBaseViewProvider::setParentResource()`) and more thoroughly flesh out its …
=> Refresh action for the FlinkDB view + misc state change fixes

CHANGELOG.md, package.json, src/commands/flinkComputePools.ts, src/extensionSettings/base.ts, src/extensionSettings/constants.ts
⚠️ Users who previously set a custom value for `confluent.flink.enableConfluentCloudLanguageServer` or `confluent.flink.enableFlinkArtifacts` may need to update their Flink settings for the extension. 
Go to **Preferences > Open Settings (UI) > Extensions > Confluent** to view and access Confluent extension settings. 
- Closes #2656
- "Flink SQL Defaults" -> "Flink" : Rename this section of our extension settings since we've expanded beyond FlinkSQL. 
- Reorder the settings so that users see the two "enable" flags first, followed by the rest in ABC order (this is vscode default if there is no "order" property, and it works well imo since Compute Pool and Database defaults come first) 
| Close up at the top | All settings (outdated titles, see left) |
| -- | -- | 
|  <img width="1233" …
=> Rename and reorder Flink extension settings

.github/ISSUE_TEMPLATE/bug_report.yml
We don't use the `bug` label, and we have Feature/Task/Bug issue types.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#:~:text=String-,type,and%20can%20be%20used%20to%20create%20a%20shared%20syntax%20across%20repos.,-Optional
=> MINOR: update issue template to use Bug type instead of `bug` label [ci skip]

src/authz/schemaRegistry.test.ts, src/authz/topics.test.ts, src/commands/topics.test.ts, src/commands/utils/uploadArtifactOrUDF.test.ts, src/directConnectManager.test.ts, src/loaders/ccloudResourceLoader.test.ts, src/loaders/loaderUtils.test.ts, src/loaders/resourceLoader.test.ts, src/projectGeneration/templates.test.ts, src/sidecar/connections/index.test.ts, tests/createResultsManager.ts
Replaces (hopefully all) old methods of stubbing the `SidecarHandle`.
Closes #2233
=> MINOR test cleanup: standardize `getSidecarStub()` usage

src/commands/flinkUDFs.test.ts, src/commands/flinkUDFs.ts
- Closes #2662 
- Sets the Flink URI metadata for the new document that we open when running the "register UDF with Editor" flow
- Adds imports and uses the results from `flinkDatabaseProvider.database` and `CCloudResourceLoader.getEnvironment`
1. Make sure your settings have Flink Artifacts `enabled` 
2. Log in to Confluent Cloud in the extension
3. Choose a database that has artifacts in the Flink Artifacts view panel (or upload a new artifact). To verify defaults don't get picked up, choose a database that is in a different region/provider than your Default Flink Database setting
4. Right-click on an artifact and choose Register with Flink SQL option to open a new sql code editor document.
**Verify that**: 
- ... you see the option to Submit the statement right away. 
- ... you do …
=> Update doc metadata for codelens on new CREATE FUNCTION statements

src/authn/ccloudProvider.test.ts, src/authn/ccloudProvider.ts, src/authn/ccloudStateHandling.ts, src/authn/errors.ts, src/authn/utils.ts, src/commands/connections.test.ts, src/commands/connections.ts, src/emitters.ts, src/extension.ts, src/sidecar/logging.test.ts, src/sidecar/logging.ts, src/sidecar/sidecarManager.test.ts, src/sidecar/sidecarManager.ts, src/uriHandler.ts
We wanted easier ways of gathering sidecar logs while handling different CCloud sign-in issues, so I:
- updated `gatherSidecarOutputs()` to use a single `options` param with some defaults for the log path, stderr path, and number of log lines to work with
- set up the error scenarios while signing in (before converting to a VS Code `AuthenticationSession`) to use a new `.signInError()` method which creates (new) `CCloudSignInError`s while also gathering and sending sidecar logs to Sentry for our team to investigate for follow-up fixing
- all of that to say that that cases like this just mean "grab the sidecar logs, send to sentry, and prep a `CCloudSignInError` to throw":
> [!TIP]
> The majority of lines changed here are from updating `authn/ccloudProvider.test.ts` so it fit our …
=> add more logging when CCloud auth fails

src/commands/flinkUDFs.ts, src/commands/utils/uploadArtifactOrUDF.ts
Fixes #2652 
Updates the copy in both UDF flows (editor and guided user input) to hint that the user will need to enter the fully qualified class name. 
1. Open extension dev host
2. Connect to Confluent Cloud and select a cluster with artifactsw
3. Right-click on an Artifact and select a UDF registration path
4. Confirm that there is copy to indicate that user needs fully qualified classname like the screenshots below 
_______________________________________________________________________________________
=> Minor (UDFs): update copy to indicate fully classified name needed

src/codelens/flinkSqlProvider.test.ts, src/codelens/flinkSqlProvider.ts, src/commands/flinkUDFs.test.ts, src/commands/flinkUDFs.ts, src/commands/utils/uploadArtifactOrUDF.test.ts, src/commands/utils/uploadArtifactOrUDF.ts, src/viewProviders/baseModels/parentedBase.ts, tests/unit/testUtils.ts
This is mostly follow-up work to allow the codelens helper functions to look up catalog/database metadata just based off of the IDs alone (which is all we have at the time we use a Flink artifact to create a UDF without using the loader to look up parent resource names):
https://github.com/confluentinc/vscode/blob/fdd12d21a1391b821d571726ac03a6a74da62afe/src/commands/flinkUDFs.ts#L62-L68
Closes #2707
1. Sign into CCloud
2. Select a Flink database while in the artifacts view mode
3. Right-click an artifact and select `Register Flink Artifact with Flink SQL` to open the `CREATE FUNCTION` statement editor
4. Expect the Flink view provider's focused database (and parent catalog) to be pre-filled in the codelens (which is the existing behavior, so this is just making sure it isn't broken)
- …
=> update FlinkSqlCodelensProvider to allow going off of just catalog/database ID metadata (without names)

tests/e2e/objects/views/viewItems/FlinkComputePoolItem.ts, tests/e2e/objects/webviews/ProjectScaffoldWebview.ts, tests/e2e/specs/scaffold.spec.ts, tests/e2e/utils/scaffold.ts
This change introduces a new E2E test that makes sure we can generate a new project from the right-click context menu of a Flink compute pool item in the Resources view.
-
=> Add E2E test covering generating project from Flink compute pool

src/loaders/ccloudResourceLoader.ts, src/loaders/ccloudResourceLoaderUtils.test.ts, src/loaders/ccloudResourceLoaderUtils.ts
- Refine the SQL used to query for UDFs and their parameters by limiting both halves of the query to a single Flink database (by its id, via `INFORMATION_SCHEMA.ROUTINES` and `PARAMETERS` views's common column `SPECIFIC_SCHEMA_ID` , doc'd as "The ID of the database").
- I missed including that filter previously, so were getting ... perhaps all of the UDFs in the cloud/region/environment, yet claiming were just for a single Flink database.
1. Select one of our Flink databases as a Flink database, then switch to the UDFs view. Should now only see fewer UDFs, and they should match the list offered by Flink Workspace's 'Functions' schema browser subset for the same database, then nothing to hang a bad 'delete UDF' action from.
- Closes #2765 in v1.7.x timeline.
- Also preemptively fixes …
=> [1.7] Add proper WHERE clauses to the UDFs system catalog query

src/loaders/ccloudResourceLoader.ts, src/loaders/ccloudResourceLoaderUtils.test.ts, src/loaders/ccloudResourceLoaderUtils.ts
- Bring #2772 forward into main.
- Refine the system catalog query used for gathering UDF information to limit to a single Flink database id
=> [main] Add proper WHERE clauses to the UDFs system catalog query

package.json, src/extension.test.ts, src/extension.ts, tests/e2e/specs/directConnectionLifecycle.spec.ts
Follow-up to https://github.com/confluentinc/vscode/pull/2743 now that there is no old Resource view provider, which implemented the top-level refresh. The new provider has connection-row-level refreshes.
1.
-
=> MINOR cleanup: remove top-level Resources view refresh command 

CHANGELOG.md
This PR adds the fix of Avro union type encoding, links to GitHub issues, and links to the Confluent docs to the changelog for 1.7.x.
=> [v1.7.x] MINOR: refine changelog

package-lock.json
```
❯ npm audit    
axios  1.0.0 - 1.11.0
Severity: high
Axios is vulnerable to DoS attack through lack of data size check - https://github.com/advisories/GHSA-4hjh-wcwx-xvwj
fix available via `npm audit fix`
node_modules/axios
@openapitools/openapi-generator-cli  2.8.0 - 2.23.1
Depends on vulnerable versions of axios
node_modules/@openapitools/openapi-generator-cli
hono  <4.9.7
Severity: moderate
Hono has Body Limit Middleware Bypass - https://github.com/advisories/GHSA-92vj-g62v-jqhh
fix available via `npm audit fix`
node_modules/hono
tar-fs  2.0.0 - 2.1.3
Severity: high
tar-fs has a symlink validation bypass if destination directory is predictable with a specific tarball - https://github.com/advisories/GHSA-vj76-c3g6-qr5v
fix available via `npm audit fix`
node_modules/tar-fs
4 …
```
=> [v1.7.x] security: update `axios`, `hono`, and `tar-fs`
